!function(){var k={scope:{}};k.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[g]=c.value)};k.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};k.global=k.getGlobal(this);k.SYMBOL_PREFIX="jscomp_symbol_";
k.initSymbol=function(){k.initSymbol=function(){};k.global.Symbol||(k.global.Symbol=k.Symbol)};k.symbolCounter_=0;k.Symbol=function(a){return k.SYMBOL_PREFIX+(a||"")+k.symbolCounter_++};k.initSymbolIterator=function(){k.initSymbol();var a=k.global.Symbol.iterator;a||(a=k.global.Symbol.iterator=k.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&k.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return k.arrayIterator(this)}});k.initSymbolIterator=function(){}};
k.arrayIterator=function(a){var g=0;return k.iteratorPrototype(function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}})};k.iteratorPrototype=function(a){k.initSymbolIterator();a={next:a};a[k.global.Symbol.iterator]=function(){return this};return a};k.makeIterator=function(a){k.initSymbolIterator();k.initSymbol();k.initSymbolIterator();var g=a[Symbol.iterator];return g?g.call(a):k.arrayIterator(a)};k.arrayFromIterator=function(a){for(var g,c=[];!(g=a.next()).done;)c.push(g.value);return c};
k.arrayFromIterable=function(a){return a instanceof Array?a:k.arrayFromIterator(k.makeIterator(a))};k.inherits=function(a,g){function c(){}c.prototype=g.prototype;a.prototype=new c;a.prototype.constructor=a;for(var f in g)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(g,f);d&&Object.defineProperty(a,f,d)}else a[f]=g[f]};k.owns=function(a,g){return Object.prototype.hasOwnProperty.call(a,g)};
k.polyfill=function(a,g){if(g){var c=k.global;a=a.split(".");for(var f=0;f<a.length-1;f++){var d=a[f];d in c||(c[d]={});c=c[d]}a=a[a.length-1];f=c[a];g=g(f);g!=f&&null!=g&&k.defineProperty(c,a,{configurable:!0,writable:!0,value:g})}};
k.polyfill("WeakMap",function(a){function g(d){this.id_=(b+=Math.random()+1).toString();if(d){k.initSymbol();k.initSymbolIterator();d=k.makeIterator(d);for(var h;!(h=d.next()).done;)h=h.value,this.set(h[0],h[1])}}function c(b){k.owns(b,d)||k.defineProperty(b,d,{value:{}})}function f(b){var h=Object[b];h&&(Object[b]=function(b){c(b);return h(b)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),h=Object.seal({}),d=new a([[b,2],[h,3]]);if(2!=d.get(b)||3!=d.get(h))return!1;d.delete(b);
d.set(h,4);return!d.has(b)&&4==d.get(h)}catch(q){return!1}}())return a;var d="$jscomp_hidden_"+Math.random().toString().substring(2);f("freeze");f("preventExtensions");f("seal");var b=0;g.prototype.set=function(b,h){c(b);if(!k.owns(b,d))throw Error("WeakMap key fail: "+b);b[d][this.id_]=h;return this};g.prototype.get=function(b){return k.owns(b,d)?b[d][this.id_]:void 0};g.prototype.has=function(b){return k.owns(b,d)&&k.owns(b[d],this.id_)};g.prototype.delete=function(b){return k.owns(b,d)&&k.owns(b[d],
this.id_)?delete b[d][this.id_]:!1};return g},"es6-impl","es3");k.ASSUME_NO_NATIVE_MAP=!1;
k.polyfill("Map",function(a){function g(){var b={};return b.previous=b.next=b.head=b}function c(b,d){var h=b.head_;return k.iteratorPrototype(function(){if(h){for(;h.head!=b.head_;)h=h.previous;for(;h.next!=h.head;)return h=h.next,{done:!1,value:d(h)};h=null}return{done:!0,value:void 0}})}function f(h,d){var c;c=d&&typeof d;"object"==c||"function"==c?b.has(d)?c=b.get(d):(c=""+ ++r,b.set(d,c)):c="p_"+d;var f=h.data_[c];if(f&&k.owns(h.data_,c))for(h=0;h<f.length;h++){var a=f[h];if(d!==d&&a.key!==a.key||
d===a.key)return{id:c,list:f,index:h,entry:a}}return{id:c,list:f,index:-1,entry:void 0}}function d(b){this.data_={};this.head_=g();this.size=0;if(b){b=k.makeIterator(b);for(var h;!(h=b.next()).done;)h=h.value,this.set(h[0],h[1])}}if(!k.ASSUME_NO_NATIVE_MAP&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a(k.makeIterator([[b,"s"]]));if("s"!=d.get(b)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var c=d.entries(),
f=c.next();if(f.done||f.value[0]!=b||"s"!=f.value[1])return!1;f=c.next();return f.done||4!=f.value[0].x||"t"!=f.value[1]||!c.next().done?!1:!0}catch(w){return!1}}())return a;k.initSymbol();k.initSymbolIterator();var b=new WeakMap;d.prototype.set=function(b,d){var h=f(this,b);h.list||(h.list=this.data_[h.id]=[]);h.entry?h.entry.value=d:(h.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:b,value:d},h.list.push(h.entry),this.head_.previous.next=h.entry,this.head_.previous=h.entry,
this.size++);return this};d.prototype.delete=function(b){b=f(this,b);return b.entry&&b.list?(b.list.splice(b.index,1),b.list.length||delete this.data_[b.id],b.entry.previous.next=b.entry.next,b.entry.next.previous=b.entry.previous,b.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};d.prototype.has=function(b){return!!f(this,b).entry};d.prototype.get=function(b){return(b=f(this,b).entry)&&b.value};d.prototype.entries=function(){return c(this,
function(b){return[b.key,b.value]})};d.prototype.keys=function(){return c(this,function(b){return b.key})};d.prototype.values=function(){return c(this,function(b){return b.value})};d.prototype.forEach=function(b,d){for(var c=this.entries(),h;!(h=c.next()).done;)h=h.value,b.call(d,h[1],h[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var r=0;return d},"es6-impl","es3");k.ASSUME_NO_NATIVE_SET=!1;
k.polyfill("Set",function(a){function g(c){this.map_=new Map;if(c){c=k.makeIterator(c);for(var f;!(f=c.next()).done;)this.add(f.value)}this.size=this.map_.size}if(!k.ASSUME_NO_NATIVE_SET&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),f=new a(k.makeIterator([c]));if(!f.has(c)||1!=f.size||f.add(c)!=f||1!=f.size||f.add({x:4})!=f||2!=f.size)return!1;var d=f.entries(),b=d.next();if(b.done||b.value[0]!=c||b.value[1]!=c)return!1;b=d.next();return b.done||
b.value[0]==c||4!=b.value[0].x||b.value[1]!=b.value[0]?!1:d.next().done}catch(r){return!1}}())return a;k.initSymbol();k.initSymbolIterator();g.prototype.add=function(c){this.map_.set(c,c);this.size=this.map_.size;return this};g.prototype.delete=function(c){c=this.map_.delete(c);this.size=this.map_.size;return c};g.prototype.clear=function(){this.map_.clear();this.size=0};g.prototype.has=function(c){return this.map_.has(c)};g.prototype.entries=function(){return this.map_.entries()};g.prototype.values=
function(){return this.map_.values()};g.prototype[Symbol.iterator]=g.prototype.values;g.prototype.forEach=function(c,f){var d=this;this.map_.forEach(function(b){return c.call(f,b,b,d)})};return g},"es6-impl","es3");k.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");k.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6-impl","es3");
k.polyfill("Number.isInteger",function(a){return a?a:function(a){return Number.isFinite(a)?a===Math.floor(a):!1}},"es6-impl","es3");k.polyfill("Number.isSafeInteger",function(a){return a?a:function(a){return Number.isInteger(a)&&Math.abs(a)<=Number.MAX_SAFE_INTEGER}},"es6-impl","es3");k.array=k.array||{};
k.iteratorFromArray=function(a,g){k.initSymbolIterator();a instanceof String&&(a+="");var c=0,f={next:function(){if(c<a.length){var d=c++;return{value:g(d,a[d]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};k.polyfill("Array.prototype.entries",function(a){return a?a:function(){return k.iteratorFromArray(this,function(a,c){return[a,c]})}},"es6-impl","es3");
k.polyfill("Array.prototype.values",function(a){return a?a:function(){return k.iteratorFromArray(this,function(a,c){return c})}},"es6","es3");k.checkStringArgs=function(a,g,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(g instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
k.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var f=k.checkStringArgs(this,a,"startsWith");a+="";var d=f.length,b=a.length;c=Math.max(0,Math.min(c|0,f.length));for(var r=0;r<b&&c<d;)if(f[c++]!=a[r++])return!1;return r>=b}},"es6-impl","es3");
k.polyfill("String.prototype.repeat",function(a){return a?a:function(a){var c=k.checkStringArgs(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var f="";a;)if(a&1&&(f+=c),a>>>=1)c+=c;return f}},"es6-impl","es3");
require=function pa(g,c,f){function d(h,r){if(!c[h]){if(!g[h]){var q="function"==typeof require&&require;if(!r&&q)return q(h,!0);if(b)return b(h,!0);r=Error("Cannot find module '"+h+"'");throw r.code="MODULE_NOT_FOUND",r;}r=c[h]={exports:{}};g[h][0].call(r.exports,function(b){var c=g[h][1][b];return d(c?c:b)},r,r.exports,pa,g,c,f)}return c[h].exports}for(var b="function"==typeof require&&require,r=0;r<f.length;r++)d(f[r]);return d}({"/client-side/binary-ajax.js":[function(){(function(a){a.ajaxTransport("+*",
function(a){if(window.FormData&&("blob"===a.dataType||"arraybuffer"===a.dataType||a.data&&(window.Blob&&a.data instanceof Blob||window.ArrayBuffer&&a.data instanceof ArrayBuffer))){var c;return{send:function(f,d){var b=a.url||location.href,r=a.type||"GET",h=a.dataType||"text",t=a.data||null,q=a.async||!0;c=new XMLHttpRequest;c.addEventListener("load",function(){var b={};200<=c.status&&300>c.status||304===c.status?b[h]=c.response:b.text=c.statusText;d(c.status,c.statusText,b,c.getAllResponseHeaders())});
c.open(r,b,q);c.responseType=h;for(var g in f)({}).hasOwnProperty.call(f,g)&&c.setRequestHeader(g,f[g]);c.send(t)},abort:function(){c&&c.abort()}}}})})(jQuery)},{}],"/client-side/common.js":[function(a){var g=a("/lib/assert.js");g.instanceOf(window.Map,Function);g.instanceOf(window.Set,Function);g.instanceOf(window.ArrayBuffer,Function);g.instanceOf(window.Uint8Array,Function);g.instanceOf(window.Symbol,Function);a("/client-side/binary-ajax.js");if(!window.sb){window.sb=a("/structure-types.js");a=
a("/recursive-registry.js");for(var c in a)({}).hasOwnProperty.call(a,c)&&(window.sb[c]=a[c])}else if(!(window.sb instanceof Object))throw Error("window.sb is already defined");},{"/client-side/binary-ajax.js":"/client-side/binary-ajax.js","/lib/assert.js":"/lib/assert.js","/recursive-registry.js":"/recursive-registry.js","/structure-types.js":"/structure-types.js"}],"/config.js":[function(a,g){var c="/";"/"===c&&(c="");c=a(c+"/lib/assert.js");a=a("base64-js");c.between(0,9,65536);c=new ArrayBuffer(2);
(new DataView(c)).setUint16(0,9);a=a.fromByteArray(new Uint8Array(c));g.exports={VERSION_STRING:a}},{"base64-js":2}],"/lib/assert.js":[function(a,g){var c=a("/lib/util-inspect.js"),f=g.exports={instanceOf:function(d,b){b instanceof Array||(b=[b]);for(var a=!1,h=k.makeIterator(b),f=h.next();!f.done;f=h.next())if(f=f.value,d instanceof f||void 0!==d&&null!==d&&d.constructor===f){a=!0;break}if(!a)throw new TypeError(c.inspect(d)+" is not an instance of "+b.map(function(b){return b.name}).join(" or "));
},integer:function(d){f.instanceOf(d,Number);if(!Number.isSafeInteger(d))throw new RangeError(c.inspect(d)+" is not an integer");},between:function(d,b,a,h){if(b<d||b>=a){d=c.inspect(b)+" is not in ["+c.inspect(d)+","+c.inspect(a)+")";if(void 0===h)throw new RangeError(d);throw new RangeError(h+" ("+d+")");}},byteUnsignedInteger:function(d){f.integer(d);f.between(0,d,256)},twoByteUnsignedInteger:function(d){f.integer(d);f.between(0,d,65536)},fourByteUnsignedInteger:function(d){f.integer(d);f.between(0,
d,4294967296)},fail:function(d){throw Error(d);},assert:function(d,b){d||f.fail(b)},throws:function(d,b){var a=!0;try{d(),a=!1}catch(h){void 0!==b&&f.message(h,b)}f.assert(a,"Should throw an error")},equal:function(d,b){var a=new RangeError("Expected "+c.inspect(b)+" but got "+c.inspect(d));if(b&&b.constructor===Object)for(var h in b){if({}.hasOwnProperty.call(b,h))try{f.equal(d[h],b[h])}catch(q){throw a;}}else if(b&&b.constructor===Array){if(!d||d.constructor!==Array)throw a;try{f.equal(d.length,
b.length)}catch(q){throw a;}for(h=0;h<b.length;h++)try{f.equal(d[h],b[h])}catch(q){throw a;}}else if(b&&b.constructor===Map){if(!d||d.constructor!==Map)throw a;try{f.equal(d.size,b.size)}catch(q){throw a;}b=b.entries();for(d=d.entries();!(h=b.next()).done;)try{f.equal(h.value,d.next().value)}catch(q){throw a;}}else if(b&&b.constructor===Set){if(!d||d.constructor!==Set)throw a;try{f.equal(d.size,b.size)}catch(q){throw a;}b=b.values();for(d=d.values();!(h=b.next()).done;)try{f.equal(h.value,d.next().value)}catch(q){throw a;
}}else if(b&&b.constructor===ArrayBuffer){if(!d||d.constructor!==ArrayBuffer)throw a;try{f.equal(d.byteLength,b.byteLength)}catch(q){throw a;}d=new Uint8Array(d);b=new Uint8Array(b);try{for(h=0;h<b.length;h++)f.equal(d[h],b[h])}catch(q){throw a;}}else if(void 0!==b&&null!==b&&b.equals instanceof Function){var t;try{t=b.equals(d)}catch(q){throw Error("equals() is not implemented for "+c.inspect(b));}if(!t)throw a;}else if(b!==d)throw a;},message:function(a,b){f.instanceOf(b,String);f.assert(a&&a.message.startsWith(b),
'Message "'+(a?a.message:"No error thrown")+'" does not start with "'+b+'"')}}},{"/lib/util-inspect.js":"/lib/util-inspect.js"}],"/lib/bit-math.js":[function(a,g){g.exports={dividedByEight:function(a){return a>>>3},modEight:function(a){return a&7}}},{}],"/lib/buffer-string.js":[function(a,g){(function(c){var f=a(c+"/assert.js"),d=a(c+"/growable-buffer.js");g.exports={toString:function(b){b&&b.constructor===ArrayBuffer&&(b=new Uint8Array(b));f.instanceOf(b,Uint8Array);for(var a=[],d=0;d<b.length;){var c=
b[d],q=void 0,g=239<c?4:223<c?3:191<c?2:1;if(d+g<=b.length){var w,C,z;switch(g){case 1:128>c&&(q=c);break;case 2:w=b[d+1];128===(w&192)&&(c=(c&31)<<6|w&63,127<c&&(q=c));break;case 3:w=b[d+1];C=b[d+2];128===(w&192)&&128===(C&192)&&(c=(c&15)<<12|(w&63)<<6|C&63,2047<c&&(55296>c||57343<c)&&(q=c));break;case 4:w=b[d+1],C=b[d+2],z=b[d+3],128===(w&192)&&128===(C&192)&&128===(z&192)&&(c=(c&15)<<18|(w&63)<<12|(C&63)<<6|z&63,65535<c&&1114112>c&&(q=c))}}void 0===q?(q=65533,g=1):65535<q&&(q-=65536,a.push(q>>>
10&1023|55296),q=56320|q&1023);a.push(q);d+=g}b="";for(d=0;d<a.length;d+=4096)b+=String.fromCharCode.apply(String,[].concat(k.arrayFromIterable(a.slice(d,d+4096))));return b},fromString:function(b){f.instanceOf(b,String);var a=new d;b=k.makeIterator(b);for(var c=b.next();!c.done;c=b.next())c=c.value.charCodeAt(0),128>c?a.add(c):(2048>c?a.add(192|c>>6):(55296>c||57344<=c?a.add(224|c>>12):(c=65536+((c&1023)<<10|c&1023),a.add(240|c>>18),a.add(128|c>>12&63)),a.add(128|c>>6&63)),a.add(128|c&63));return a.toBuffer()},
toBinaryString:function(b){f.instanceOf(b,ArrayBuffer);var a="";b=new Uint8Array(b);b=k.makeIterator(b);for(var c=b.next();!c.done;c=b.next())a+=String.fromCharCode(c.value);return a},fromBinaryString:function(b){f.instanceOf(b,String);for(var a=new ArrayBuffer(b.length),c=new Uint8Array(a),d=0;d<b.length;d++)c[d]=b[d].charCodeAt(0);return a}}}).call(this,"/lib")},{}],"/lib/growable-buffer.js":[function(a,g){(function(c){function f(b){b=void 0===b?10:b;try{d.integer(b),d.between(0,b,Number.MAX_SAFE_INTEGER+
1)}catch(r){throw new RangeError(String(b)+" is not a valid buffer length");}this.buffer=new ArrayBuffer(b);this.size=0}var d=a(c+"/assert.js");f.prototype.grow=function(b){d.integer(b);b>this.buffer.byteLength&&(b=new ArrayBuffer(b<<1),(new Uint8Array(b)).set((new Uint8Array(this.buffer)).subarray(0,this.size)),this.buffer=b);return this};f.prototype.set=function(b,a){d.integer(b);d.integer(a);d.between(0,b,this.size,"Index out of bounds: "+String(b));d.between(0,a,256,"Not a byte: "+String(a));
(new Uint8Array(this.buffer))[b]=a;return this};f.prototype.setAll=function(b,a){d.instanceOf(a,ArrayBuffer);d.integer(b);d.between(0,b,this.size-a.byteLength+1,"Index out of bounds: "+String(b));(new Uint8Array(this.buffer)).set(new Uint8Array(a),b);return this};f.prototype.get=function(b){d.integer(b);d.between(0,b,this.size,"Index out of bounds: "+String(b));return(new Uint8Array(this.buffer))[b]};f.prototype.add=function(b){var a=this.size,c=a+1;this.grow(c);this.size=c;(new Uint8Array(this.buffer))[a]=
b;return this};f.prototype.addAll=function(b){d.instanceOf(b,ArrayBuffer);var a=this.size,c=this.size+b.byteLength;this.grow(c);this.size=c;(new Uint8Array(this.buffer)).set(new Uint8Array(b),a);return this};f.prototype.toBuffer=function(){return this.buffer.slice(0,this.size)};k.global.Object.defineProperties(f.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.size}},rawBuffer:{configurable:!0,enumerable:!0,get:function(){return this.buffer}}});g.exports=f}).call(this,"/lib")},
{}],"/lib/strint.js":[function(a,g){var c={};(function(){function a(b){return F(b)?b.length-1:b.length}function d(b,c){w(b);l(c,"number");return c>=a(b)?"0":b.charAt(b.length-c-1)}function b(b,a){C(b);z(a);for(var c=0;c<a;c++)b="0"+b;return b}function g(a,c){C(a);z(c);return b(a,c-a.length)}function h(b,a){if(F(b)||F(a))throw Error("Both operands must be positive: "+b+" "+a);var c=Math.max(b.length,a.length);b=g(b,c);a=g(a,c);return b<a}function t(a,c){C(a);C(c);if(e(a,"0")&&e(c,"0"))return"0";for(var f=
Math.max(a.length,c.length),h="",x=0,q=0,u=0;u<f;u++){for(var l=Number(d(a,u)),m=Number(d(c,u)),l=l+m+x,x=0;10<=l;)l-=10,x++;0===l?q++:(h=String(l)+b(h,q),q=0)}0<x&&(h=String(x)+b(h,q));return h}function q(b,a){return M(b)===M(a)}function B(b,a){for(;0<a;)b+="0",a--;return b}function w(b){l(b,"string")}function C(b){w(b);if(!M.call(null,b))throw Error("Condition isPositive failed for value "+b);}function z(b){l(b,"number");if(0>b)throw Error("Expected a positive number: "+b);}function l(b,a){if(typeof b!==
a)throw Error("Not a "+a+": "+b);}var J=c.subPositive=function(a,c){C(a);C(c);if(!m(a,c))throw Error("x must be greater or equal to y");for(var e=Math.max(a.length,c.length),f="",h=0,x=0,q=0;q<e;q++){for(var u=Number(d(a,q))-h,h=0,l=Number(d(c,q));u<l;)u+=10,h++;u=String(u-l);"0"!==u?(f=u+b(f,x),x=0):x++}return 0===f.length?"0":f},K=c.add=function(b,a){w(b);w(a);if(M(b)&&M(a))return t(b,a);if(F(b)&&F(a))return Q(t(G(b),G(a)));if(I(G(b),G(a))){var c=b;b=a;a=c}a=J(G(b),G(a));return M(b)?a:Q(a)},H=c.sub=
function(b,a){w(b);w(a);return K(b,Q(a))},E=c.timesDigit=function(c,e){C(c);l(e,"number");for(var f="",h=a(c),x=0,q=0,u=0;u<h;u++){for(var m=Number(d(c,u))*e+x,x=0;10<=m;)m-=10,x++;0===m?q++:(f=String(m)+b(f,q),q=0)}0<x&&(f=String(x)+b(f,q));return 0===f.length?"0":f},u=c.mulPositive=function(b,c){C(b);C(c);for(var e="0",f=a(c),x=0;x<f;x++)var h=E(b,Number(d(c,x))),h=B(h,x),e=t(e,h);return e},x=c.mul=function(b,a){w(b);w(a);if(e(b,"0")||e(a,"0"))return"0";var c=u(G(b),G(a));return q(b,a)?c:Q(c)},
O=c.quotientRemainderPositive=function(b,a){C(b);C(a);if(e(b,a))return["1","0"];if(n(a,b))return["0",S(b)];for(var c="0",d=b.length-a.length;;){for(var f=b.slice(0,b.length-d);m(f,a);)f=H(f,a),c=K(c,"1");b=f+b.slice(b.length-d);if(n(a,b))return c=B(c,d),[c,S(b)];d--;c=B(c,1);if(0>d)throw Error("Illegal state");}};c.div=function(b,a,c){c=void 0===c?!1:c;w(b);w(a);var d=O(G(b),G(a))[0];q(b,a)||(d=Q(d));!c||e(x(d,a),b)||q(b,a)||(d=H(d,"1"));return d};var e=c.eq=function(b,a){return S(b)===S(a)},I=c.lt=
function(b,a){return F(b)&&M(a)?!0:M(b)&&F(a)?!1:F(b)&&F(a)?!e(b,a)&&!h(G(b),G(a)):h(b,a)},m=c.ge=function(b,a){return!I(b,a)},n=c.gt=function(b,a){return e(b,a)?!1:m(b,a)},F=c.isNegative=function(b){w(b);return 0===b.indexOf("-")},M=c.isPositive=function(b){return!F(b)},G=c.abs=function(b){return F(b)?Q(b):b},Q=c.negate=function(b){return"0"===b?"0":F(b)?b.slice(1):"-"+b},X=/^(-?)0*([1-9][0-9]*)$/,N=/^0+$/,S=c.normalize=function(b){if(N.test(b))return"0";var a=X.exec(b);if(!a)throw Error("Illegal strint format: "+
b);return a[1]+a[2]}})();c.LONG_UPPER_SHIFT="4294967296";c.BYTE_SHIFT="256";g.exports=c},{}],"/lib/util-inspect.js":[function(a,g,c){c.inspect=function(a){if(void 0===a)return"undefined";if(null===a||a.constructor===Object||a.constructor===Array||a.constructor===String||a.constructor===Number||a.constructor===Boolean||a.constructor===Date)return JSON.stringify(a);if(a.constructor===Set){var d="Set {";a=a.values();for(var b=a.next();!b.done;)d+=c.inspect(b.value),b=a.next(),b.done||(d+=", ");return d+
"}"}if(a.constructor===Map){d="Map {";a=a.entries();for(b=a.next();!b.done;)d+=c.inspect(b.value[0]),d+=" \x3d\x3e ",d+=c.inspect(b.value[1]),b=a.next(),b.done||(d+=", ");return d+"}"}return a.constructor.name?a.constructor.name+" "+JSON.stringify(a):JSON.stringify(a)}},{}],"/read.js":[function(a,g){(function(c){function f(b,a){try{return{value:(new DataView(b)).getUint32(a),length:4}}catch(O){q.fail("Buffer is not long enough")}}function d(b,a){return b.length<a?"0".repeat(a-b.length)+b:b}function b(b,
a){switch(b.constructor){case l.ArrayType:return Array(a);case l.TupleType:return Array(b.length);case l.MapType:return new Map;case l.SetType:return new Set;case l.StructType:return{};default:throw Error("Invalid type for base value: "+J.inspect(b));}}function r(b){var a=b.buffer,c=b.offset,d=b.count;b=b.baseValue||Array(d);var d=B.modEight(b.length),f=B.dividedByEight(b.length),d=d?f+1:f;q.assert(a.byteLength>=c+d,"Buffer is not long enough");a=new Uint8Array(a);for(f=0;f<d;f++)for(var h=a[c+f],
u=0;8>u;u++){var l=8*f+u;if(l===b.length)break;b[l]=!!(h&1<<B.modEight(~B.modEight(u)))}return{value:b,length:d}}function h(a){var c=a.buffer,d=a.pointerStart,e=a.offset,g=a.type;a=a.baseValue;var m,n;switch(g.constructor){case l.ByteType:n=1;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=(new Int8Array(c))[e];break;case l.ShortType:n=2;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=(new DataView(c)).getInt16(e);break;case l.IntType:n=4;m=(new DataView(c)).getInt32(e);break;
case l.LongType:case l.DateType:n=8;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=new DataView(c);c=m.getInt32(e);e=m.getUint32(e+4);m=z.add(z.mul(String(c),z.LONG_UPPER_SHIFT),String(e));g.constructor===l.DateType&&(m=new Date(Number(m)));break;case l.BigIntType:n=2;q.assert(c.byteLength>=e+n,"Buffer is not long enough");d=new DataView(c);g=d.getUint16(e);q.assert(c.byteLength>=e+n+g,"Buffer is not long enough");m=g?String(d.getInt8(e+n)):"0";for(c=1;c<g;c++)c&&(m=z.mul(m,z.BYTE_SHIFT)),
m=z.add(m,String(d.getUint8(e+n+c)));n+=g;break;case l.UnsignedByteType:n=1;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=(new Uint8Array(c))[e];break;case l.UnsignedShortType:n=2;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=(new DataView(c)).getUint16(e);break;case l.UnsignedIntType:n=4;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=(new DataView(c)).getUint32(e);break;case l.UnsignedLongType:n=8;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=new DataView(c);
c=m.getUint32(e);e=m.getUint32(e+4);m=z.add(z.mul(String(c),z.LONG_UPPER_SHIFT),String(e));break;case l.BigUnsignedIntType:n=2;q.assert(c.byteLength>=e+n,"Buffer is not long enough");d=new DataView(c);g=d.getUint16(e);q.assert(c.byteLength>=e+n+g,"Buffer is not long enough");m="0";for(c=0;c<g;c++)c&&(m=z.mul(m,z.BYTE_SHIFT)),m=z.add(m,String(d.getUint8(e+n+c)));n+=g;break;case l.DayType:n=3;q.assert(c.byteLength>=e+n,"Buffer is not long enough");c=new DataView(c);e=(c.getInt16(e)<<8|c.getUint8(e+
2))*l.MILLIS_PER_DAY;m=new Date(e+(new Date(e)).getTimezoneOffset()*l.MILLIS_PER_MINUTE);break;case l.TimeType:n=4;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=new Date((new DataView(c)).getUint32(e));break;case l.FloatType:n=4;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=(new DataView(c)).getFloat32(e);break;case l.DoubleType:n=8;q.assert(c.byteLength>=e+n,"Buffer is not long enough");m=(new DataView(c)).getFloat64(e);break;case l.BooleanType:n=1;q.assert(c.byteLength>e,
"Buffer is not long enough");e=(new Uint8Array(c))[e];q.assert(0===e||255===e,"0x"+e.toString(16)+" is an invalid Boolean value");m=!!e;break;case l.BooleanArrayType:m=f(c,e);n=m.length;e=r({buffer:c,offset:e+n,count:m.value,baseValue:a});n+=e.length;m=e.value;break;case l.BooleanTupleType:n=r({buffer:c,offset:e,count:g.length,baseValue:a});m=n.value;n=n.length;break;case l.CharType:q.assert(c.byteLength>e,"Buffer is not long enough");m=w.toString((new Uint8Array(c)).subarray(e,e+4))[0];n=w.fromString(m).byteLength;
break;case l.StringType:m=new Uint8Array(c);for(n=0;q.assert(c.byteLength>e+n,"Buffer is not long enough"),m[e+n];n++);m=w.toString((new Uint8Array(c)).subarray(e,e+n));n++;break;case l.OctetsType:m=f(c,e);n=m.length;d=n+m.value;q.assert(c.byteLength>=e+d,"Buffer is not long enough");m=c.slice(e+n,e+d);n=d;break;case l.TupleType:n=0;m=a||b(g);for(a=0;a<g.length;a++){var u=h({buffer:c,pointerStart:d,offset:e+n,type:g.type});n+=u.length;m[a]=u.value}break;case l.StructType:n=0;m=a||b(g);g=k.makeIterator(g.fields);
for(a=g.next();!a.done;a=g.next())a=a.value,u=h({buffer:c,pointerStart:d,offset:e+n,type:a.type}),m[a.name]=u.value,n+=u.length;break;case l.ArrayType:m=f(c,e);n=m.length;m=a||b(g,m.value);for(a=0;a<m.length;a++)u=h({buffer:c,pointerStart:d,offset:e+n,type:g.type}),n+=u.length,m[a]=u.value;break;case l.SetType:u=f(c,e);n=u.length;m=a||b(g);for(a=0;a<u.value;a++){var t=h({buffer:c,pointerStart:d,offset:e+n,type:g.type});n+=t.length;m.add(t.value)}break;case l.MapType:u=f(c,e);n=u.length;m=a||b(g);
for(a=0;a<u.value;a++){t=h({buffer:c,pointerStart:d,offset:e+n,type:g.keyType});n+=t.length;var B=h({buffer:c,pointerStart:d,offset:e+n,type:g.valueType});n+=B.length;m.set(t.value,B.value)}break;case l.EnumType:n=1;q.assert(c.byteLength>e,"Buffer is not long enough");e=(new Uint8Array(c))[e];m=g.values[e];void 0===m&&q.fail("Index "+String(e)+" is invalid");break;case l.ChoiceType:n=1;q.assert(c.byteLength>e,"Buffer is not long enough");m=(new Uint8Array(c))[e];e=h({buffer:c,pointerStart:d,offset:e+
n,type:g.types[m]});n+=e.length;m=e.value;break;case l.RecursiveType:n=1;q.assert(c.byteLength>e,"Buffer is not long enough");m=(new Uint8Array(c))[e];q.assert(0===m||255===m,"0x"+m.toString(16)+" is an invalid Recursive byte");m?(g=g.type,m=b(g),H.has(c)||H.set(c,new Map),H.get(c).set(e+n,m),n+=h({buffer:c,pointerStart:d,offset:e+n,type:g,baseValue:m}).length):(d=f(c,e+n),e=e+n-d.value,m=H.get(c).get(e),q.assert(void 0!==m,"Cannot find target at "+String(e)),n+=d.length);break;case l.OptionalType:n=
1;q.assert(c.byteLength>e,"Buffer is not long enough");m=(new Uint8Array(c))[e];q.assert(0===m||255===m,"0x"+m.toString(16)+" is an invalid Optional byte");m?(e=h({buffer:c,pointerStart:d,offset:e+n,type:g.type}),n+=e.length,m=e.value):m=null;break;case l.PointerType:e=f(c,e);n=e.length;m=h({buffer:c,pointerStart:d,offset:d+e.value,type:g.type}).value;break;default:q.fail("Not a structure type: "+J.inspect(g))}return{value:m,length:n}}function t(b,a){q.assert(0<=a,"Offset is negative: "+String(a));
q.assert(b.byteLength>a,"Buffer is not long enough");for(var c,e=1,g=(new Uint8Array(b))[a],m=k.makeIterator(K),n=m.next();!n.done;n=m.next())if(n=n.value,g===n._value)return{value:new n,length:e};switch(g){case l.BooleanTupleType._value:b=f(b,a+e);c=new l.BooleanTupleType(b.value);e+=b.length;break;case l.TupleType._value:var r=t(b,a+e),e=e+r.length;b=f(b,a+e);e+=b.length;c=new l.TupleType({type:r.value,length:b.value});break;case l.StructType._value:q.assert(b.byteLength>a+e,"Buffer is not long enough");
r=new Uint8Array(b);c=r[a+e];e++;g={};for(m=0;m<c;m++){q.assert(b.byteLength>a+e,"Buffer is not long enough");var B=r[a+e];e++;q.assert(b.byteLength>=a+e+B,"Buffer is not long enough");n=w.toString(r.subarray(a+e,a+e+B));e+=B;B=t(b,a+e);g[n]=B.value;e+=B.length}c=new l.StructType(g);break;case l.ArrayType._value:b=t(b,a+e);e+=b.length;c=new l.ArrayType(b.value);break;case l.SetType._value:b=t(b,a+e);e+=b.length;c=new l.SetType(b.value);break;case l.MapType._value:r=t(b,a+e);e+=r.length;b=t(b,a+e);
e+=b.length;c=new l.MapType(r.value,b.value);break;case l.EnumType._value:r=t(b,a+e);e+=r.length;q.assert(b.byteLength>a+e,"Buffer is not long enough");c=(new Uint8Array(b))[a+e];e++;g=Array(c);for(m=0;m<c;m++)n=a+e,n=h({buffer:b,pointerStart:n,offset:n,type:r.value}),e+=n.length,g[m]=n.value;c=new l.EnumType({type:r.value,values:g});break;case l.ChoiceType._value:q.assert(b.byteLength>a+e,"Buffer is not long enough");r=(new Uint8Array(b))[a+e];e++;c=Array(r);for(g=0;g<r;g++)m=t(b,a+e),c[g]=m.value,
e+=m.length;c=new l.ChoiceType(c);break;case l.RecursiveType._value:q.assert(b.byteLength>=a+e+2,"Buffer is not long enough");c=(new DataView(b)).getUint16(a+e);e+=2;(g=E.get(b))?r=g.get(c):(g=new Map,E.set(b,g));if(!r){do for(r="read-type",m=0;16>m;m++)r+=Math.floor(16*Math.random()).toString(16);while(C.isRegistered(r));g.set(c,r);b=t(b,a+e);e+=b.length;C.registerType({type:b.value,name:r})}c=new l.RecursiveType(r);break;case l.OptionalType._value:b=t(b,a+e);e+=b.length;c=new l.OptionalType(b.value);
break;case l.PointerType._value:b=t(b,a+e);e+=b.length;c=new l.PointerType(b.value);break;case l.REPEATED_TYPE:r=e+2;q.assert(b.byteLength>=a+r,"Buffer is not long enough");c=(new DataView(b)).getUint16(a+e);c=t(b,a+e-c).value;e=r;break;default:q.fail("No such type: 0x"+d((new Uint8Array(b))[a].toString(16),2))}return{value:c,length:e}}"/"===c&&(c="");var q=a(c+"/lib/assert.js"),B=a(c+"/lib/bit-math.js"),w=a(c+"/lib/buffer-string.js"),C=a(c+"/recursive-registry.js"),z=a(c+"/lib/strint.js"),l=a(c+
"/structure-types.js"),J=a("/lib/util-inspect.js"),K=[l.ByteType,l.ShortType,l.IntType,l.LongType,l.BigIntType,l.UnsignedByteType,l.UnsignedShortType,l.UnsignedIntType,l.UnsignedLongType,l.BigUnsignedIntType,l.DateType,l.DayType,l.TimeType,l.FloatType,l.DoubleType,l.BooleanType,l.BooleanArrayType,l.CharType,l.StringType,l.OctetsType],H=new WeakMap,E=new WeakMap;g.exports={_consumeType:t,type:function(b,a){a=void 0===a?!0:a;q.instanceOf(b,ArrayBuffer);var c=t(b,0),d=c.value,c=c.length;a&&q.assert(c===
b.byteLength,"Did not consume all of the buffer");return d},value:function(b){var a=b.buffer,c=b.type;b=void 0===b.offset?0:b.offset;q.instanceOf(a,ArrayBuffer);q.instanceOf(c,l.Type);q.instanceOf(b,Number);return h({buffer:a,offset:b,type:c,pointerStart:b}).value}}}).call(this,"/")},{"/lib/util-inspect.js":"/lib/util-inspect.js"}],"/recursive-registry.js":[function(a,g){(function(c){"/"===c&&(c="");var f=a(c+"/lib/assert.js"),d=a(c+"/structure-types.js"),b=new Map;g.exports={registerType:function(a){var c=
a.type;a=a.name;f.instanceOf(c,[d.ArrayType,d.MapType,d.SetType,d.StructType,d.TupleType]);f.instanceOf(a,String);f.assert(!b.has(a),'"'+a+'" is already a registered type');b.set(a,c)},getType:function(a){f.instanceOf(a,String);var c=b.get(a);f.assert(void 0!==c,'"'+a+'" is not a registered type');return c},isRegistered:function(a){return b.has(a)}}}).call(this,"/")},{}],"/structure-types.js":[function(a,g){(function(c){function f(b){p.instanceOf(b,v);this.type=b}function d(b){v.call(this);p.instanceOf(b,
D);this.type=b}function b(b){v.call(this);p.instanceOf(b,String);this.name=b}function r(b){v.call(this);p.instanceOf(b,Array);try{p.byteUnsignedInteger(b.length)}catch(qa){p.fail(String(b.length)+" types is too many")}for(var a=k.makeIterator(b),c=a.next();!c.done;c=a.next())p.instanceOf(c.value,D);this.types=b}function h(b){var a=b.type;b=b.values;p.instanceOf(a,v);p.instanceOf(b,Array);try{p.byteUnsignedInteger(b.length)}catch(da){p.fail(String(b.length)+" values is too many")}for(var c=new Map,
d=0;d<b.length;d++){var T=b[d],e=U.toBinaryString(a.valueBuffer(T));p.assert(!c.has(e),"Value is repeated: "+ea.inspect(T));c.set(e,d)}this.type=a;this.values=b;this.valueIndices=c}function t(b,a){v.call(this);p.instanceOf(b,D);p.instanceOf(a,D);this.keyType=b;this.valueType=a}function q(b){B.apply(this,arguments)}function B(b){v.call(this);p.instanceOf(b,D);this.type=b}function w(b){v.call(this);p.instanceOf(b,Object);var a=0,c;for(c in b)({}).hasOwnProperty.call(b,c)&&a++;try{p.byteUnsignedInteger(a)}catch(da){p.fail(String(a)+
" fields is too many")}this.fields=Array(a);var a=0,d;for(d in b)if({}.hasOwnProperty.call(b,d)){c=U.fromString(d);try{p.byteUnsignedInteger(c.byteLength)}catch(da){p.fail("Field name "+d+" is too long")}var T=b[d];try{p.instanceOf(T,D)}catch(da){p.fail(String(T)+" is not a valid field type")}var e={};this.fields[a]=(e.name=d,e.type=T,e.buffer=c,e);a++}this.fields.sort(function(b,a){if(b.name<a.name)return-1;if(b.name>a.name)return 1})}function C(b){var a=b.type;b=b.length;v.call(this);p.instanceOf(a,
D);p.fourByteUnsignedInteger(b);this.type=a;this.length=b}function z(b){v.apply(this,arguments)}function l(b){v.apply(this,arguments)}function J(b){v.apply(this,arguments)}function K(b){v.apply(this,arguments)}function H(b){v.call(this);p.fourByteUnsignedInteger(b);this.length=b}function E(b){v.apply(this,arguments)}function u(b){O.apply(this,arguments)}function x(b){O.apply(this,arguments)}function O(b){v.apply(this,arguments)}function e(b){n.apply(this,arguments)}function I(b){n.apply(this,arguments)}
function m(b){n.apply(this,arguments)}function n(b){v.apply(this,arguments)}function F(b){N.apply(this,arguments)}function M(b){N.apply(this,arguments)}function G(b){N.apply(this,arguments)}function Q(b){N.apply(this,arguments)}function X(b){N.apply(this,arguments)}function N(b){v.apply(this,arguments)}function S(b){P.apply(this,arguments)}function Y(b){P.apply(this,arguments)}function Z(b){P.apply(this,arguments)}function aa(b){P.apply(this,arguments)}function ba(b){P.apply(this,arguments)}function P(b){v.apply(this,
arguments)}function v(b){D.apply(this,arguments)}function D(){}function W(b){var a=new ArrayBuffer(4);(new DataView(a)).setUint32(0,b);return a}function R(b,a){if(a&&(a=fa.get(b))){a=k.makeIterator(a);for(var c=a.next();!c.done;c=a.next()){var d=k.makeIterator(c.value),c=d.next().value,d=d.next().value,L=b.length;b.addAll(U.fromBinaryString(c));c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,L);d=k.makeIterator(d);for(L=d.next();!L.done;L=d.next())b.setAll(L.value,c)}}}function V(b){if(b&&b.constructor===
String&&(b=Number(b),!isNaN(b)))return b}function ka(b,a){p.instanceOf(b,y);p.instanceOf(a,String);(A.gt(a,"9223372036854775807")||A.lt(a,"-9223372036854775808"))&&p.fail("Value out of range");var c=A.div(a,A.LONG_UPPER_SHIFT,!0);a=A.sub(a,A.mul(c,A.LONG_UPPER_SHIFT));var d=new ArrayBuffer(8),L=new DataView(d);L.setInt32(0,Number(c));L.setUint32(4,Number(a));b.addAll(d)}function la(b,a){p.instanceOf(a,Array);for(var c=ga(a.length),d=ha(a.length),c=new ArrayBuffer(c?d+1:d),d=new Uint8Array(c),L=0;L<
a.length;L++){var e=a[L];p.instanceOf(e,Boolean);var T=ga(~ga(L));e?d[ha(L)]|=1<<T:d[ha(L)]&=~(1<<T)}b.addAll(c)}"/"===c&&(c="");var p=a(c+"/lib/assert.js"),ra=a("base64-js"),U=a(c+"/lib/buffer-string.js"),sa=a(c+"/config.js"),ta=a("sha256"),y=a(c+"/lib/growable-buffer.js"),ia,A=a(c+"/lib/strint.js"),ea=a("/lib/util-inspect.js"),ma=a(c+"/lib/bit-math.js"),ha=ma.dividedByEight,ga=ma.modEight,na=new WeakMap,ca=new WeakMap,oa=new WeakMap,fa=new WeakMap;D.prototype.addToBuffer=function(b){p.instanceOf(b,
y);if(this.cachedTypeLocations){if(!ca.get(b)){var a=this.cachedTypeLocations.get(b);if(void 0!==a){b.add(255);var c=new ArrayBuffer(2);try{return(new DataView(c)).setUint16(0,b.length-a),b.addAll(c),!1}catch(qa){}}}}else this.cachedTypeLocations=new Map;this.cachedTypeLocations.set(b,b.length);b.add(this.constructor._value);return!0};D.prototype.toBuffer=function(){this.cachedBuffer||(this.cachedBuffer=this._toBuffer());return this.cachedBuffer};D.prototype._toBuffer=function(){var b=new y;this.addToBuffer(b);
return b.toBuffer()};D.prototype.getHash=function(){this.cachedHash||(this.cachedHash=this._getHash());return this.cachedHash};D.prototype._getHash=function(){return ra.fromByteArray(ta(this.toBuffer(),{asBytes:!0}))};D.prototype.getSignature=function(){this.cachedSignature||(this.cachedSignature=this._getSignature());return this.cachedSignature};D.prototype._getSignature=function(){return sa.VERSION_STRING+this.getHash()};D.prototype.writeValue=function(){p.fail("Generic Type has no value representation")};
D.prototype.valueBuffer=function(b){var a=new y;this.writeValue(a,b);return a.toBuffer()};D.prototype.equals=function(b){try{p.instanceOf(b,this.constructor)}catch(ja){return!1}try{p.equal(b.constructor,this.constructor)}catch(ja){return!1}for(var a in this)if({}.hasOwnProperty.call(this,a)&&!a.startsWith("cached"))try{p.equal(b[a],this[a])}catch(ja){return!1}return!0};k.global.Object.defineProperties(D,{_value:{configurable:!0,enumerable:!0,get:function(){p.fail("Generic Type has no value byte")}}});
k.inherits(v,D);k.inherits(P,v);k.inherits(ba,P);ba.prototype.writeValue=function(b,a){p.instanceOf(b,y);var c=V(a);void 0!==c&&(a=c);p.integer(a);p.between(-128,a,128,"Value out of range");c=new ArrayBuffer(1);(new DataView(c)).setInt8(0,a);b.addAll(c)};k.global.Object.defineProperties(ba,{_value:{configurable:!0,enumerable:!0,get:function(){return 1}}});k.inherits(aa,P);aa.prototype.writeValue=function(b,a){p.instanceOf(b,y);var c=V(a);void 0!==c&&(a=c);p.integer(a);p.between(-32768,a,32768,"Value out of range");
c=new ArrayBuffer(2);(new DataView(c)).setInt16(0,a);b.addAll(c)};k.global.Object.defineProperties(aa,{_value:{configurable:!0,enumerable:!0,get:function(){return 2}}});k.inherits(Z,P);Z.prototype.writeValue=function(b,a){p.instanceOf(b,y);var c=V(a);void 0!==c&&(a=c);p.integer(a);p.between(-2147483648,a,2147483648,"Value out of range");c=new ArrayBuffer(4);(new DataView(c)).setInt32(0,a);b.addAll(c)};k.global.Object.defineProperties(Z,{_value:{configurable:!0,enumerable:!0,get:function(){return 3}}});
k.inherits(Y,P);Y.prototype.writeValue=function(b,a){ka(b,a)};k.global.Object.defineProperties(Y,{_value:{configurable:!0,enumerable:!0,get:function(){return 4}}});k.inherits(S,P);S.prototype.writeValue=function(b,a){p.instanceOf(b,y);p.instanceOf(a,String);a=A.normalize(a);var c=[];if(!A.eq(a,"0")){for(;A.gt(a,"127")||A.lt(a,"-128");){var d=A.div(a,A.BYTE_SHIFT,!0);a=A.sub(a,A.mul(d,A.BYTE_SHIFT));c.push(Number(a));a=d}c.push(Number(a));p.twoByteUnsignedInteger(c.length)}d=new ArrayBuffer(2+c.length);
a=new DataView(d);a.setUint16(0,c.length);for(var e=3,f=c.length-2;-1<f;f--,e++)a.setUint8(e,c[f]);c.length&&a.setInt8(2,c[c.length-1]);b.addAll(d)};k.global.Object.defineProperties(S,{_value:{configurable:!0,enumerable:!0,get:function(){return 5}}});k.inherits(N,v);k.inherits(X,N);X.prototype.writeValue=function(b,a){p.instanceOf(b,y);var c=V(a);void 0!==c&&(a=c);p.integer(a);p.between(0,a,256,"Value out of range");c=new ArrayBuffer(1);(new Uint8Array(c))[0]=a;b.addAll(c)};k.global.Object.defineProperties(X,
{_value:{configurable:!0,enumerable:!0,get:function(){return 17}}});k.inherits(Q,N);Q.prototype.writeValue=function(b,a){p.instanceOf(b,y);var c=V(a);void 0!==c&&(a=c);p.integer(a);p.between(0,a,65536,"Value out of range");c=new ArrayBuffer(2);(new DataView(c)).setUint16(0,a);b.addAll(c)};k.global.Object.defineProperties(Q,{_value:{configurable:!0,enumerable:!0,get:function(){return 18}}});k.inherits(G,N);G.prototype.writeValue=function(b,a){p.instanceOf(b,y);var c=V(a);void 0!==c&&(a=c);p.integer(a);
p.between(0,a,4294967296,"Value out of range");c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,a);b.addAll(c)};k.global.Object.defineProperties(G,{_value:{configurable:!0,enumerable:!0,get:function(){return 19}}});k.inherits(M,N);M.prototype.writeValue=function(b,a){p.instanceOf(b,y);p.instanceOf(a,String);(A.gt(a,"18446744073709551615")||A.lt(a,"0"))&&p.fail("Value out of range");var c=A.div(a,A.LONG_UPPER_SHIFT);a=A.sub(a,A.mul(c,A.LONG_UPPER_SHIFT));var d=new ArrayBuffer(8),e=new DataView(d);
e.setUint32(0,Number(c));e.setUint32(4,Number(a));b.addAll(d)};k.global.Object.defineProperties(M,{_value:{configurable:!0,enumerable:!0,get:function(){return 20}}});k.inherits(F,N);F.prototype.writeValue=function(b,a){p.instanceOf(b,y);p.instanceOf(a,String);A.isNegative(a)&&p.fail("Value out of range");var c=[];if(!A.eq(a,"0")){for(;A.ge(a,A.BYTE_SHIFT);){var d=k.makeIterator(A.quotientRemainderPositive(a,A.BYTE_SHIFT));a=d.next().value;d=d.next().value;c.push(Number(d))}c.push(Number(a));p.twoByteUnsignedInteger(c.length)}a=
new ArrayBuffer(2+c.length);d=new DataView(a);d.setUint16(0,c.length);for(var e=2,f=c.length-1;-1<f;f--,e++)d.setUint8(e,c[f]);b.addAll(a)};k.global.Object.defineProperties(F,{_value:{configurable:!0,enumerable:!0,get:function(){return 21}}});k.inherits(n,v);k.inherits(m,n);m.prototype.writeValue=function(b,a){p.instanceOf(a,Date);ka(b,String(a.getTime()))};k.global.Object.defineProperties(m,{_value:{configurable:!0,enumerable:!0,get:function(){return 26}}});k.inherits(I,n);I.prototype.writeValue=
function(b,a){p.instanceOf(a,Date);a=new Date(a.getFullYear(),a.getMonth(),a.getDate());a=(a.getTime()-6E4*a.getTimezoneOffset())/864E5;var c=new ArrayBuffer(3),d=new DataView(c);d.setInt16(0,a>>8);d.setUint8(2,a&255);b.addAll(c)};k.global.Object.defineProperties(I,{_value:{configurable:!0,enumerable:!0,get:function(){return 27}}});k.inherits(e,n);e.prototype.writeValue=function(b,a){p.instanceOf(a,Date);var c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,a.getTime()%864E5);b.addAll(c)};k.global.Object.defineProperties(e,
{_value:{configurable:!0,enumerable:!0,get:function(){return 28}}});k.inherits(O,v);k.inherits(x,O);x.prototype.writeValue=function(b,a){p.instanceOf(b,y);var c=V(a);void 0!==c&&(a=c);p.instanceOf(a,Number);c=new ArrayBuffer(4);(new DataView(c)).setFloat32(0,a);b.addAll(c)};k.global.Object.defineProperties(x,{_value:{configurable:!0,enumerable:!0,get:function(){return 32}}});k.inherits(u,O);u.prototype.writeValue=function(b,a){p.instanceOf(b,y);var c=V(a);void 0!==c&&(a=c);p.instanceOf(a,Number);
c=new ArrayBuffer(8);(new DataView(c)).setFloat64(0,a);b.addAll(c)};k.global.Object.defineProperties(u,{_value:{configurable:!0,enumerable:!0,get:function(){return 33}}});k.inherits(E,v);E.prototype.writeValue=function(b,a){p.instanceOf(b,y);p.instanceOf(a,Boolean);a?b.add(255):b.add(0)};k.global.Object.defineProperties(E,{_value:{configurable:!0,enumerable:!0,get:function(){return 48}}});k.inherits(H,v);H.prototype.addToBuffer=function(b){v.prototype.addToBuffer.call(this,b)&&b.addAll(W(this.length))};
H.prototype.writeValue=function(b,a){p.instanceOf(b,y);p.instanceOf(a,Array);a.length!==this.length&&p.fail("Length does not match");la(b,a)};k.global.Object.defineProperties(H,{_value:{configurable:!0,enumerable:!0,get:function(){return 49}}});k.inherits(K,v);K.prototype.writeValue=function(b,a){p.instanceOf(a,Array);p.fourByteUnsignedInteger(a.length);b.addAll(W(a.length));la(b,a)};k.global.Object.defineProperties(K,{_value:{configurable:!0,enumerable:!0,get:function(){return 50}}});k.inherits(J,
v);J.prototype.writeValue=function(b,a){p.instanceOf(b,y);p.instanceOf(a,String);p.assert(1===a.length,"String must contain only 1 character");b.addAll(U.fromString(a))};k.global.Object.defineProperties(J,{_value:{configurable:!0,enumerable:!0,get:function(){return 64}}});k.inherits(l,v);l.prototype.writeValue=function(b,a){p.instanceOf(b,y);p.instanceOf(a,String);a=U.fromString(a);b.addAll(a);b.add(0)};k.global.Object.defineProperties(l,{_value:{configurable:!0,enumerable:!0,get:function(){return 65}}});
k.inherits(z,v);z.prototype.writeValue=function(b,a){p.instanceOf(b,y);p.instanceOf(a,ArrayBuffer);p.fourByteUnsignedInteger(a.byteLength);b.addAll(W(a.byteLength));b.addAll(a)};k.global.Object.defineProperties(z,{_value:{configurable:!0,enumerable:!0,get:function(){return 66}}});k.inherits(C,v);C.prototype.addToBuffer=function(b){v.prototype.addToBuffer.call(this,b)&&(this.type.addToBuffer(b),b.addAll(W(this.length)))};C.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(b,y);p.instanceOf(a,
Array);a.length!==this.length&&p.fail("Length does not match: expected "+String(this.length)+" but got "+a.length);a=k.makeIterator(a);for(var d=a.next();!d.done;d=a.next())this.type.writeValue(b,d.value,!1);R(b,c)};k.global.Object.defineProperties(C,{_value:{configurable:!0,enumerable:!0,get:function(){return 80}}});k.inherits(w,v);w.prototype.addToBuffer=function(b){if(v.prototype.addToBuffer.call(this,b)){b.add(this.fields.length);for(var a=k.makeIterator(this.fields),c=a.next();!c.done;c=a.next()){var c=
c.value,d=c.buffer;b.add(d.byteLength);b.addAll(d);c.type.addToBuffer(b)}}};w.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(b,y);p.instanceOf(a,Object);for(var d=k.makeIterator(this.fields),e=d.next();!e.done;e=d.next()){var e=e.value,f=a[e.name];void 0===f&&p.fail("Value for field "+e.name+" missing");e.type.writeValue(b,f,!1)}R(b,c)};k.global.Object.defineProperties(w,{_value:{configurable:!0,enumerable:!0,get:function(){return 81}}});k.inherits(B,v);B.prototype.addToBuffer=
function(b){v.prototype.addToBuffer.call(this,b)&&this.type.addToBuffer(b)};B.prototype._writeValue=function(b,a,c){p.instanceOf(b,y);var d=a.length;void 0===d&&(d=a.size);p.fourByteUnsignedInteger(d);b.addAll(W(d));a=k.makeIterator(a);for(d=a.next();!d.done;d=a.next())this.type.writeValue(b,d.value,!1);R(b,c)};B.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(a,Array);this._writeValue(b,a,c)};k.global.Object.defineProperties(B,{_value:{configurable:!0,enumerable:!0,get:function(){return 82}}});
k.inherits(q,B);q.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(a,Set);this._writeValue(b,a,c)};k.global.Object.defineProperties(q,{_value:{configurable:!0,enumerable:!0,get:function(){return 83}}});k.inherits(t,v);t.prototype.addToBuffer=function(b){v.prototype.addToBuffer.call(this,b)&&(this.keyType.addToBuffer(b),this.valueType.addToBuffer(b))};t.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(b,y);p.instanceOf(a,Map);p.fourByteUnsignedInteger(a.size);
b.addAll(W(a.size));a=k.makeIterator(a);for(var d=a.next();!d.done;d=a.next()){var e=k.makeIterator(d.value),d=e.next().value,e=e.next().value;this.keyType.writeValue(b,d,!1);this.valueType.writeValue(b,e,!1)}R(b,c)};k.global.Object.defineProperties(t,{_value:{configurable:!0,enumerable:!0,get:function(){return 84}}});k.inherits(h,D);h.prototype.addToBuffer=function(b){if(D.prototype.addToBuffer.call(this,b)){this.type.addToBuffer(b);b.add(this.valueIndices.size);for(var a=k.makeIterator(this.valueIndices),
c=a.next();!c.done;c=a.next()){var c=k.makeIterator(c.value),d=c.next().value;c.next();b.addAll(U.fromBinaryString(d))}}};h.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(b,y);var d=new y;this.type.writeValue(d,a,!1);d=this.valueIndices.get(U.toBinaryString(d.toBuffer()));p.assert(void 0!==d,"Not a valid enum value: "+ea.inspect(a));b.add(d);R(b,c)};k.global.Object.defineProperties(h,{_value:{configurable:!0,enumerable:!0,get:function(){return 85}}});k.inherits(r,v);r.prototype.addToBuffer=
function(b){if(v.prototype.addToBuffer.call(this,b)){b.add(this.types.length);for(var a=k.makeIterator(this.types),c=a.next();!c.done;c=a.next())c.value.addToBuffer(b)}};r.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(b,y);for(var d=!1,e=0;e<this.types.length;e++){var f=this.types[e],h=new y;try{f.writeValue(h,a,!1)}catch(ua){continue}b.add(e);b.addAll(h.toBuffer());d=!0;break}d||p.fail("No types matched: "+ea.inspect(a));R(b,c)};k.global.Object.defineProperties(r,{_value:{configurable:!0,
enumerable:!0,get:function(){return 86}}});k.inherits(b,v);b.prototype.addToBuffer=function(b){if(v.prototype.addToBuffer.call(this,b)){var a=na.get(b);a||(a=new Map,na.set(b,a));var c=a.get(this.name),d=void 0===c;d&&(c=a.size,p.twoByteUnsignedInteger(c),a.set(this.name,c));a=new ArrayBuffer(2);(new DataView(a)).setUint16(0,c);b.addAll(a);d&&(c=ca.get(b)||0,ca.set(b,c+1),this.type.addToBuffer(b),ca.set(b,c))}};b.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(b,y);var d=!0,e=
oa.get(b);if(e){var f=e.get(a);if(void 0!==f){d=!1;b.add(0);f=b.length-f;p.fourByteUnsignedInteger(f);var h=new ArrayBuffer(4);(new DataView(h)).setUint32(0,f);b.addAll(h)}}else e=new Map,oa.set(b,e);d&&(b.add(255),e.set(a,b.length),this.type.writeValue(b,a,!1));R(b,c)};k.global.Object.defineProperties(b.prototype,{type:{configurable:!0,enumerable:!0,get:function(){ia||(ia=a(c+"/recursive-registry.js"));return ia.getType(this.name)}}});k.global.Object.defineProperties(b,{_value:{configurable:!0,enumerable:!0,
get:function(){return 87}}});k.inherits(d,v);d.prototype.addToBuffer=function(b){v.prototype.addToBuffer.call(this,b)&&this.type.addToBuffer(b)};d.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(b,y);null===a?b.add(0):(b.add(255),this.type.writeValue(b,a,!1));R(b,c)};k.global.Object.defineProperties(d,{_value:{configurable:!0,enumerable:!0,get:function(){return 96}}});k.inherits(f,D);f.prototype.addToBuffer=function(b){D.prototype.addToBuffer.call(this,b)&&this.type.addToBuffer(b)};
f.prototype.writeValue=function(b,a,c){c=void 0===c?!0:c;p.instanceOf(b,y);var d=fa.get(b);d||(d=new Map,fa.set(b,d));var e=new y;this.type.writeValue(e,a,!1);a=U.toBinaryString(e.toBuffer());var e=b.length,f=d.get(a);f?f.add(e):d.set(a,new Set([e]));b.addAll(new ArrayBuffer(4));R(b,c)};k.global.Object.defineProperties(f,{_value:{configurable:!0,enumerable:!0,get:function(){return 112}}});g.exports={Type:D,ByteType:ba,ShortType:aa,IntType:Z,LongType:Y,BigIntType:S,UnsignedByteType:X,UnsignedShortType:Q,
UnsignedIntType:G,UnsignedLongType:M,BigUnsignedIntType:F,DateType:m,DayType:I,TimeType:e,FloatType:x,DoubleType:u,BooleanType:E,BooleanTupleType:H,BooleanArrayType:K,CharType:J,StringType:l,OctetsType:z,TupleType:C,StructType:w,ArrayType:B,SetType:q,MapType:t,EnumType:h,ChoiceType:r,RecursiveType:b,OptionalType:d,PointerType:f,REPEATED_TYPE:255,MILLIS_PER_DAY:864E5,MILLIS_PER_MINUTE:6E4}}).call(this,"/")},{"/lib/util-inspect.js":"/lib/util-inspect.js","base64-js":2,sha256:5}],1:[function(a){(function(){function g(){var a=
{},c;for(c in b)a[c]={sig:b[c].sig,type:f.fromByteArray(new Uint8Array(b[c].type.toBuffer()))};localStorage.typeCache=JSON.stringify(a)}a("/client-side/common.js");var c=a("/lib/assert.js"),f=a("base64-js"),d=a("/read.js"),b={};if(localStorage.typeCache){var r=JSON.parse(localStorage.typeCache),h;for(h in r)b[h]={sig:r[h].sig,type:d.type((new Uint8Array(f.toByteArray(r[h].type))).buffer)}}else g();sb.download=function(a,f){function h(b,a,c){if(r){r instanceof Array||(r=[r]);for(var d=k.makeIterator(r),
f=d.next();!f.done;f=d.next())f=f.value,f(b,a,c)}}c.instanceOf(a,String);c.instanceOf(f,Object);f.dataType="arraybuffer";var q;b[a]?(q=!0,f.headers||(f.headers={}),f.headers.sig=b[a].sig):q=!1;var r=f.success;f.success=function(c,f,r){var l=r.getResponseHeader("sig");if(q&&b[a].sig===l)l=d.value({buffer:c,type:b[a].type}),h(l,f,r);else{var t=d._consumeType(c,0);c=d.value({buffer:c,offset:t.length,type:t.value});b[a]={sig:l,type:t.value};g();h(c,f,r)}};$.ajax(f)}})()},{"/client-side/common.js":"/client-side/common.js",
"/lib/assert.js":"/lib/assert.js","/read.js":"/read.js","base64-js":2}],2:[function(a,g,c){function f(b){var a=b.length;if(0<a%4)throw Error("Invalid string. Length must be a multiple of 4");return"\x3d"===b[a-2]?2:"\x3d"===b[a-1]?1:0}function d(a,c,d){for(var f=[],h=c;h<d;h+=3)c=(a[h]<<16)+(a[h+1]<<8)+a[h+2],f.push(b[c>>18&63]+b[c>>12&63]+b[c>>6&63]+b[c&63]);return f.join("")}c.byteLength=function(b){return 3*b.length/4-f(b)};c.toByteArray=function(b){var a,c,d,g,t;a=b.length;g=f(b);t=new h(3*a/
4-g);c=0<g?a-4:a;var l=0;for(a=0;a<c;a+=4)d=r[b.charCodeAt(a)]<<18|r[b.charCodeAt(a+1)]<<12|r[b.charCodeAt(a+2)]<<6|r[b.charCodeAt(a+3)],t[l++]=d>>16&255,t[l++]=d>>8&255,t[l++]=d&255;2===g?(d=r[b.charCodeAt(a)]<<2|r[b.charCodeAt(a+1)]>>4,t[l++]=d&255):1===g&&(d=r[b.charCodeAt(a)]<<10|r[b.charCodeAt(a+1)]<<4|r[b.charCodeAt(a+2)]>>2,t[l++]=d>>8&255,t[l++]=d&255);return t};c.fromByteArray=function(a){for(var c=a.length,f=c%3,h="",g=[],r=0,l=c-f;r<l;r+=16383)g.push(d(a,r,r+16383>l?l:r+16383));1===f?(a=
a[c-1],h+=b[a>>2],h+=b[a<<4&63],h+="\x3d\x3d"):2===f&&(a=(a[c-2]<<8)+a[c-1],h+=b[a>>10],h+=b[a>>4&63],h+=b[a<<2&63],h+="\x3d");g.push(h);return g.join("")};var b=[],r=[],h="undefined"!==typeof Uint8Array?Uint8Array:Array;for(a=0;64>a;++a)b[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[a],r["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(a)]=a;r[45]=62;r[95]=63},{}],3:[function(a,g){!function(a){function c(b){return b.map(function(b){b=b.toString(16);
b=2<b.length?b:Array(2-b.length+1).join("0")+b;return b}).join("")}var d={bytesToHex:function(b){return c(b)},hexToBytes:function(b){if(1===b.length%2)throw Error("hexToBytes can't have a string with an odd number of characters.");0===b.indexOf("0x")&&(b=b.slice(2));return b.match(/../g).map(function(b){return parseInt(b,16)})}};"undefined"!==typeof g&&g.exports?g.exports=d:a.convertHex=d}(this)},{}],4:[function(a,g){!function(a){var c={bytesToString:function(a){return a.map(function(b){return String.fromCharCode(b)}).join("")},
stringToBytes:function(a){return a.split("").map(function(b){return b.charCodeAt(0)})},UTF8:{bytesToString:function(a){return decodeURIComponent(escape(c.bytesToString(a)))},stringToBytes:function(a){return c.stringToBytes(unescape(encodeURIComponent(a)))}}};"undefined"!==typeof g&&g.exports?g.exports=c:a.convertString=c}(this)},{}],5:[function(a,g){!function(c){function f(a,c){a.constructor===String&&(a=d.convertString.UTF8.stringToBytes(a));for(var f=[1779033703,3144134277,1013904242,2773480762,
1359893119,2600822924,528734635,1541459225],g=a,h=[],t=0,z=0;t<g.length;t++,z+=8)h[z>>>5]|=g[t]<<24-z%32;a=8*a.length;h[a>>5]|=128<<24-a%32;h[(a+64>>9<<4)+15]=a;for(a=0;a<h.length;a+=16){for(var g=f,t=h,z=a,l=g[0],J=g[1],K=g[2],H=g[3],E=g[4],u=g[5],x=g[6],O=g[7],e=0;64>e;e++){if(16>e)r[e]=t[z+e]|0;else{var I=r[e-15],m=r[e-2];r[e]=((I<<25|I>>>7)^(I<<14|I>>>18)^I>>>3)+r[e-7]+((m<<15|m>>>17)^(m<<13|m>>>19)^m>>>10)+r[e-16]}I=O+((E<<26|E>>>6)^(E<<21|E>>>11)^(E<<7|E>>>25))+(E&u^~E&x)+b[e]+r[e];m=((l<<30|
l>>>2)^(l<<19|l>>>13)^(l<<10|l>>>22))+(l&J^l&K^J&K);O=x;x=u;u=E;E=H+I|0;H=K;K=J;J=l;l=I+m|0}g[0]=g[0]+l|0;g[1]=g[1]+J|0;g[2]=g[2]+K|0;g[3]=g[3]+H|0;g[4]=g[4]+E|0;g[5]=g[5]+u|0;g[6]=g[6]+x|0;g[7]=g[7]+O|0}h=[];for(a=0;a<32*f.length;a+=8)h.push(f[a>>>5]>>>24-a%32&255);return c&&c.asBytes?h:c&&c.asString?d.convertString.bytesToString(h):d.bytesToHex(h)}var d={};"undefined"!==typeof g&&g.exports?(d.bytesToHex=a("convert-hex").bytesToHex,d.convertString=a("convert-string"),g.exports=f):(d.bytesToHex=c.convertHex.bytesToHex,
d.convertString=c.convertString,c.sha256=f);var b=[];!function(){function a(a){for(var b=Math.sqrt(a),c=2;c<=b;c++)if(!(a%c))return!1;return!0}function c(a){return 4294967296*(a-(a|0))|0}for(var d=2,f=0;64>f;)a(d)&&(b[f]=c(Math.pow(d,1/3)),f++),d++}();var r=[];f.x2=function(a,b){return f(f(a,{asBytes:!0}),b)}}(this)},{"convert-hex":3,"convert-string":4}]},{},[1]);}()