!function(){var g={scope:{}};g.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[d]=a.value)};g.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};g.global=g.getGlobal(this);g.SYMBOL_PREFIX="jscomp_symbol_";
g.initSymbol=function(){g.initSymbol=function(){};g.global.Symbol||(g.global.Symbol=g.Symbol)};g.symbolCounter_=0;g.Symbol=function(b){return g.SYMBOL_PREFIX+(b||"")+g.symbolCounter_++};g.initSymbolIterator=function(){g.initSymbol();var b=g.global.Symbol.iterator;b||(b=g.global.Symbol.iterator=g.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&g.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return g.arrayIterator(this)}});g.initSymbolIterator=function(){}};
g.arrayIterator=function(b){var d=0;return g.iteratorPrototype(function(){return d<b.length?{done:!1,value:b[d++]}:{done:!0}})};g.iteratorPrototype=function(b){g.initSymbolIterator();b={next:b};b[g.global.Symbol.iterator]=function(){return this};return b};g.makeIterator=function(b){g.initSymbolIterator();g.initSymbol();g.initSymbolIterator();var d=b[Symbol.iterator];return d?d.call(b):g.arrayIterator(b)};g.arrayFromIterator=function(b){for(var d,a=[];!(d=b.next()).done;)a.push(d.value);return a};
g.arrayFromIterable=function(b){return b instanceof Array?b:g.arrayFromIterator(g.makeIterator(b))};g.inherits=function(b,d){function a(){}a.prototype=d.prototype;b.prototype=new a;b.prototype.constructor=b;for(var h in d)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(d,h);e&&Object.defineProperty(b,h,e)}else b[h]=d[h]};g.owns=function(b,d){return Object.prototype.hasOwnProperty.call(b,d)};
g.polyfill=function(b,d){if(d){var a=g.global;b=b.split(".");for(var h=0;h<b.length-1;h++){var e=b[h];e in a||(a[e]={});a=a[e]}b=b[b.length-1];h=a[b];d=d(h);d!=h&&null!=d&&g.defineProperty(a,b,{configurable:!0,writable:!0,value:d})}};
g.polyfill("WeakMap",function(b){function d(a){this.id_=(c+=Math.random()+1).toString();if(a){g.initSymbol();g.initSymbolIterator();a=g.makeIterator(a);for(var r;!(r=a.next()).done;)r=r.value,this.set(r[0],r[1])}}function a(c){g.owns(c,e)||g.defineProperty(c,e,{value:{}})}function h(c){var r=Object[c];r&&(Object[c]=function(c){a(c);return r(c)})}if(function(){if(!b||!Object.seal)return!1;try{var c=Object.seal({}),a=Object.seal({}),e=new b([[c,2],[a,3]]);if(2!=e.get(c)||3!=e.get(a))return!1;e.delete(c);
e.set(a,4);return!e.has(c)&&4==e.get(a)}catch(l){return!1}}())return b;var e="$jscomp_hidden_"+Math.random().toString().substring(2);h("freeze");h("preventExtensions");h("seal");var c=0;d.prototype.set=function(c,r){a(c);if(!g.owns(c,e))throw Error("WeakMap key fail: "+c);c[e][this.id_]=r;return this};d.prototype.get=function(c){return g.owns(c,e)?c[e][this.id_]:void 0};d.prototype.has=function(c){return g.owns(c,e)&&g.owns(c[e],this.id_)};d.prototype.delete=function(c){return g.owns(c,e)&&g.owns(c[e],
this.id_)?delete c[e][this.id_]:!1};return d},"es6-impl","es3");g.ASSUME_NO_NATIVE_MAP=!1;
g.polyfill("Map",function(b){function d(){var c={};return c.previous=c.next=c.head=c}function a(c,a){var e=c.head_;return g.iteratorPrototype(function(){if(e){for(;e.head!=c.head_;)e=e.previous;for(;e.next!=e.head;)return e=e.next,{done:!1,value:a(e)};e=null}return{done:!0,value:void 0}})}function h(a,e){var r;r=e&&typeof e;"object"==r||"function"==r?c.has(e)?r=c.get(e):(r=""+ ++t,c.set(e,r)):r="p_"+e;var b=a.data_[r];if(b&&g.owns(a.data_,r))for(a=0;a<b.length;a++){var n=b[a];if(e!==e&&n.key!==n.key||
e===n.key)return{id:r,list:b,index:a,entry:n}}return{id:r,list:b,index:-1,entry:void 0}}function e(c){this.data_={};this.head_=d();this.size=0;if(c){c=g.makeIterator(c);for(var a;!(a=c.next()).done;)a=a.value,this.set(a[0],a[1])}}if(!g.ASSUME_NO_NATIVE_MAP&&function(){if(!b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),a=new b(g.makeIterator([[c,"s"]]));if("s"!=a.get(c)||1!=a.size||a.get({x:4})||a.set({x:4},"t")!=a||2!=a.size)return!1;var e=a.entries(),
h=e.next();if(h.done||h.value[0]!=c||"s"!=h.value[1])return!1;h=e.next();return h.done||4!=h.value[0].x||"t"!=h.value[1]||!e.next().done?!1:!0}catch(v){return!1}}())return b;g.initSymbol();g.initSymbolIterator();var c=new WeakMap;e.prototype.set=function(c,a){var e=h(this,c);e.list||(e.list=this.data_[e.id]=[]);e.entry?e.entry.value=a:(e.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:c,value:a},e.list.push(e.entry),this.head_.previous.next=e.entry,this.head_.previous=e.entry,
this.size++);return this};e.prototype.delete=function(c){c=h(this,c);return c.entry&&c.list?(c.list.splice(c.index,1),c.list.length||delete this.data_[c.id],c.entry.previous.next=c.entry.next,c.entry.next.previous=c.entry.previous,c.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=d();this.size=0};e.prototype.has=function(c){return!!h(this,c).entry};e.prototype.get=function(c){return(c=h(this,c).entry)&&c.value};e.prototype.entries=function(){return a(this,
function(c){return[c.key,c.value]})};e.prototype.keys=function(){return a(this,function(c){return c.key})};e.prototype.values=function(){return a(this,function(c){return c.value})};e.prototype.forEach=function(c,a){for(var e=this.entries(),b;!(b=e.next()).done;)b=b.value,c.call(a,b[1],b[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var t=0;return e},"es6-impl","es3");g.ASSUME_NO_NATIVE_SET=!1;
g.polyfill("Set",function(b){function d(a){this.map_=new Map;if(a){a=g.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size}if(!g.ASSUME_NO_NATIVE_SET&&function(){if(!b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),h=new b(g.makeIterator([a]));if(!h.has(a)||1!=h.size||h.add(a)!=h||1!=h.size||h.add({x:4})!=h||2!=h.size)return!1;var e=h.entries(),c=e.next();if(c.done||c.value[0]!=a||c.value[1]!=a)return!1;c=e.next();return c.done||
c.value[0]==a||4!=c.value[0].x||c.value[1]!=c.value[0]?!1:e.next().done}catch(t){return!1}}())return b;g.initSymbol();g.initSymbolIterator();d.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};d.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};d.prototype.clear=function(){this.map_.clear();this.size=0};d.prototype.has=function(a){return this.map_.has(a)};d.prototype.entries=function(){return this.map_.entries()};d.prototype.values=
function(){return this.map_.values()};d.prototype[Symbol.iterator]=d.prototype.values;d.prototype.forEach=function(a,b){var e=this;this.map_.forEach(function(c){return a.call(b,c,c,e)})};return d},"es6-impl","es3");g.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");g.polyfill("Number.isFinite",function(b){return b?b:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}},"es6-impl","es3");
g.polyfill("Number.isInteger",function(b){return b?b:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}},"es6-impl","es3");g.polyfill("Number.isSafeInteger",function(b){return b?b:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}},"es6-impl","es3");g.array=g.array||{};
g.iteratorFromArray=function(b,d){g.initSymbolIterator();b instanceof String&&(b+="");var a=0,h={next:function(){if(a<b.length){var e=a++;return{value:d(e,b[e]),done:!1}}h.next=function(){return{done:!0,value:void 0}};return h.next()}};h[Symbol.iterator]=function(){return h};return h};g.polyfill("Array.prototype.entries",function(b){return b?b:function(){return g.iteratorFromArray(this,function(b,a){return[b,a]})}},"es6-impl","es3");
g.polyfill("Array.prototype.values",function(b){return b?b:function(){return g.iteratorFromArray(this,function(b,a){return a})}},"es6","es3");g.checkStringArgs=function(b,d,a){if(null==b)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return b+""};
g.polyfill("String.prototype.startsWith",function(b){return b?b:function(b,a){var h=g.checkStringArgs(this,b,"startsWith");b+="";var e=h.length,c=b.length;a=Math.max(0,Math.min(a|0,h.length));for(var t=0;t<c&&a<e;)if(h[a++]!=b[t++])return!1;return t>=c}},"es6-impl","es3");
g.polyfill("String.prototype.repeat",function(b){return b?b:function(b){var a=g.checkStringArgs(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var h="";b;)if(b&1&&(h+=a),b>>>=1)a+=a;return h}},"es6-impl","es3");
require=function sa(d,a,h){function e(r,n){if(!a[r]){if(!d[r]){var l="function"==typeof require&&require;if(!n&&l)return l(r,!0);if(c)return c(r,!0);n=Error("Cannot find module '"+r+"'");throw n.code="MODULE_NOT_FOUND",n;}n=a[r]={exports:{}};d[r][0].call(n.exports,function(c){var a=d[r][1][c];return e(a?a:c)},n,n.exports,sa,d,a,h)}return a[r].exports}for(var c="function"==typeof require&&require,t=0;t<h.length;t++)e(h[t]);return e}({"/client-side/binary-ajax.js":[function(){(function(b){b.ajaxTransport("+*",
function(b){if(window.FormData&&("blob"===b.dataType||"arraybuffer"===b.dataType||b.data&&(window.Blob&&b.data instanceof Blob||window.ArrayBuffer&&b.data instanceof ArrayBuffer))){var a;return{send:function(h,e){var c=b.url||location.href,t=b.type||"GET",r=b.dataType||"text",n=b.data||null,l=b.async||!0;a=new XMLHttpRequest;a.addEventListener("load",function(){var c={};200<=a.status&&300>a.status||304===a.status?c[r]=a.response:c.text=a.statusText;e(a.status,a.statusText,c,a.getAllResponseHeaders())});
a.open(t,c,l);a.responseType=r;for(var d in h)({}).hasOwnProperty.call(h,d)&&a.setRequestHeader(d,h[d]);a.send(n)},abort:function(){a&&a.abort()}}}})})(jQuery)},{}],"/client-side/common.js":[function(b){var d=b("/lib/assert.js");d.instanceOf(window.Map,Function);d.instanceOf(window.Set,Function);d.instanceOf(window.ArrayBuffer,Function);d.instanceOf(window.Uint8Array,Function);d.instanceOf(window.Symbol,Function);b("/client-side/binary-ajax.js");if(!window.sb){window.sb=b("/structure-types.js");b=
b("/recursive-registry.js");for(var a in b)({}).hasOwnProperty.call(b,a)&&(window.sb[a]=b[a])}else if(!(window.sb instanceof Object))throw Error("window.sb is already defined");},{"/client-side/binary-ajax.js":"/client-side/binary-ajax.js","/lib/assert.js":"/lib/assert.js","/recursive-registry.js":"/recursive-registry.js","/structure-types.js":"/structure-types.js"}],"/config.js":[function(b,d){b=b("base64-js");var a=new ArrayBuffer(2);(new DataView(a)).setUint16(0,10);b=b.fromByteArray(new Uint8Array(a));
d.exports={VERSION_STRING:b}},{"base64-js":2}],"/constructor-registry.js":[function(b,d){(function(a){"/"===a&&(a="");var b=new Map;d.exports={get:function(a){var c=b.get(a);if(c)return c;c={};c=(c[a]=function(){},c)[a];b.set(a,c);return c}}}).call(this,"/")},{}],"/lib/assert.js":[function(b,d){function a(){}var h=b("/lib/util-inspect.js");a.instanceOf=function(a,c){c instanceof Array||(c=[c]);for(var e=!1,b=g.makeIterator(c),n=b.next();!n.done;n=b.next())if(n=n.value,a instanceof n||void 0!==a&&
null!==a&&a.constructor===n){e=!0;break}if(!e)throw new TypeError(h.inspect(a)+" is not an instance of "+c.map(function(c){return c.name}).join(" or "));};a.integer=function(e){a.instanceOf(e,Number);if(!Number.isSafeInteger(e))throw new RangeError(h.inspect(e)+" is not an integer");};a.between=function(a,c,b,r){if(c<a||c>=b){a=h.inspect(c)+" is not in ["+h.inspect(a)+","+h.inspect(b)+")";if(void 0===r)throw new RangeError(a);throw new RangeError(r+" ("+a+")");}};a.byteUnsignedInteger=function(b){a.integer(b);
a.between(0,b,256)};a.fail=function(a){throw Error(a);};a.assert=function(b,c){b||a.fail(c)};a.throws=function(b,c){var e=!0;try{b(),e=!1}catch(r){void 0!==c&&a.message(r,c)}a.assert(e,"Should throw an error")};a.equal=function(b,c){var e=new RangeError("Expected "+h.inspect(c)+" but got "+h.inspect(b));if(c){var r=!0;switch(c.constructor){case Object:if(!b||b.constructor!==Object)throw e;for(var n in c)if({}.hasOwnProperty.call(c,n))try{a.equal(b[n],c[n])}catch(x){throw e;}break;case Array:if(!b||
b.constructor!==Array)throw e;try{a.equal(b.length,c.length)}catch(x){throw e;}for(n=0;n<c.length;n++)try{a.equal(b[n],c[n])}catch(x){throw e;}break;case Map:if(!b||b.constructor!==Map)throw e;try{a.equal(b.size,c.size)}catch(x){throw e;}n=c.entries();for(var l=b.entries(),d;!(d=n.next()).done;)try{a.equal(d.value,l.next().value)}catch(x){throw e;}break;case Set:if(!b||b.constructor!==Set)throw e;try{a.equal(b.size,c.size)}catch(x){throw e;}n=c.values();for(l=b.values();!(d=n.next()).done;)try{a.equal(d.value,
l.next().value)}catch(x){throw e;}break;case ArrayBuffer:if(!b||b.constructor!==ArrayBuffer)throw e;try{a.equal(b.byteLength,c.byteLength)}catch(x){throw e;}b=new Uint8Array(b);c=new Uint8Array(c);try{for(n=0;n<c.length;n++)a.equal(b[n],c[n])}catch(x){throw e;}break;case Function:if(!b||b.constructor!==Function)throw e;try{a.equal(b.name,c.name)}catch(x){throw e;}break;default:r=!1}if(r)return}if(void 0!==c&&null!==c&&c.equals instanceof Function){var v;try{v=c.equals(b)}catch(x){throw Error("equals() is not implemented for "+
h.inspect(c));}if(!v)throw e;}else if(c!==b)throw e;};a.message=function(b,c){a.instanceOf(c,String);a.assert(b&&b.message.startsWith(c),'Message "'+(b?b.message:"No error thrown")+'" does not start with "'+c+'"')};d.exports=a},{"/lib/util-inspect.js":"/lib/util-inspect.js"}],"/lib/bit-math.js":[function(b,d){d.exports={dividedByEight:function(a){return a>>>3},modEight:function(a){return a&7}}},{}],"/lib/buffer-string.js":[function(b,d){(function(a){var h=b(a+"/assert.js"),e=b(a+"/growable-buffer.js");
d.exports={toString:function(c){c&&c.constructor===ArrayBuffer&&(c=new Uint8Array(c));h.instanceOf(c,Uint8Array);for(var a=[],b=0;b<c.length;){var e=c[b],l=void 0,d=239<e?4:223<e?3:191<e?2:1;if(b+d<=c.length){var v,x,A;switch(d){case 1:128>e&&(l=e);break;case 2:v=c[b+1];128===(v&192)&&(e=(e&31)<<6|v&63,127<e&&(l=e));break;case 3:v=c[b+1];x=c[b+2];128===(v&192)&&128===(x&192)&&(e=(e&15)<<12|(v&63)<<6|x&63,2047<e&&(55296>e||57343<e)&&(l=e));break;case 4:v=c[b+1],x=c[b+2],A=c[b+3],128===(v&192)&&128===
(x&192)&&128===(A&192)&&(e=(e&15)<<18|(v&63)<<12|(x&63)<<6|A&63,65535<e&&1114112>e&&(l=e))}}void 0===l?(l=65533,d=1):65535<l&&(l-=65536,a.push(l>>>10&1023|55296),l=56320|l&1023);a.push(l);b+=d}c="";for(b=0;b<a.length;b+=4096)c+=String.fromCharCode.apply(String,[].concat(g.arrayFromIterable(a.slice(b,b+4096))));return c},fromString:function(c){h.instanceOf(c,String);var b=new e;c=g.makeIterator(c);for(var a=c.next();!a.done;a=c.next())a=a.value.charCodeAt(0),128>a?b.add(a):(2048>a?b.add(192|a>>6):
(55296>a||57344<=a?b.add(224|a>>12):(a=65536+((a&1023)<<10|a&1023),b.add(240|a>>18),b.add(128|a>>12&63)),b.add(128|a>>6&63)),b.add(128|a&63));return b.toBuffer()},toBinaryString:function(c){h.instanceOf(c,ArrayBuffer);var a="";c=new Uint8Array(c);c=g.makeIterator(c);for(var b=c.next();!b.done;b=c.next())a+=String.fromCharCode(b.value);return a},fromBinaryString:function(c){h.instanceOf(c,String);for(var a=new ArrayBuffer(c.length),b=new Uint8Array(a),e=0;e<c.length;e++)b[e]=c[e].charCodeAt(0);return a}}}).call(this,
"/lib")},{}],"/lib/flex-int.js":[function(b,d){(function(a){for(var h=b(a+"/assert.js"),e=new Map,c=a=0;a<=Number.MAX_SAFE_INTEGER;)e.set(c,a),c++,a+=Math.pow(2,7*c);e.set(c,a);var t=new Map,r=new Map;a=0;for(var c=7,n=g.makeIterator(e),l=n.next();!l.done;l=n.next()){var l=g.makeIterator(l.value),I=l.next().value;l.next();I&&(r.set(I,a),t.set(I-1,I),a|=1<<c,c--)}d.exports={makeValueBuffer:function(c){h.integer(c);h.assert(0<=c,String(c)+" is negative");var a;a:{a=g.makeIterator(e);for(var b=a.next();!b.done;b=
a.next()){var b=g.makeIterator(b.value),l=b.next().value;if(b.next().value>c){a=l;break a}}a=void 0}l=c-e.get(a-1);c=new ArrayBuffer(a);for(var b=new Uint8Array(c),n=a-1;0<=n;n--)b[n]=l&255,l=Math.floor(l/256);b[0]|=r.get(a);return c},getByteCount:function(c){h.byteUnsignedInteger(c);var a;for(a=0;c&128;a++)c<<=1;c=t.get(a);h.assert(void 0!==c,"Invalid number of bytes");return c},readValueBuffer:function(c){h.instanceOf(c,ArrayBuffer);var a=c.byteLength;c=new Uint8Array(c);for(var b=0,l=0;l<a;l++)b*=
256,b+=c[l];c=b^r.get(a)<<8*(a-1);return e.get(a-1)+c}}}).call(this,"/lib")},{}],"/lib/growable-buffer.js":[function(b,d){(function(a){function h(c){c=void 0===c?10:c;try{e.integer(c),e.between(0,c,Number.MAX_SAFE_INTEGER+1)}catch(t){throw new RangeError(String(c)+" is not a valid buffer length");}this.buffer=new ArrayBuffer(c);this.size=0}var e=b(a+"/assert.js");h.prototype.grow=function(c){e.integer(c);c>this.buffer.byteLength&&(c=new ArrayBuffer(c<<1),(new Uint8Array(c)).set((new Uint8Array(this.buffer)).subarray(0,
this.size)),this.buffer=c);return this};h.prototype.set=function(c,a){e.integer(c);e.between(0,c,this.size,"Index out of bounds: "+String(c));e.integer(a);e.between(0,a,256,"Not a byte: "+String(a));(new Uint8Array(this.buffer))[c]=a;return this};h.prototype.setAll=function(c,a){e.instanceOf(a,ArrayBuffer);e.integer(c);e.between(0,c,this.size-a.byteLength+1,"Index out of bounds: "+String(c));(new Uint8Array(this.buffer)).set(new Uint8Array(a),c);return this};h.prototype.get=function(c){e.integer(c);
e.between(0,c,this.size,"Index out of bounds: "+String(c));return(new Uint8Array(this.buffer))[c]};h.prototype.add=function(c){e.integer(c);e.between(0,c,256,"Not a byte: "+String(c));var a=this.size,b=a+1;this.grow(b);this.size=b;(new Uint8Array(this.buffer))[a]=c;return this};h.prototype.addAll=function(c){e.instanceOf(c,ArrayBuffer);var a=this.size,b=this.size+c.byteLength;this.grow(b);this.size=b;(new Uint8Array(this.buffer)).set(new Uint8Array(c),a);return this};h.prototype.toBuffer=function(){return this.buffer.slice(0,
this.size)};g.global.Object.defineProperties(h.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.size}},rawBuffer:{configurable:!0,enumerable:!0,get:function(){return this.buffer}}});d.exports=h}).call(this,"/lib")},{}],"/lib/strint.js":[function(b,d){var a={};(function(){function b(c){return G(c)?c.length-1:c.length}function e(c,a){v(c);w(a,"number");return a>=b(c)?"0":c.charAt(c.length-a-1)}function c(c,a){x(c);A(a);for(var b=0;b<a;b++)c="0"+c;return c}function d(a,b){x(a);
A(b);return c(a,b-a.length)}function r(c,a){if(G(c)||G(a))throw Error("Both operands must be positive: "+c+" "+a);var b=Math.max(c.length,a.length);c=d(c,b);a=d(a,b);return c<a}function n(a,b){x(a);x(b);if(m(a,"0")&&m(b,"0"))return"0";for(var y=Math.max(a.length,b.length),f="",l=0,h=0,E=0;E<y;E++){for(var k=Number(e(a,E)),n=Number(e(b,E)),k=k+n+l,l=0;10<=k;)k-=10,l++;0===k?h++:(f=String(k)+c(f,h),h=0)}0<l&&(f=String(l)+c(f,h));return f}function l(c,a){return f(c)===f(a)}function I(c,a){for(;0<a;)c+=
"0",a--;return c}function v(c){w(c,"string")}function x(c){v(c);if(!f.call(null,c))throw Error("Condition isPositive failed for value "+c);}function A(c){w(c,"number");if(0>c)throw Error("Expected a positive number: "+c);}function w(c,a){if(typeof c!==a)throw Error("Not a "+a+": "+c);}var C=a.subPositive=function(a,b){x(a);x(b);if(!K(a,b))throw Error("x must be greater or equal to y");for(var f=Math.max(a.length,b.length),y="",l=0,h=0,m=0;m<f;m++){for(var E=Number(e(a,m))-l,l=0,k=Number(e(b,m));E<
k;)E+=10,l++;E=String(E-k);"0"!==E?(y=E+c(y,h),h=0):h++}return 0===y.length?"0":y},q=a.add=function(c,a){v(c);v(a);if(f(c)&&f(a))return n(c,a);if(G(c)&&G(a))return Q(n(k(c),k(a)));if(y(k(c),k(a))){var b=c;c=a;a=b}a=C(k(c),k(a));return f(c)?a:Q(a)},M=a.sub=function(c,a){v(c);v(a);return q(c,Q(a))},F=a.timesDigit=function(a,y){x(a);w(y,"number");for(var f="",l=b(a),h=0,m=0,E=0;E<l;E++){for(var k=Number(e(a,E))*y+h,h=0;10<=k;)k-=10,h++;0===k?m++:(f=String(k)+c(f,m),m=0)}0<h&&(f=String(h)+c(f,m));return 0===
f.length?"0":f},J=a.mulPositive=function(c,a){x(c);x(a);for(var f="0",y=b(a),h=0;h<y;h++)var m=F(c,Number(e(a,h))),m=I(m,h),f=n(f,m);return f},L=a.mul=function(c,a){v(c);v(a);if(m(c,"0")||m(a,"0"))return"0";var b=J(k(c),k(a));return l(c,a)?b:Q(b)},O=a.quotientRemainderPositive=function(c,a){x(c);x(a);if(m(c,a))return["1","0"];if(E(a,c))return["0",T(c)];for(var b="0",e=c.length-a.length;;){for(var f=c.slice(0,c.length-e);K(f,a);)f=M(f,a),b=q(b,"1");c=f+c.slice(c.length-e);if(E(a,c))return b=I(b,e),
[b,T(c)];e--;b=I(b,1);if(0>e)throw Error("Illegal state");}};a.div=function(c,a,b){b=void 0===b?!1:b;v(c);v(a);var e=O(k(c),k(a))[0];l(c,a)||(e=Q(e));!b||m(L(e,a),c)||l(c,a)||(e=M(e,"1"));return e};var m=a.eq=function(c,a){return T(c)===T(a)},y=a.lt=function(c,a){return G(c)&&f(a)?!0:f(c)&&G(a)?!1:G(c)&&G(a)?!m(c,a)&&!r(k(c),k(a)):r(c,a)},K=a.ge=function(c,a){return!y(c,a)},E=a.gt=function(c,a){return m(c,a)?!1:K(c,a)},G=a.isNegative=function(c){v(c);return 0===c.indexOf("-")},f=a.isPositive=function(c){return!G(c)},
k=a.abs=function(c){return G(c)?Q(c):c},Q=a.negate=function(c){return"0"===c?"0":G(c)?c.slice(1):"-"+c},W=/^(-?)0*([1-9][0-9]*)$/,X=/^0+$/,T=a.normalize=function(c){if(X.test(c))return"0";var a=W.exec(c);if(!a)throw Error("Illegal strint format: "+c);return a[1]+a[2]}})();a.LONG_UPPER_SHIFT="4294967296";a.BYTE_SHIFT="256";d.exports=a},{}],"/lib/util-inspect.js":[function(b,d,a){a.inspect=function(b){if(void 0===b)return"undefined";if(null===b||b.constructor===Object||b.constructor===Array||b.constructor===
String||b.constructor===Number||b.constructor===Boolean||b.constructor===Date)return JSON.stringify(b);if(b.constructor===Set){var e="Set {";b=b.values();for(var c=b.next();!c.done;)e+=a.inspect(c.value),c=b.next(),c.done||(e+=", ");return e+"}"}if(b.constructor===Map){e="Map {";b=b.entries();for(c=b.next();!c.done;)e+=a.inspect(c.value[0]),e+=" \x3d\x3e ",e+=a.inspect(c.value[1]),c=b.next(),c.done||(e+=", ");return e+"}"}return b.constructor.name?b.constructor.name+" "+JSON.stringify(b):JSON.stringify(b)}},
{}],1:[function(b){(function(){function d(){var a={},b;for(b in c)a[b]={sig:c[b].sig,type:h.fromByteArray(new Uint8Array(c[b].type.toBuffer()))};localStorage.typeCache=JSON.stringify(a)}b("/client-side/common.js");var a=b("/lib/assert.js"),h=b("base64-js"),e=b("/read.js"),c={};if(localStorage.typeCache){var t=JSON.parse(localStorage.typeCache),r;for(r in t)c[r]={sig:t[r].sig,type:e.type((new Uint8Array(h.toByteArray(t[r].type))).buffer)}}else d();sb.download=function(b,l){function h(c,a,b){if(r){r instanceof
Array||(r=[r]);for(var e=g.makeIterator(r),l=e.next();!l.done;l=e.next())l=l.value,l(c,a,b)}}a.instanceOf(b,String);a.instanceOf(l,Object);l.dataType="arraybuffer";var n;c[b]?(n=!0,l.headers||(l.headers={}),l.headers.sig=c[b].sig):n=!1;var r=l.success;l.success=function(a,l,r){var q=r.getResponseHeader("sig");if(n&&c[b].sig===q)q=e.value({buffer:a,type:c[b].type}),h(q,l,r);else{var v=e._consumeType(a,0);a=e.value({buffer:a,offset:v.length,type:v.value});c[b]={sig:q,type:v.value};d();h(a,l,r)}};$.ajax(l)}})()},
{"/client-side/common.js":"/client-side/common.js","/lib/assert.js":"/lib/assert.js","/read.js":"/read.js","base64-js":2}],2:[function(b,d,a){function h(c){var a=c.length;if(0<a%4)throw Error("Invalid string. Length must be a multiple of 4");return"\x3d"===c[a-2]?2:"\x3d"===c[a-1]?1:0}function e(a,b,e){for(var l=[],h=b;h<e;h+=3)b=(a[h]<<16)+(a[h+1]<<8)+a[h+2],l.push(c[b>>18&63]+c[b>>12&63]+c[b>>6&63]+c[b&63]);return l.join("")}a.byteLength=function(c){return 3*c.length/4-h(c)};a.toByteArray=function(c){var a,
b,e,d,n;a=c.length;d=h(c);n=new r(3*a/4-d);b=0<d?a-4:a;var w=0;for(a=0;a<b;a+=4)e=t[c.charCodeAt(a)]<<18|t[c.charCodeAt(a+1)]<<12|t[c.charCodeAt(a+2)]<<6|t[c.charCodeAt(a+3)],n[w++]=e>>16&255,n[w++]=e>>8&255,n[w++]=e&255;2===d?(e=t[c.charCodeAt(a)]<<2|t[c.charCodeAt(a+1)]>>4,n[w++]=e&255):1===d&&(e=t[c.charCodeAt(a)]<<10|t[c.charCodeAt(a+1)]<<4|t[c.charCodeAt(a+2)]>>2,n[w++]=e>>8&255,n[w++]=e&255);return n};a.fromByteArray=function(a){for(var b=a.length,h=b%3,d="",r=[],n=0,t=b-h;n<t;n+=16383)r.push(e(a,
n,n+16383>t?t:n+16383));1===h?(a=a[b-1],d+=c[a>>2],d+=c[a<<4&63],d+="\x3d\x3d"):2===h&&(a=(a[b-2]<<8)+a[b-1],d+=c[a>>10],d+=c[a>>4&63],d+=c[a<<2&63],d+="\x3d");r.push(d);return r.join("")};var c=[],t=[],r="undefined"!==typeof Uint8Array?Uint8Array:Array;for(b=0;64>b;++b)c[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[b],t["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(b)]=b;t[45]=62;t[95]=63},{}],3:[function(b,d){!function(a){function b(a){return a.map(function(a){a=
a.toString(16);a=2<a.length?a:Array(2-a.length+1).join("0")+a;return a}).join("")}var e={bytesToHex:function(a){return b(a)},hexToBytes:function(a){if(1===a.length%2)throw Error("hexToBytes can't have a string with an odd number of characters.");0===a.indexOf("0x")&&(a=a.slice(2));return a.match(/../g).map(function(a){return parseInt(a,16)})}};"undefined"!==typeof d&&d.exports?d.exports=e:a.convertHex=e}(this)},{}],4:[function(b,d){!function(a){var b={bytesToString:function(a){return a.map(function(a){return String.fromCharCode(a)}).join("")},
stringToBytes:function(a){return a.split("").map(function(a){return a.charCodeAt(0)})},UTF8:{bytesToString:function(a){return decodeURIComponent(escape(b.bytesToString(a)))},stringToBytes:function(a){return b.stringToBytes(unescape(encodeURIComponent(a)))}}};"undefined"!==typeof d&&d.exports?d.exports=b:a.convertString=b}(this)},{}],5:[function(b,d){!function(a){function h(a,b){a.constructor===String&&(a=e.convertString.UTF8.stringToBytes(a));for(var h=[1779033703,3144134277,1013904242,2773480762,
1359893119,2600822924,528734635,1541459225],d=a,r=[],n=0,A=0;n<d.length;n++,A+=8)r[A>>>5]|=d[n]<<24-A%32;a=8*a.length;r[a>>5]|=128<<24-a%32;r[(a+64>>9<<4)+15]=a;for(a=0;a<r.length;a+=16){for(var d=h,n=r,A=a,w=d[0],C=d[1],q=d[2],M=d[3],F=d[4],J=d[5],L=d[6],O=d[7],m=0;64>m;m++){if(16>m)t[m]=n[A+m]|0;else{var y=t[m-15],K=t[m-2];t[m]=((y<<25|y>>>7)^(y<<14|y>>>18)^y>>>3)+t[m-7]+((K<<15|K>>>17)^(K<<13|K>>>19)^K>>>10)+t[m-16]}y=O+((F<<26|F>>>6)^(F<<21|F>>>11)^(F<<7|F>>>25))+(F&J^~F&L)+c[m]+t[m];K=((w<<30|
w>>>2)^(w<<19|w>>>13)^(w<<10|w>>>22))+(w&C^w&q^C&q);O=L;L=J;J=F;F=M+y|0;M=q;q=C;C=w;w=y+K|0}d[0]=d[0]+w|0;d[1]=d[1]+C|0;d[2]=d[2]+q|0;d[3]=d[3]+M|0;d[4]=d[4]+F|0;d[5]=d[5]+J|0;d[6]=d[6]+L|0;d[7]=d[7]+O|0}r=[];for(a=0;a<32*h.length;a+=8)r.push(h[a>>>5]>>>24-a%32&255);return b&&b.asBytes?r:b&&b.asString?e.convertString.bytesToString(r):e.bytesToHex(r)}var e={};"undefined"!==typeof d&&d.exports?(e.bytesToHex=b("convert-hex").bytesToHex,e.convertString=b("convert-string"),d.exports=h):(e.bytesToHex=a.convertHex.bytesToHex,
e.convertString=a.convertString,a.sha256=h);var c=[];!function(){function a(a){for(var c=Math.sqrt(a),b=2;b<=c;b++)if(!(a%b))return!1;return!0}function b(a){return 4294967296*(a-(a|0))|0}for(var e=2,h=0;64>h;)a(e)&&(c[h]=b(Math.pow(e,1/3)),h++),e++}();var t=[];h.x2=function(a,c){return h(h(a,{asBytes:!0}),c)}}(this)},{"convert-hex":3,"convert-string":4}],"/read.js":[function(b,d){(function(a){function h(a,c){l.assert(a.byteLength>c,"Buffer is not long enough");var b=A.getByteCount((new Uint8Array(a))[c]);
l.assert(a.byteLength>=c+b,"Buffer is not long enough");return{value:A.readValueBuffer(a.slice(c,c+b)),length:b}}function e(a,c){return a.length<c?"0".repeat(c-a.length)+a:a}function c(a,c){switch(a.constructor){case q.ArrayType:return Array(c);case q.TupleType:return Array(a.length);case q.MapType:return new Map;case q.SetType:return new Set;case q.StructType:return{};default:l.fail("Invalid type for base value: "+M.inspect(a))}}function t(a){var c=a.buffer,b=a.offset,e=a.count;a=a.baseValue||Array(e);
var e=I.modEight(a.length),h=I.dividedByEight(a.length),e=e?h+1:h;l.assert(c.byteLength>=b+e,"Buffer is not long enough");c=new Uint8Array(c);for(h=0;h<e;h++)for(var f=c[b+h],k=0;8>k;k++){var d=8*h+k;if(d===a.length)break;a[d]=!!(f&1<<I.modEight(~I.modEight(k)))}return{value:a,length:e}}function r(a){var b=a.buffer,e=a.pointerStart,d=a.offset,m=a.type;a=a.baseValue;var f,k;switch(m.constructor){case q.ByteType:k=1;l.assert(b.byteLength>=d+k,"Buffer is not long enough");f=(new Int8Array(b))[d];break;
case q.ShortType:k=2;l.assert(b.byteLength>=d+k,"Buffer is not long enough");f=(new DataView(b)).getInt16(d);break;case q.IntType:k=4;f=(new DataView(b)).getInt32(d);break;case q.LongType:case q.DateType:k=8;l.assert(b.byteLength>=d+k,"Buffer is not long enough");f=new DataView(b);b=f.getInt32(d);d=f.getUint32(d+4);f=C.add(C.mul(String(b),C.LONG_UPPER_SHIFT),String(d));m.constructor===q.DateType&&(f=new Date(Number(f)));break;case q.BigIntType:k=h(b,d);e=k.value;k=k.length;l.assert(b.byteLength>=
d+k+e,"Buffer is not long enough");b=new DataView(b);f=e?String(b.getInt8(d+k)):"0";for(m=1;m<e;m++)m&&(f=C.mul(f,C.BYTE_SHIFT)),f=C.add(f,String(b.getUint8(d+k+m)));k+=e;break;case q.UnsignedByteType:k=1;l.assert(b.byteLength>d,"Buffer is not long enough");f=(new Uint8Array(b))[d];break;case q.UnsignedShortType:k=2;l.assert(b.byteLength>=d+k,"Buffer is not long enough");f=(new DataView(b)).getUint16(d);break;case q.UnsignedIntType:k=4;l.assert(b.byteLength>=d+k,"Buffer is not long enough");f=(new DataView(b)).getUint32(d);
break;case q.UnsignedLongType:k=8;l.assert(b.byteLength>=d+k,"Buffer is not long enough");f=new DataView(b);b=f.getUint32(d);d=f.getUint32(d+4);f=C.add(C.mul(String(b),C.LONG_UPPER_SHIFT),String(d));break;case q.BigUnsignedIntType:k=h(b,d);e=k.value;k=k.length;l.assert(b.byteLength>=d+k+e,"Buffer is not long enough");b=new DataView(b);f="0";for(m=0;m<e;m++)m&&(f=C.mul(f,C.BYTE_SHIFT)),f=C.add(f,String(b.getUint8(d+k+m)));k+=e;break;case q.FlexUnsignedIntType:k=h(b,d);f=k.value;k=k.length;break;case q.DayType:k=
3;l.assert(b.byteLength>=d+k,"Buffer is not long enough");b=new DataView(b);d=(b.getInt16(d)<<8|b.getUint8(d+2))*q.MILLIS_PER_DAY;f=new Date(d+(new Date(d)).getTimezoneOffset()*q.MILLIS_PER_MINUTE);break;case q.TimeType:k=4;l.assert(b.byteLength>=d+k,"Buffer is not long enough");f=new Date((new DataView(b)).getUint32(d));break;case q.FloatType:k=4;l.assert(b.byteLength>=d+k,"Buffer is not long enough");f=(new DataView(b)).getFloat32(d);break;case q.DoubleType:k=8;l.assert(b.byteLength>=d+k,"Buffer is not long enough");
f=(new DataView(b)).getFloat64(d);break;case q.BooleanType:k=1;l.assert(b.byteLength>d,"Buffer is not long enough");d=(new Uint8Array(b))[d];l.assert(0===d||255===d,"0x"+d.toString(16)+" is an invalid Boolean value");f=!!d;break;case q.BooleanArrayType:f=h(b,d);k=f.length;d=t({buffer:b,offset:d+k,count:f.value,baseValue:a});k+=d.length;f=d.value;break;case q.BooleanTupleType:k=t({buffer:b,offset:d,count:m.length,baseValue:a});f=k.value;k=k.length;break;case q.CharType:l.assert(b.byteLength>d,"Buffer is not long enough");
f=v.toString((new Uint8Array(b)).subarray(d,d+4))[0];k=v.fromString(f).byteLength;break;case q.StringType:f=new Uint8Array(b);for(k=0;l.assert(b.byteLength>d+k,"Buffer is not long enough"),f[d+k];k++);f=v.toString((new Uint8Array(b)).subarray(d,d+k));k++;break;case q.OctetsType:f=h(b,d);k=f.length;e=k+f.value;l.assert(b.byteLength>=d+e,"Buffer is not long enough");f=b.slice(d+k,d+e);k=e;break;case q.TupleType:k=0;f=a||c(m);for(a=0;a<m.length;a++){var n=r({buffer:b,pointerStart:e,offset:d+k,type:m.type});
k+=n.length;f[a]=n.value}break;case q.StructType:k=0;f=a||c(m);m=g.makeIterator(m.fields);for(a=m.next();!a.done;a=m.next())a=a.value,n=r({buffer:b,pointerStart:e,offset:d+k,type:a.type}),f[a.name]=n.value,k+=n.length;break;case q.ArrayType:k=h(b,d);n=k.value;k=k.length;f=a||c(m,n);for(a=0;a<n;a++){var w=r({buffer:b,pointerStart:e,offset:d+k,type:m.type});k+=w.length;f[a]=w.value}break;case q.SetType:n=h(b,d);k=n.length;f=a||c(m);for(a=0;a<n.value;a++)w=r({buffer:b,pointerStart:e,offset:d+k,type:m.type}),
k+=w.length,f.add(w.value);break;case q.MapType:n=h(b,d);k=n.length;f=a||c(m);for(a=0;a<n.value;a++){w=r({buffer:b,pointerStart:e,offset:d+k,type:m.keyType});k+=w.length;var A=r({buffer:b,pointerStart:e,offset:d+k,type:m.valueType});k+=A.length;f.set(w.value,A.value)}break;case q.EnumType:k=1;l.assert(b.byteLength>d,"Buffer is not long enough");d=(new Uint8Array(b))[d];f=m.values[d];void 0===f&&l.fail("Index "+String(d)+" is invalid");break;case q.ChoiceType:k=1;l.assert(b.byteLength>d,"Buffer is not long enough");
f=(new Uint8Array(b))[d];d=r({buffer:b,pointerStart:e,offset:d+k,type:m.types[f]});k+=d.length;f=d.value;break;case q.NamedChoiceType:k=1;l.assert(b.byteLength>d,"Buffer is not long enough");f=(new Uint8Array(b))[d];a=m.indexConstructors.get(f).name;a=x.get(a);d=r({buffer:b,pointerStart:e,offset:d+k,type:m.constructorTypes[f].type,baseValue:new a});k+=d.length;f=d.value;break;case q.RecursiveType:k=1;l.assert(b.byteLength>d,"Buffer is not long enough");f=(new Uint8Array(b))[d];l.assert(0===f||255===
f,"0x"+f.toString(16)+" is an invalid Recursive byte");f?(m=m.type,f=c(m),L.has(b)||L.set(b,new Map),L.get(b).set(d+k,f),k+=r({buffer:b,pointerStart:e,offset:d+k,type:m,baseValue:f}).length):(e=h(b,d+k),d=d+k-e.value,f=L.get(b).get(d),l.assert(void 0!==f,"Cannot find target at "+String(d)),k+=e.length);break;case q.OptionalType:k=1;l.assert(b.byteLength>d,"Buffer is not long enough");f=(new Uint8Array(b))[d];l.assert(0===f||255===f,"0x"+f.toString(16)+" is an invalid Optional byte");f?(d=r({buffer:b,
pointerStart:e,offset:d+k,type:m.type}),k+=d.length,f=d.value):f=null;break;case q.PointerType:k=4;l.assert(b.byteLength>=d+k,"Buffer is not long enough");d=(new DataView(b)).getUint32(d);f=r({buffer:b,pointerStart:e,offset:e+d,type:m.type}).value;break;default:l.fail("Not a structure type: "+M.inspect(m))}return{value:f,length:k}}function n(a,b){l.assert(0<=b,"Offset is negative: "+String(b));var c=new Uint8Array(a);l.assert(a.byteLength>b,"Buffer is not long enough");var d=c[b],m,f=1,k=F.get(d);
if(void 0!==k)return{value:new k,length:f};switch(d){case q.BooleanTupleType._value:l.assert(a.byteLength>b+f,"Buffer is not long enough");a=c[b+f];f++;m=new q.BooleanTupleType(a);break;case q.TupleType._value:var t=n(a,b+f),f=f+t.length;l.assert(a.byteLength>b+f,"Buffer is not long enough");a=c[b+f];f++;m=new q.TupleType({type:t.value,length:a});break;case q.StructType._value:l.assert(a.byteLength>b+f,"Buffer is not long enough");t=c[b+f];f++;m={};for(d=0;d<t;d++){l.assert(a.byteLength>b+f,"Buffer is not long enough");
k=c[b+f];f++;var y=b+f,A=y+k;l.assert(a.byteLength>=A,"Buffer is not long enough");y=v.toString(c.subarray(y,A));f+=k;k=n(a,A);m[y]=k.value;f+=k.length}m=new q.StructType(m);break;case q.ArrayType._value:a=n(a,b+f);f+=a.length;m=new q.ArrayType(a.value);break;case q.SetType._value:a=n(a,b+f);f+=a.length;m=new q.SetType(a.value);break;case q.MapType._value:c=n(a,b+f);f+=c.length;a=n(a,b+f);f+=a.length;m=new q.MapType(c.value,a.value);break;case q.EnumType._value:c=n(a,b+f);f+=c.length;l.assert(a.byteLength>
b+f,"Buffer is not long enough");t=(new Uint8Array(a))[b+f];f++;m=Array(t);for(d=0;d<t;d++)k=b+f,k=r({buffer:a,pointerStart:k,offset:k,type:c.value}),f+=k.length,m[d]=k.value;m=new q.EnumType({type:c.value,values:m});break;case q.ChoiceType._value:l.assert(a.byteLength>b+f,"Buffer is not long enough");c=(new Uint8Array(a))[b+f];f++;t=Array(c);for(m=0;m<c;m++)d=n(a,b+f),t[m]=d.value,f+=d.length;m=new q.ChoiceType(t);break;case q.NamedChoiceType._value:l.assert(a.byteLength>b+f,"Buffer is not long enough");
t=c[b+f];f++;m=new Map;for(d=0;d<t;d++)l.assert(a.byteLength>b+f,"Buffer is not long enough"),k=c[b+f],f++,y=b+f,A=y+k,l.assert(a.byteLength>=A,"Buffer is not long enough"),y=v.toString(c.subarray(y,A)),f+=k,k=n(a,A),m.set(x.get(y),k.value),f+=k.length;m=new q.NamedChoiceType(m);break;case q.RecursiveType._value:m=h(a,b+f);c=m.value;f+=m.length;(m=O.get(a))?t=m.get(c):(m=new Map,O.set(a,m));if(!t){do for(t="read-type",d=0;16>d;d++)t+=Math.floor(16*Math.random()).toString(16);while(w.isRegistered(t));
m.set(c,t);a=n(a,b+f);f+=a.length;w.registerType({type:a.value,name:t})}m=new q.RecursiveType(t);break;case q.OptionalType._value:a=n(a,b+f);f+=a.length;m=new q.OptionalType(a.value);break;case q.PointerType._value:a=n(a,b+f);f+=a.length;m=new q.PointerType(a.value);break;case q.REPEATED_TYPE:c=h(a,b+f);m=n(a,b+f-c.value).value;f+=c.length;break;default:l.fail("No such type: 0x"+e((new Uint8Array(a))[b].toString(16),2))}return{value:m,length:f}}"/"===a&&(a="");var l=b(a+"/lib/assert.js"),I=b(a+"/lib/bit-math.js"),
v=b(a+"/lib/buffer-string.js"),x=b(a+"/constructor-registry.js"),A=b(a+"/lib/flex-int.js"),w=b(a+"/recursive-registry.js"),C=b(a+"/lib/strint.js"),q=b(a+"/structure-types.js"),M=b("/lib/util-inspect.js");a=new Set([q.ByteType,q.ShortType,q.IntType,q.LongType,q.BigIntType,q.UnsignedByteType,q.UnsignedShortType,q.UnsignedIntType,q.UnsignedLongType,q.BigUnsignedIntType,q.FlexUnsignedIntType,q.DateType,q.DayType,q.TimeType,q.FloatType,q.DoubleType,q.BooleanType,q.BooleanArrayType,q.CharType,q.StringType,
q.OctetsType]);var F=new Map;a=g.makeIterator(a);for(var J=a.next();!J.done;J=a.next())J=J.value,F.set(J._value,J);var L=new WeakMap,O=new WeakMap;d.exports={_consumeType:n,type:function(a,b){b=void 0===b?!0:b;l.instanceOf(a,ArrayBuffer);var c=n(a,0),d=c.value,c=c.length;b&&l.assert(c===a.byteLength,"Did not consume all of the buffer");return d},value:function(a){var b=a.buffer,c=a.type;a=void 0===a.offset?0:a.offset;l.instanceOf(b,ArrayBuffer);l.instanceOf(c,q.Type);l.instanceOf(a,Number);return r({buffer:b,
offset:a,type:c,pointerStart:a}).value}}}).call(this,"/")},{"/lib/util-inspect.js":"/lib/util-inspect.js"}],"/recursive-registry.js":[function(b,d){(function(a){"/"===a&&(a="");var h=b(a+"/lib/assert.js"),e=b(a+"/structure-types.js"),c=new Map;d.exports={registerType:function(a){var b=a.type;a=a.name;h.instanceOf(b,[e.ArrayType,e.MapType,e.SetType,e.StructType,e.TupleType]);h.instanceOf(a,String);h.assert(!c.has(a),'"'+a+'" is already a registered type');c.set(a,b)},getType:function(a){h.instanceOf(a,
String);var b=c.get(a);h.assert(void 0!==b,'"'+a+'" is not a registered type');return b},isRegistered:function(a){return c.has(a)}}}).call(this,"/")},{}],"/structure-types.js":[function(b,d){(function(a){function h(a){p.instanceOf(a,u);this.type=a;return this}function e(a){var b;b=u.call(this)||this;p.instanceOf(a,D);b.type=a;return b}function c(a){var b;b=u.call(this)||this;p.instanceOf(a,String);b.name=a;return b}function t(a){var b;b=u.call(this)||this;p.instanceOf(a,Map);try{p.byteUnsignedInteger(a.size)}catch(Y){p.fail(String(a.size)+
" types is too many")}b.indexConstructors=new Map;b.constructorTypes=Array(a.size);var c=new Set;a=g.makeIterator(a);for(var d=a.next();!d.done;d=a.next()){var e=g.makeIterator(d.value),d=e.next().value,e=e.next().value;p.instanceOf(d,Function);var H=d.name;p.assert(H,'Function "'+String(H)+'" does not have a name');p.assert(!c.has(H),'Function name "'+H+'" is repeated');c.add(H);var f=U.fromString(H);try{p.byteUnsignedInteger(f.byteLength)}catch(Y){p.fail('Function name "'+H+'" is too long')}p.instanceOf(e,
x);H=b.indexConstructors.size;b.indexConstructors.set(H,d);b.constructorTypes[H]={nameBuffer:f,type:e}}return b}function r(a){var b;b=u.call(this)||this;p.instanceOf(a,Array);try{p.byteUnsignedInteger(a.length)}catch(wa){p.fail(String(a.length)+" types is too many")}for(var c=g.makeIterator(a),d=c.next();!d.done;d=c.next())p.instanceOf(d.value,D);b.types=a;return b}function n(a){var b=a.type;a=a.values;p.instanceOf(b,u);p.instanceOf(a,Array);try{p.byteUnsignedInteger(a.length)}catch(ma){p.fail(String(a.length)+
" values is too many")}for(var c=new Map,d=0;d<a.length;d++){var e=a[d],H=U.toBinaryString(b.valueBuffer(e));p.assert(!c.has(H),"Value is repeated: "+ea.inspect(e));c.set(H,d)}this.type=b;this.values=a;this.valueIndices=c;return this}function l(a,b){var c;c=u.call(this)||this;p.instanceOf(a,D);p.instanceOf(b,D);c.keyType=a;c.valueType=b;return c}function I(a){return v.apply(this,arguments)||this}function v(a){var b;b=u.call(this)||this;p.instanceOf(a,D);b.type=a;return b}function x(a){var b;b=u.call(this)||
this;p.instanceOf(a,Object);var c=0,d;for(d in a)({}).hasOwnProperty.call(a,d)&&c++;try{p.byteUnsignedInteger(c)}catch(Y){p.fail(String(c)+" fields is too many")}b.fields=Array(c);var c=0,e;for(e in a)if({}.hasOwnProperty.call(a,e)){d=U.fromString(e);try{p.byteUnsignedInteger(d.byteLength)}catch(Y){p.fail("Field name "+e+" is too long")}var H=a[e];try{p.instanceOf(H,D)}catch(Y){p.fail(String(H)+" is not a valid field type")}var f={};b.fields[c]=(f.name=e,f.type=H,f.buffer=d,f);c++}b.fields.sort(function(a,
b){if(a.name<b.name)return-1;if(a.name>b.name)return 1});return b}function A(a){var b=a.type,c=a.length;a=u.call(this)||this;p.instanceOf(b,D);p.byteUnsignedInteger(c);a.type=b;a.length=c;return a}function w(a){return u.apply(this,arguments)||this}function C(a){return u.apply(this,arguments)||this}function q(a){return u.apply(this,arguments)||this}function M(a){return u.apply(this,arguments)||this}function F(a){var b;b=u.call(this)||this;p.byteUnsignedInteger(a);b.length=a;return b}function J(a){return u.apply(this,
arguments)||this}function L(a){return m.apply(this,arguments)||this}function O(a){return m.apply(this,arguments)||this}function m(a){return u.apply(this,arguments)||this}function y(a){return G.apply(this,arguments)||this}function K(a){return G.apply(this,arguments)||this}function E(a){return G.apply(this,arguments)||this}function G(a){return u.apply(this,arguments)||this}function f(a){return N.apply(this,arguments)||this}function k(a){return N.apply(this,arguments)||this}function Q(a){return N.apply(this,
arguments)||this}function W(a){return N.apply(this,arguments)||this}function X(a){return N.apply(this,arguments)||this}function T(a){return N.apply(this,arguments)||this}function N(a){return u.apply(this,arguments)||this}function Z(a){return P.apply(this,arguments)||this}function aa(a){return P.apply(this,arguments)||this}function ba(a){return P.apply(this,arguments)||this}function ca(a){return P.apply(this,arguments)||this}function da(a){return P.apply(this,arguments)||this}function P(a){return u.apply(this,
arguments)||this}function u(a){return D.apply(this,arguments)||this}function D(){}function R(a,b){if(b&&(b=ga.get(a))){b=g.makeIterator(b);for(var c=b.next();!c.done;c=b.next()){var d=g.makeIterator(c.value),c=d.next().value,d=d.next().value,e=a.length;a.addAll(U.fromBinaryString(c));c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,e);d=g.makeIterator(d);for(e=d.next();!e.done;e=d.next())a.setAll(e.value,c)}}}function V(a){if(a&&a.constructor===String&&(a=Number(a),!isNaN(a)))return a}function na(a,
b){p.instanceOf(a,z);p.instanceOf(b,String);p.assert(!(B.gt(b,"9223372036854775807")||B.lt(b,"-9223372036854775808")),"Value out of range");var c=B.div(b,B.LONG_UPPER_SHIFT,!0);b=B.sub(b,B.mul(c,B.LONG_UPPER_SHIFT));var d=new ArrayBuffer(8),e=new DataView(d);e.setInt32(0,Number(c));e.setUint32(4,Number(b));a.addAll(d)}function oa(a,b){p.instanceOf(b,Array);for(var c=ha(b.length),d=ia(b.length),c=new ArrayBuffer(c?d+1:d),d=new Uint8Array(c),e=0;e<b.length;e++){var ka=b[e];p.instanceOf(ka,Boolean);
var H=ha(~ha(e));ka?d[ia(e)]|=1<<H:d[ia(e)]&=~(1<<H)}a.addAll(c)}"/"===a&&(a="");var p=b(a+"/lib/assert.js"),ta=b("base64-js"),U=b(a+"/lib/buffer-string.js"),ua=b(a+"/config.js"),S=b(a+"/lib/flex-int.js"),va=b("sha256"),z=b(a+"/lib/growable-buffer.js"),ja,B=b(a+"/lib/strint.js"),ea=b("/lib/util-inspect.js"),pa=b(a+"/lib/bit-math.js"),ia=pa.dividedByEight,ha=pa.modEight,qa=new WeakMap,fa=new WeakMap,ra=new WeakMap,ga=new WeakMap;D.prototype.addToBuffer=function(a){p.instanceOf(a,z);if(this.cachedTypeLocations){if(!fa.get(a)){var b=
this.cachedTypeLocations.get(a);if(void 0!==b)return a.add(255),a.addAll(S.makeValueBuffer(a.length-b)),!1}}else this.cachedTypeLocations=new Map;this.cachedTypeLocations.set(a,a.length);a.add(this.constructor._value);return!0};D.prototype.toBuffer=function(){this.cachedBuffer||(this.cachedBuffer=this._toBuffer());return this.cachedBuffer};D.prototype._toBuffer=function(){var a=new z;this.addToBuffer(a);return a.toBuffer()};D.prototype.getHash=function(){this.cachedHash||(this.cachedHash=this._getHash());
return this.cachedHash};D.prototype._getHash=function(){return ta.fromByteArray(va(this.toBuffer(),{asBytes:!0}))};D.prototype.getSignature=function(){this.cachedSignature||(this.cachedSignature=this._getSignature());return this.cachedSignature};D.prototype._getSignature=function(){return ua.VERSION_STRING+this.getHash()};D.prototype.writeValue=function(){p.fail("Generic Type has no value representation")};D.prototype.valueBuffer=function(a){var b=new z;this.writeValue(b,a);return b.toBuffer()};D.prototype.equals=
function(a){try{p.instanceOf(a,this.constructor)}catch(la){return!1}try{p.equal(a.constructor,this.constructor)}catch(la){return!1}for(var b in this)if({}.hasOwnProperty.call(this,b)&&!b.startsWith("cached"))try{p.equal(a[b],this[b])}catch(la){return!1}return!0};g.global.Object.defineProperties(D,{_value:{configurable:!0,enumerable:!0,get:function(){p.fail("Generic Type has no value byte")}}});g.inherits(u,D);g.inherits(P,u);g.inherits(da,P);da.prototype.writeValue=function(a,b){p.instanceOf(a,z);
var c=V(b);void 0!==c&&(b=c);p.integer(b);p.between(-128,b,128,"Value out of range");c=new ArrayBuffer(1);(new DataView(c)).setInt8(0,b);a.addAll(c)};g.global.Object.defineProperties(da,{_value:{configurable:!0,enumerable:!0,get:function(){return 1}}});g.inherits(ca,P);ca.prototype.writeValue=function(a,b){p.instanceOf(a,z);var c=V(b);void 0!==c&&(b=c);p.integer(b);p.between(-32768,b,32768,"Value out of range");c=new ArrayBuffer(2);(new DataView(c)).setInt16(0,b);a.addAll(c)};g.global.Object.defineProperties(ca,
{_value:{configurable:!0,enumerable:!0,get:function(){return 2}}});g.inherits(ba,P);ba.prototype.writeValue=function(a,b){p.instanceOf(a,z);var c=V(b);void 0!==c&&(b=c);p.integer(b);p.between(-2147483648,b,2147483648,"Value out of range");c=new ArrayBuffer(4);(new DataView(c)).setInt32(0,b);a.addAll(c)};g.global.Object.defineProperties(ba,{_value:{configurable:!0,enumerable:!0,get:function(){return 3}}});g.inherits(aa,P);aa.prototype.writeValue=function(a,b){na(a,b)};g.global.Object.defineProperties(aa,
{_value:{configurable:!0,enumerable:!0,get:function(){return 4}}});g.inherits(Z,P);Z.prototype.writeValue=function(a,b){p.instanceOf(a,z);p.instanceOf(b,String);b=B.normalize(b);var c=[];if(!B.eq(b,"0")){for(;B.gt(b,"127")||B.lt(b,"-128");){var d=B.div(b,B.BYTE_SHIFT,!0);b=B.sub(b,B.mul(d,B.BYTE_SHIFT));c.push(Number(b));b=d}c.push(Number(b))}a.addAll(S.makeValueBuffer(c.length));d=new ArrayBuffer(c.length);b=new DataView(d);for(var e=1,f=c.length-2;0<=f;f--,e++)b.setUint8(e,c[f]);c.length&&b.setInt8(0,
c[c.length-1]);a.addAll(d)};g.global.Object.defineProperties(Z,{_value:{configurable:!0,enumerable:!0,get:function(){return 5}}});g.inherits(N,u);g.inherits(T,N);T.prototype.writeValue=function(a,b){p.instanceOf(a,z);var c=V(b);void 0!==c&&(b=c);p.integer(b);p.between(0,b,256,"Value out of range");c=new ArrayBuffer(1);(new Uint8Array(c))[0]=b;a.addAll(c)};g.global.Object.defineProperties(T,{_value:{configurable:!0,enumerable:!0,get:function(){return 17}}});g.inherits(X,N);X.prototype.writeValue=function(a,
b){p.instanceOf(a,z);var c=V(b);void 0!==c&&(b=c);p.integer(b);p.between(0,b,65536,"Value out of range");c=new ArrayBuffer(2);(new DataView(c)).setUint16(0,b);a.addAll(c)};g.global.Object.defineProperties(X,{_value:{configurable:!0,enumerable:!0,get:function(){return 18}}});g.inherits(W,N);W.prototype.writeValue=function(a,b){p.instanceOf(a,z);var c=V(b);void 0!==c&&(b=c);p.integer(b);p.between(0,b,4294967296,"Value out of range");c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,b);a.addAll(c)};
g.global.Object.defineProperties(W,{_value:{configurable:!0,enumerable:!0,get:function(){return 19}}});g.inherits(Q,N);Q.prototype.writeValue=function(a,b){p.instanceOf(a,z);p.instanceOf(b,String);p.assert(!(B.gt(b,"18446744073709551615")||B.lt(b,"0")),"Value out of range");var c=B.div(b,B.LONG_UPPER_SHIFT);b=B.sub(b,B.mul(c,B.LONG_UPPER_SHIFT));var d=new ArrayBuffer(8),e=new DataView(d);e.setUint32(0,Number(c));e.setUint32(4,Number(b));a.addAll(d)};g.global.Object.defineProperties(Q,{_value:{configurable:!0,
enumerable:!0,get:function(){return 20}}});g.inherits(k,N);k.prototype.writeValue=function(a,b){p.instanceOf(a,z);p.instanceOf(b,String);p.assert(!B.isNegative(b),"Value out of range");var c=[];if(!B.eq(b,"0")){for(;B.ge(b,B.BYTE_SHIFT);){var d=g.makeIterator(B.quotientRemainderPositive(b,B.BYTE_SHIFT));b=d.next().value;d=d.next().value;c.push(Number(d))}c.push(Number(b))}a.addAll(S.makeValueBuffer(c.length));b=new ArrayBuffer(c.length);for(var d=new DataView(b),e=0,f=c.length-1;0<=f;f--,e++)d.setUint8(e,
c[f]);a.addAll(b)};g.global.Object.defineProperties(k,{_value:{configurable:!0,enumerable:!0,get:function(){return 21}}});g.inherits(f,N);f.prototype.writeValue=function(a,b){p.instanceOf(a,z);var c=V(b);void 0!==c&&(b=c);p.integer(b);a.addAll(S.makeValueBuffer(b))};g.global.Object.defineProperties(f,{_value:{configurable:!0,enumerable:!0,get:function(){return 23}}});g.inherits(G,u);g.inherits(E,G);E.prototype.writeValue=function(a,b){p.instanceOf(b,Date);na(a,String(b.getTime()))};g.global.Object.defineProperties(E,
{_value:{configurable:!0,enumerable:!0,get:function(){return 26}}});g.inherits(K,G);K.prototype.writeValue=function(a,b){p.instanceOf(b,Date);b=new Date(b.getFullYear(),b.getMonth(),b.getDate());b=(b.getTime()-6E4*b.getTimezoneOffset())/864E5;var c=new ArrayBuffer(3),d=new DataView(c);d.setInt16(0,b>>8);d.setUint8(2,b&255);a.addAll(c)};g.global.Object.defineProperties(K,{_value:{configurable:!0,enumerable:!0,get:function(){return 27}}});g.inherits(y,G);y.prototype.writeValue=function(a,b){p.instanceOf(b,
Date);var c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,b.getTime()%864E5);a.addAll(c)};g.global.Object.defineProperties(y,{_value:{configurable:!0,enumerable:!0,get:function(){return 28}}});g.inherits(m,u);g.inherits(O,m);O.prototype.writeValue=function(a,b){p.instanceOf(a,z);var c=V(b);void 0!==c&&(b=c);p.instanceOf(b,Number);c=new ArrayBuffer(4);(new DataView(c)).setFloat32(0,b);a.addAll(c)};g.global.Object.defineProperties(O,{_value:{configurable:!0,enumerable:!0,get:function(){return 32}}});
g.inherits(L,m);L.prototype.writeValue=function(a,b){p.instanceOf(a,z);var c=V(b);void 0!==c&&(b=c);p.instanceOf(b,Number);c=new ArrayBuffer(8);(new DataView(c)).setFloat64(0,b);a.addAll(c)};g.global.Object.defineProperties(L,{_value:{configurable:!0,enumerable:!0,get:function(){return 33}}});g.inherits(J,u);J.prototype.writeValue=function(a,b){p.instanceOf(a,z);p.instanceOf(b,Boolean);b?a.add(255):a.add(0)};g.global.Object.defineProperties(J,{_value:{configurable:!0,enumerable:!0,get:function(){return 48}}});
g.inherits(F,u);F.prototype.addToBuffer=function(a){u.prototype.addToBuffer.call(this,a)&&a.add(this.length)};F.prototype.writeValue=function(a,b){p.instanceOf(a,z);p.instanceOf(b,Array);p.assert(b.length===this.length,"Length does not match: expected "+String(this.length)+" but got "+b.length);oa(a,b)};g.global.Object.defineProperties(F,{_value:{configurable:!0,enumerable:!0,get:function(){return 49}}});g.inherits(M,u);M.prototype.writeValue=function(a,b){p.instanceOf(b,Array);a.addAll(S.makeValueBuffer(b.length));
oa(a,b)};g.global.Object.defineProperties(M,{_value:{configurable:!0,enumerable:!0,get:function(){return 50}}});g.inherits(q,u);q.prototype.writeValue=function(a,b){p.instanceOf(a,z);p.instanceOf(b,String);p.assert(1===b.length,"String must contain only 1 character");a.addAll(U.fromString(b))};g.global.Object.defineProperties(q,{_value:{configurable:!0,enumerable:!0,get:function(){return 64}}});g.inherits(C,u);C.prototype.writeValue=function(a,b){p.instanceOf(a,z);p.instanceOf(b,String);b=U.fromString(b);
a.addAll(b);a.add(0)};g.global.Object.defineProperties(C,{_value:{configurable:!0,enumerable:!0,get:function(){return 65}}});g.inherits(w,u);w.prototype.writeValue=function(a,b){p.instanceOf(a,z);p.instanceOf(b,ArrayBuffer);a.addAll(S.makeValueBuffer(b.byteLength));a.addAll(b)};g.global.Object.defineProperties(w,{_value:{configurable:!0,enumerable:!0,get:function(){return 66}}});g.inherits(A,u);A.prototype.addToBuffer=function(a){u.prototype.addToBuffer.call(this,a)&&(this.type.addToBuffer(a),a.add(this.length))};
A.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(a,z);p.instanceOf(b,Array);p.assert(b.length===this.length,"Length does not match: expected "+String(this.length)+" but got "+b.length);b=g.makeIterator(b);for(var d=b.next();!d.done;d=b.next())this.type.writeValue(a,d.value,!1);R(a,c)};g.global.Object.defineProperties(A,{_value:{configurable:!0,enumerable:!0,get:function(){return 80}}});g.inherits(x,u);x.prototype.addToBuffer=function(a){if(u.prototype.addToBuffer.call(this,a)){a.add(this.fields.length);
for(var b=g.makeIterator(this.fields),c=b.next();!c.done;c=b.next()){var c=c.value,d=c.buffer;a.add(d.byteLength);a.addAll(d);c.type.addToBuffer(a)}}};x.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(a,z);p.instanceOf(b,Object);for(var d=g.makeIterator(this.fields),e=d.next();!e.done;e=d.next()){var e=e.value,f=b[e.name];try{e.type.writeValue(a,f,!1)}catch(ma){throw p.assert(void 0!==f,'Value for field "'+e.name+'" missing'),ma;}}R(a,c)};g.global.Object.defineProperties(x,{_value:{configurable:!0,
enumerable:!0,get:function(){return 81}}});g.inherits(v,u);v.prototype.addToBuffer=function(a){u.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};v.prototype._writeValue=function(a){var b=a;a=b.buffer;var c=b.value,d=b.length,b=b.root;p.instanceOf(a,z);a.addAll(S.makeValueBuffer(d));c=g.makeIterator(c);for(d=c.next();!d.done;d=c.next())this.type.writeValue(a,d.value,!1);R(a,b)};v.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(b,Array);this._writeValue({buffer:a,value:b,
length:b.length,root:c})};g.global.Object.defineProperties(v,{_value:{configurable:!0,enumerable:!0,get:function(){return 82}}});g.inherits(I,v);I.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(b,Set);this._writeValue({buffer:a,value:b,length:b.size,root:c})};g.global.Object.defineProperties(I,{_value:{configurable:!0,enumerable:!0,get:function(){return 83}}});g.inherits(l,u);l.prototype.addToBuffer=function(a){u.prototype.addToBuffer.call(this,a)&&(this.keyType.addToBuffer(a),
this.valueType.addToBuffer(a))};l.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(a,z);p.instanceOf(b,Map);a.addAll(S.makeValueBuffer(b.size));b=g.makeIterator(b);for(var d=b.next();!d.done;d=b.next()){var e=g.makeIterator(d.value),d=e.next().value,e=e.next().value;this.keyType.writeValue(a,d,!1);this.valueType.writeValue(a,e,!1)}R(a,c)};g.global.Object.defineProperties(l,{_value:{configurable:!0,enumerable:!0,get:function(){return 84}}});g.inherits(n,D);n.prototype.addToBuffer=
function(a){if(D.prototype.addToBuffer.call(this,a)){this.type.addToBuffer(a);a.add(this.valueIndices.size);for(var b=g.makeIterator(this.valueIndices),c=b.next();!c.done;c=b.next()){var c=g.makeIterator(c.value),d=c.next().value;c.next();a.addAll(U.fromBinaryString(d))}}};n.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(a,z);var d=new z;this.type.writeValue(d,b,!1);d=this.valueIndices.get(U.toBinaryString(d.toBuffer()));p.assert(void 0!==d,"Not a valid enum value: "+ea.inspect(b));
a.add(d);R(a,c)};g.global.Object.defineProperties(n,{_value:{configurable:!0,enumerable:!0,get:function(){return 85}}});g.inherits(r,u);r.prototype.addToBuffer=function(a){if(u.prototype.addToBuffer.call(this,a)){a.add(this.types.length);for(var b=g.makeIterator(this.types),c=b.next();!c.done;c=b.next())c.value.addToBuffer(a)}};r.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(a,z);for(var d=!1,e=0;e<this.types.length;e++){var f=this.types[e],h=new z;try{f.writeValue(h,b,!1)}catch(Y){continue}a.add(e);
a.addAll(h.toBuffer());d=!0;break}p.assert(d,"No types matched: "+ea.inspect(b));R(a,c)};g.global.Object.defineProperties(r,{_value:{configurable:!0,enumerable:!0,get:function(){return 86}}});g.inherits(t,u);t.prototype.addToBuffer=function(a){if(u.prototype.addToBuffer.call(this,a)){a.add(this.constructorTypes.length);for(var b=g.makeIterator(this.constructorTypes),c=b.next();!c.done;c=b.next()){var d=c.value,c=d.nameBuffer,d=d.type;a.add(c.byteLength);a.addAll(c);d.addToBuffer(a)}}};t.prototype.writeValue=
function(a,b,c){c=void 0===c?!0:c;p.instanceOf(a,z);p.instanceOf(b,Object);for(var d,e=g.makeIterator(this.indexConstructors),f=e.next();!f.done;f=e.next()){var h=g.makeIterator(f.value),f=h.next().value,h=h.next().value;if(b instanceof h){d=f;break}}p.assert(void 0!==d,"No types matched: "+ea.inspect(b));a.add(d);this.constructorTypes[d].type.writeValue(a,b,!1);R(a,c)};g.global.Object.defineProperties(t,{_value:{configurable:!0,enumerable:!0,get:function(){return 88}}});g.inherits(c,u);c.prototype.addToBuffer=
function(a){if(u.prototype.addToBuffer.call(this,a)){var b=qa.get(a);b||(b=new Map,qa.set(a,b));var c=b.get(this.name),d=void 0===c;d&&(c=b.size,b.set(this.name,c));a.addAll(S.makeValueBuffer(c));d&&(b=fa.get(a)||0,fa.set(a,b+1),this.type.addToBuffer(a),fa.set(a,b))}};c.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(a,z);var d=!0,e=ra.get(a);if(e){var f=e.get(b);void 0!==f&&(d=!1,a.add(0),a.addAll(S.makeValueBuffer(a.length-f)))}else e=new Map,ra.set(a,e);d&&(a.add(255),e.set(b,
a.length),this.type.writeValue(a,b,!1));R(a,c)};g.global.Object.defineProperties(c.prototype,{type:{configurable:!0,enumerable:!0,get:function(){ja||(ja=b(a+"/recursive-registry.js"));return ja.getType(this.name)}}});g.global.Object.defineProperties(c,{_value:{configurable:!0,enumerable:!0,get:function(){return 87}}});g.inherits(e,u);e.prototype.addToBuffer=function(a){u.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};e.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(a,
z);null===b||void 0===b?a.add(0):(a.add(255),this.type.writeValue(a,b,!1));R(a,c)};g.global.Object.defineProperties(e,{_value:{configurable:!0,enumerable:!0,get:function(){return 96}}});g.inherits(h,D);h.prototype.addToBuffer=function(a){D.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};h.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;p.instanceOf(a,z);var d=ga.get(a);d||(d=new Map,ga.set(a,d));var e=new z;this.type.writeValue(e,b,!1);b=U.toBinaryString(e.toBuffer());var e=a.length,
f=d.get(b);f?f.add(e):d.set(b,new Set([e]));a.addAll(new ArrayBuffer(4));R(a,c)};g.global.Object.defineProperties(h,{_value:{configurable:!0,enumerable:!0,get:function(){return 112}}});d.exports={Type:D,ByteType:da,ShortType:ca,IntType:ba,LongType:aa,BigIntType:Z,UnsignedByteType:T,UnsignedShortType:X,UnsignedIntType:W,UnsignedLongType:Q,BigUnsignedIntType:k,FlexUnsignedIntType:f,DateType:E,DayType:K,TimeType:y,FloatType:O,DoubleType:L,BooleanType:J,BooleanTupleType:F,BooleanArrayType:M,CharType:q,
StringType:C,OctetsType:w,TupleType:A,StructType:x,ArrayType:v,SetType:I,MapType:l,EnumType:n,ChoiceType:r,NamedChoiceType:t,RecursiveType:c,OptionalType:e,PointerType:h,REPEATED_TYPE:255,MILLIS_PER_DAY:864E5,MILLIS_PER_MINUTE:6E4}}).call(this,"/")},{"/lib/util-inspect.js":"/lib/util-inspect.js","base64-js":2,sha256:5}]},{},[1]);}()