!function(){var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[g]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var g=0;return $jscomp.iteratorPrototype(function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var g=a[Symbol.iterator];return g?g.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var g,b=[];!(g=a.next()).done;)b.push(g.value);return b};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.inherits=function(a,g){function b(){}b.prototype=g.prototype;a.prototype=new b;a.prototype.constructor=a;for(var e in g)if(Object.defineProperties){var k=Object.getOwnPropertyDescriptor(g,e);k&&Object.defineProperty(a,e,k)}else a[e]=g[e]};$jscomp.owns=function(a,g){return Object.prototype.hasOwnProperty.call(a,g)};
$jscomp.polyfill=function(a,g,b,e){if(g){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var k=a[e];k in b||(b[k]={});b=b[k]}a=a[a.length-1];e=b[a];g=g(e);g!=e&&null!=g&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:g})}};
$jscomp.polyfill("WeakMap",function(a){function g(d){$jscomp.owns(d,e)||$jscomp.defineProperty(d,e,{value:{}})}function b(d){var c=Object[d];c&&(Object[d]=function(d){g(d);return c(d)})}if(function(){if(!a||!Object.seal)return!1;try{var d=Object.seal({}),c=Object.seal({}),e=new a([[d,2],[c,3]]);if(2!=e.get(d)||3!=e.get(c))return!1;e.delete(d);e.set(c,4);return!e.has(d)&&4==e.get(c)}catch(l){return!1}}())return a;var e="$jscomp_hidden_"+Math.random().toString().substring(2);b("freeze");b("preventExtensions");
b("seal");var k=0,d=function(d){this.id_=(k+=Math.random()+1).toString();if(d){$jscomp.initSymbol();$jscomp.initSymbolIterator();d=$jscomp.makeIterator(d);for(var c;!(c=d.next()).done;)c=c.value,this.set(c[0],c[1])}};d.prototype.set=function(d,c){g(d);if(!$jscomp.owns(d,e))throw Error("WeakMap key fail: "+d);d[e][this.id_]=c;return this};d.prototype.get=function(d){return $jscomp.owns(d,e)?d[e][this.id_]:void 0};d.prototype.has=function(d){return $jscomp.owns(d,e)&&$jscomp.owns(d[e],this.id_)};d.prototype.delete=
function(d){return $jscomp.owns(d,e)&&$jscomp.owns(d[e],this.id_)?delete d[e][this.id_]:!1};return d},"es6-impl","es3");$jscomp.MapEntry=function(){};$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(a){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a($jscomp.makeIterator([[c,"s"]]));if("s"!=d.get(c)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var l=d.entries(),e=l.next();if(e.done||e.value[0]!=c||"s"!=e.value[1])return!1;e=l.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!l.next().done?!1:!0}catch(u){return!1}}())return a;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var g=new WeakMap,b=function(c){this.data_={};this.head_=d();this.size=0;if(c){c=$jscomp.makeIterator(c);for(var a;!(a=c.next()).done;)a=a.value,this.set(a[0],a[1])}};b.prototype.set=function(c,d){var a=e(this,c);a.list||(a.list=this.data_[a.id]=[]);a.entry?a.entry.value=d:(a.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:c,value:d},a.list.push(a.entry),this.head_.previous.next=a.entry,this.head_.previous=a.entry,this.size++);return this};b.prototype.delete=
function(c){c=e(this,c);return c.entry&&c.list?(c.list.splice(c.index,1),c.list.length||delete this.data_[c.id],c.entry.previous.next=c.entry.next,c.entry.next.previous=c.entry.previous,c.entry.head=null,this.size--,!0):!1};b.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=d();this.size=0};b.prototype.has=function(c){return!!e(this,c).entry};b.prototype.get=function(c){return(c=e(this,c).entry)&&c.value};b.prototype.entries=function(){return k(this,function(c){return[c.key,
c.value]})};b.prototype.keys=function(){return k(this,function(c){return c.key})};b.prototype.values=function(){return k(this,function(c){return c.value})};b.prototype.forEach=function(c,d){for(var a=this.entries(),e;!(e=a.next()).done;)e=e.value,c.call(d,e[1],e[0],this)};b.prototype[Symbol.iterator]=b.prototype.entries;var e=function(c,d){var a;a=d&&typeof d;"object"==a||"function"==a?g.has(d)?a=g.get(d):(a=""+ ++n,g.set(d,a)):a="p_"+d;var e=c.data_[a];if(e&&$jscomp.owns(c.data_,a))for(c=0;c<e.length;c++){var k=
e[c];if(d!==d&&k.key!==k.key||d===k.key)return{id:a,list:e,index:c,entry:k}}return{id:a,list:e,index:-1,entry:void 0}},k=function(c,d){var a=c.head_;return $jscomp.iteratorPrototype(function(){if(a){for(;a.head!=c.head_;)a=a.previous;for(;a.next!=a.head;)return a=a.next,{done:!1,value:d(a)};a=null}return{done:!0,value:void 0}})},d=function(){var c={};return c.previous=c.next=c.head=c},n=0;return b},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(a){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),e=new a($jscomp.makeIterator([b]));if(!e.has(b)||1!=e.size||e.add(b)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var k=e.entries(),d=k.next();if(d.done||d.value[0]!=b||d.value[1]!=b)return!1;d=k.next();return d.done||d.value[0]==b||4!=d.value[0].x||d.value[1]!=d.value[0]?!1:k.next().done}catch(n){return!1}}())return a;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var g=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var e;!(e=a.next()).done;)this.add(e.value)}this.size=this.map_.size};g.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};g.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};g.prototype.clear=function(){this.map_.clear();this.size=0};g.prototype.has=function(a){return this.map_.has(a)};g.prototype.entries=function(){return this.map_.entries()};
g.prototype.values=function(){return this.map_.values()};g.prototype.keys=g.prototype.values;g.prototype[Symbol.iterator]=g.prototype.values;g.prototype.forEach=function(a,e){var k=this;this.map_.forEach(function(d){return a.call(e,d,d,k)})};return g},"es6-impl","es3");$jscomp.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");
$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6-impl","es3");$jscomp.polyfill("Number.isInteger",function(a){return a?a:function(a){return Number.isFinite(a)?a===Math.floor(a):!1}},"es6-impl","es3");$jscomp.polyfill("Number.isSafeInteger",function(a){return a?a:function(a){return Number.isInteger(a)&&Math.abs(a)<=Number.MAX_SAFE_INTEGER}},"es6-impl","es3");
$jscomp.iteratorFromArray=function(a,g){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var b=0,e={next:function(){if(b<a.length){var k=b++;return{value:g(k,a[k]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,b){return[a,b]})}},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,b){return b})}},"es6","es3");$jscomp.checkStringArgs=function(a,g,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(g instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,b){var e=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var k=e.length,d=a.length;b=Math.max(0,Math.min(b|0,e.length));for(var n=0;n<d&&b<k;)if(e[b++]!=a[n++])return!1;return n>=d}},"es6-impl","es3");$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.repeat",function(a){return a?a:function(a){var b=$jscomp.checkStringArgs(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var e="";a;)if(a&1&&(e+=b),a>>>=1)b+=b;return e}},"es6-impl","es3");
require=function e$jscomp$0(g,b,e){function k(c,n){if(!b[c]){if(!g[c]){var l="function"==typeof require&&require;if(!n&&l)return l(c,!0);if(d)return d(c,!0);n=Error("Cannot find module '"+c+"'");throw n.code="MODULE_NOT_FOUND",n;}n=b[c]={exports:{}};g[c][0].call(n.exports,function(d){var e=g[c][1][d];return k(e?e:d)},n,n.exports,e$jscomp$0,g,b,e)}return b[c].exports}for(var d="function"==typeof require&&require,n=0;n<e.length;n++)k(e[n]);return k}({"/client-side/binary-ajax.js":[function(a,g,b){(function(a){a.ajaxTransport("+*",
function(a){if(window.FormData&&("blob"===a.dataType||"arraybuffer"===a.dataType||a.data&&(window.Blob&&a.data instanceof Blob||window.ArrayBuffer&&a.data instanceof ArrayBuffer))){var d;return{send:function(e,c){var k=a.url||location.href,l=a.type||"GET",n=a.dataType||"text",b=a.data||null,g=a.async||!0;d=new XMLHttpRequest;d.addEventListener("load",function(){var a={};200<=d.status&&300>d.status||304===d.status?a[n]=d.response:a.text=d.statusText;c(d.status,d.statusText,a,d.getAllResponseHeaders())});
d.open(l,k,g);d.responseType=n;for(var q in e)({}).hasOwnProperty.call(e,q)&&d.setRequestHeader(q,e[q]);d.send(b)},abort:function(){d&&d.abort()}}}})})(jQuery)},{}],"/client-side/common.js":[function(a,g,b){g=a("../lib/assert");g.instanceOf(window.Map,Function);g.instanceOf(window.Set,Function);g.instanceOf(window.ArrayBuffer,Function);g.instanceOf(window.Uint8Array,Function);g.instanceOf(window.Symbol,Function);a("./binary-ajax");if(!window.sb){window.sb=a("../structure-types");a=a("../recursive-registry");
for(var e in a)({}).hasOwnProperty.call(a,e)&&(window.sb[e]=a[e])}else if(!(window.sb instanceof Object))throw Error("window.sb is already defined");},{"../lib/assert":"/lib/assert.js","../recursive-registry":"/recursive-registry.js","../structure-types":"/structure-types.js","./binary-ajax":"/client-side/binary-ajax.js"}],"/config.js":[function(a,g,b){a=a("base64-js");b=new ArrayBuffer(2);(new DataView(b)).setUint16(0,11);a=a.fromByteArray(new Uint8Array(b));g.exports={VERSION_STRING:a}},{"base64-js":2}],
"/constructor-registry.js":[function(a,g,b){var e=new Map;g.exports={get:function(a){var d=e.get(a);if(d)return d;d={};d=(d[a]=function(){},d)[a];e.set(a,d);return d}}},{}],"/lib/assert.js":[function(a,g,b){var e=a("util"),k=function(){};k.instanceOf=function(a,n){n instanceof Array||(n=[n]);for(var c=!1,d=$jscomp.makeIterator(n),l=d.next();!l.done;l=d.next())if(l=l.value,a instanceof l||void 0!==a&&null!==a&&a.constructor===l){c=!0;break}if(!c)throw new TypeError(e.inspect(a)+" is not an instance of "+
n.map(function(c){return c.name}).join(" or "));};k.integer=function(a){k.instanceOf(a,Number);if(!Number.isSafeInteger(a))throw new RangeError(e.inspect(a)+" is not an integer");};k.between=function(a,n,c,k){if(n<a||n>=c){a=e.inspect(n)+" is not in ["+e.inspect(a)+","+e.inspect(c)+")";if(void 0===k)throw new RangeError(a);throw new RangeError(k+" ("+a+")");}};k.byteUnsignedInteger=function(a){k.integer(a);k.between(0,a,256)};k.fail=function(a){throw Error(a);};k.assert=function(a,e){a||k.fail(e)};
k.throws=function(a,e){var c=!0;try{a(),c=!1}catch(v){void 0!==e&&k.message(v,e)}k.assert(c,"Should throw an error")};k.equal=function(a,n){var c=new RangeError("Expected "+e.inspect(n)+" but got "+e.inspect(a));if(n){var d=!0;switch(n.constructor){case Object:if(!a||a.constructor!==Object)throw c;for(var l in n)if({}.hasOwnProperty.call(n,l))try{k.equal(a[l],n[l])}catch(q){throw c;}break;case Array:if(!a||a.constructor!==Array)throw c;try{k.equal(a.length,n.length)}catch(q){throw c;}for(l=0;l<n.length;l++)try{k.equal(a[l],
n[l])}catch(q){throw c;}break;case Map:if(!a||a.constructor!==Map)throw c;try{k.equal(a.size,n.size)}catch(q){throw c;}l=n.entries();for(var b=a.entries(),u;!(u=l.next()).done;)try{k.equal(u.value,b.next().value)}catch(q){throw c;}break;case Set:if(!a||a.constructor!==Set)throw c;try{k.equal(a.size,n.size)}catch(q){throw c;}l=n.values();for(b=a.values();!(u=l.next()).done;)try{k.equal(u.value,b.next().value)}catch(q){throw c;}break;case ArrayBuffer:if(!a||a.constructor!==ArrayBuffer)throw c;try{k.equal(a.byteLength,
n.byteLength)}catch(q){throw c;}a=new Uint8Array(a);n=new Uint8Array(n);try{for(l=0;l<n.length;l++)k.equal(a[l],n[l])}catch(q){throw c;}break;case Function:if(!a||a.constructor!==Function)throw c;try{k.equal(a.name,n.name)}catch(q){throw c;}break;default:d=!1}if(d)return}if(void 0!==n&&null!==n&&n.equals instanceof Function){var g;try{g=n.equals(a)}catch(q){throw Error("equals() is not implemented for "+e.inspect(n));}if(!g)throw c;}else if(n!==a)throw c;};k.message=function(a,e){k.instanceOf(e,String);
k.assert(a&&a.message.startsWith(e),'Message "'+(a?a.message:"No error thrown")+'" does not start with "'+e+'"')};g.exports=k},{util:9}],"/lib/bit-math.js":[function(a,g,b){g.exports={dividedByEight:function(a){return a>>>3},modEight:function(a){return a&7}}},{}],"/lib/buffer-string.js":[function(a,g,b){var e=a("./assert"),k=a("./growable-buffer");g.exports={toString:function(a){a&&a.constructor===ArrayBuffer&&(a=new Uint8Array(a));e.instanceOf(a,Uint8Array);for(var d=[],c=0;c<a.length;){var k=a[c],
l=void 0,b=239<k?4:223<k?3:191<k?2:1;if(c+b<=a.length){var u,g,q;switch(b){case 1:128>k&&(l=k);break;case 2:u=a[c+1];128===(u&192)&&(k=(k&31)<<6|u&63,127<k&&(l=k));break;case 3:u=a[c+1];g=a[c+2];128===(u&192)&&128===(g&192)&&(k=(k&15)<<12|(u&63)<<6|g&63,2047<k&&(55296>k||57343<k)&&(l=k));break;case 4:u=a[c+1],g=a[c+2],q=a[c+3],128===(u&192)&&128===(g&192)&&128===(q&192)&&(k=(k&15)<<18|(u&63)<<12|(g&63)<<6|q&63,65535<k&&1114112>k&&(l=k))}}void 0===l?(l=65533,b=1):65535<l&&(l-=65536,d.push(l>>>10&1023|
55296),l=56320|l&1023);d.push(l);c+=b}a="";for(c=0;c<d.length;c+=4096)a+=String.fromCharCode.apply(String,[].concat($jscomp.arrayFromIterable(d.slice(c,c+4096))));return a},fromString:function(a){e.instanceOf(a,String);var d=new k;a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())c=c.value.charCodeAt(0),128>c?d.add(c):(2048>c?d.add(192|c>>6):(55296>c||57344<=c?d.add(224|c>>12):(c=65536+((c&1023)<<10|c&1023),d.add(240|c>>18),d.add(128|c>>12&63)),d.add(128|c>>6&63)),d.add(128|c&63));return d.toBuffer()},
toBinaryString:function(a){e.instanceOf(a,ArrayBuffer);var d="";a=new Uint8Array(a);a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())d+=String.fromCharCode(c.value);return d},fromBinaryString:function(a){e.instanceOf(a,String);for(var d=new ArrayBuffer(a.length),c=new Uint8Array(d),k=0;k<a.length;k++)c[k]=a[k].charCodeAt(0);return d}}},{"./assert":"/lib/assert.js","./growable-buffer":"/lib/growable-buffer.js"}],"/lib/flex-int.js":[function(a,g,b){var e=a("./assert"),k=new Map;for(b=
a=0;a<=Number.MAX_SAFE_INTEGER;)k.set(b,a),b++,a+=Math.pow(2,7*b);k.set(b,a);var d=new Map,n=new Map;a=0;b=7;for(var c=$jscomp.makeIterator(k),v=c.next();!v.done;v=c.next()){var v=$jscomp.makeIterator(v.value),l=v.next().value;v.next();l&&(n.set(l,a),d.set(l-1,l),a|=1<<b,b--)}g.exports={makeValueBuffer:function(a){e.integer(a);e.assert(0<=a,String(a)+" is negative");var c;a:{c=$jscomp.makeIterator(k);for(var d=c.next();!d.done;d=c.next()){var d=$jscomp.makeIterator(d.value),l=d.next().value;if(d.next().value>
a){c=l;break a}}c=void 0}l=a-k.get(c-1);a=new ArrayBuffer(c);for(var d=new Uint8Array(a),b=c-1;0<=b;b--)d[b]=l&255,l=Math.floor(l/256);d[0]|=n.get(c);return a},getByteCount:function(a){e.byteUnsignedInteger(a);var c;for(c=0;a&128;c++)a<<=1;a=d.get(c);e.assert(void 0!==a,"Invalid number of bytes");return a},readValueBuffer:function(a){e.instanceOf(a,ArrayBuffer);var c=a.byteLength;e.assert(0<c,"Empty flex int buffer");a=new Uint8Array(a);for(var d=a[0]^n.get(c),l=1;l<c;l++)d*=256,d+=a[l];a=d;return k.get(c-
1)+a}}},{"./assert":"/lib/assert.js"}],"/lib/growable-buffer.js":[function(a,g,b){var e=a("./assert");a=function(a){a=void 0===a?10:a;try{e.integer(a),e.between(0,a,Number.MAX_SAFE_INTEGER+1)}catch(d){throw new RangeError(String(a)+" is not a valid buffer length");}this.buffer=new ArrayBuffer(a);this.size=0};a.prototype.grow=function(a){e.integer(a);a>this.buffer.byteLength&&(a=new ArrayBuffer(a<<1),(new Uint8Array(a)).set((new Uint8Array(this.buffer)).subarray(0,this.size)),this.buffer=a);return this};
a.prototype.set=function(a,d){e.integer(a);e.between(0,a,this.size,"Index out of bounds: "+String(a));e.integer(d);e.between(0,d,256,"Not a byte: "+String(d));(new Uint8Array(this.buffer))[a]=d;return this};a.prototype.setAll=function(a,d){e.instanceOf(d,ArrayBuffer);e.integer(a);e.between(0,a,this.size-d.byteLength+1,"Index out of bounds: "+String(a));(new Uint8Array(this.buffer)).set(new Uint8Array(d),a);return this};a.prototype.get=function(a){e.integer(a);e.between(0,a,this.size,"Index out of bounds: "+
String(a));return(new Uint8Array(this.buffer))[a]};a.prototype.add=function(a){e.integer(a);e.between(0,a,256,"Not a byte: "+String(a));var d=this.size,b=d+1;this.grow(b);this.size=b;(new Uint8Array(this.buffer))[d]=a;return this};a.prototype.addAll=function(a){e.instanceOf(a,ArrayBuffer);var d=this.size,b=this.size+a.byteLength;this.grow(b);this.size=b;(new Uint8Array(this.buffer)).set(new Uint8Array(a),d);return this};a.prototype.toBuffer=function(){return this.buffer.slice(0,this.size)};$jscomp.global.Object.defineProperties(a.prototype,
{length:{configurable:!0,enumerable:!0,get:function(){return this.size}},rawBuffer:{configurable:!0,enumerable:!0,get:function(){return this.buffer}}});g.exports=a},{"./assert":"/lib/assert.js"}],"/lib/strint.js":[function(a,g,b){var e={};(function(){function a(a,c){return f(a)===f(c)}function d(a,c){for(;0<c;)a+="0",c--;return a}function b(a){l(a,"string")}function c(a){b(a);if(!f.call(null,a))throw Error("Condition isPositive failed for value "+a);}function g(a){l(a,"number");if(0>a)throw Error("Expected a positive number: "+
a);}function l(a,c){if(typeof a!==c)throw Error("Not a "+c+": "+a);}var E=e.subPositive=function(a,d){c(a);c(d);if(!x(a,d))throw Error("x must be greater or equal to y");for(var e=Math.max(a.length,d.length),f="",l=0,b=0,w=0;w<e;w++){for(var h=Number(J(a,w))-l,l=0,k=Number(J(d,w));h<k;)h+=10,l++;h=String(h-k);"0"!==h?(f=h+K(f,b),b=0):b++}return 0===f.length?"0":f},u=function(a,d){c(a);c(d);if(A(a,"0")&&A(d,"0"))return"0";for(var e=Math.max(a.length,d.length),f="",l=0,b=0,h=0;h<e;h++){for(var w=Number(J(a,
h)),k=Number(J(d,h)),w=w+k+l,l=0;10<=w;)w-=10,l++;0===w?b++:(f=String(w)+K(f,b),b=0)}0<l&&(f=String(l)+K(f,b));return f},C=e.add=function(a,c){b(a);b(c);if(f(a)&&f(c))return u(a,c);if(t(a)&&t(c))return h(u(y(a),y(c)));if(B(y(a),y(c))){var d=a;a=c;c=d}c=E(y(a),y(c));return f(a)?c:h(c)},q=e.sub=function(a,c){b(a);b(c);return C(a,h(c))},G=e.timesDigit=function(a,d){c(a);l(d,"number");for(var e="",f=M(a),b=0,w=0,h=0;h<f;h++){for(var k=Number(J(a,h))*d+b,b=0;10<=k;)k-=10,b++;0===k?w++:(e=String(k)+K(e,
w),w=0)}0<b&&(e=String(b)+K(e,w));return 0===e.length?"0":e},r=e.mulPositive=function(a,e){c(a);c(e);for(var f="0",l=M(e),b=0;b<l;b++)var w=G(a,Number(J(e,b))),w=d(w,b),f=u(f,w);return f},p=e.mul=function(c,d){b(c);b(d);if(A(c,"0")||A(d,"0"))return"0";var e=r(y(c),y(d));return a(c,d)?e:h(e)},D=e.quotientRemainderPositive=function(a,e){c(a);c(e);if(A(a,e))return["1","0"];if(w(e,a))return["0",H(a)];for(var f="0",b=a.length-e.length;;){for(var l=a.slice(0,a.length-b);x(l,e);)l=q(l,e),f=C(f,"1");a=l+
a.slice(a.length-b);if(w(e,a))return f=d(f,b),[f,H(a)];b--;f=d(f,1);if(0>b)throw Error("Illegal state");}};e.div=function(c,e,d){d=void 0===d?!1:d;b(c);b(e);var f=D(y(c),y(e))[0];a(c,e)||(f=h(f));!d||A(p(f,e),c)||a(c,e)||(f=q(f,"1"));return f};var A=e.eq=function(a,c){return H(a)===H(c)},z=function(a,c){if(t(a)||t(c))throw Error("Both operands must be positive: "+a+" "+c);var e=Math.max(a.length,c.length);a=F(a,e);c=F(c,e);return a<c},B=e.lt=function(a,c){return t(a)&&f(c)?!0:f(a)&&t(c)?!1:t(a)&&
t(c)?!A(a,c)&&!z(y(a),y(c)):z(a,c)},x=e.ge=function(a,c){return!B(a,c)},w=e.gt=function(a,c){return A(a,c)?!1:x(a,c)},t=e.isNegative=function(a){b(a);return 0===a.indexOf("-")},f=e.isPositive=function(a){return!t(a)},y=e.abs=function(a){return t(a)?h(a):a},h=e.negate=function(a){return"0"===a?"0":t(a)?a.slice(1):"-"+a},m=/^(-?)0*([1-9][0-9]*)$/,L=/^0+$/,H=e.normalize=function(a){if(L.test(a))return"0";var c=m.exec(a);if(!c)throw Error("Illegal strint format: "+a);return c[1]+c[2]},F=function(a,e){c(a);
g(e);return K(a,e-a.length)},K=function(a,e){c(a);g(e);for(var d=0;d<e;d++)a="0"+a;return a},J=function(a,c){b(a);l(c,"number");return c>=M(a)?"0":a.charAt(a.length-c-1)},M=function(a){return t(a)?a.length-1:a.length}})();e.LONG_UPPER_SHIFT="4294967296";e.BYTE_SHIFT="256";g.exports=e},{}],1:[function(a,g,b){(function(){function e(){var a={},e;for(e in c)a[e]={sig:c[e].sig,type:d.fromByteArray(new Uint8Array(c[e].type.toBuffer()))};localStorage.typeCache=JSON.stringify(a)}a("./common");var b=a("../lib/assert"),
d=a("base64-js"),n=a("../read"),c={};if(localStorage.typeCache){var g=JSON.parse(localStorage.typeCache),l;for(l in g)c[l]={sig:g[l].sig,type:n.type((new Uint8Array(d.toByteArray(g[l].type))).buffer)}}else e();sb.download=function(a,d){function l(a,c,e){if(g){g instanceof Array||(g=[g]);for(var d=$jscomp.makeIterator(g),b=d.next();!b.done;b=d.next())b=b.value,b(a,c,e)}}b.instanceOf(a,String);b.instanceOf(d,Object);d.dataType="arraybuffer";var k;c[a]?(k=!0,d.headers||(d.headers={}),d.headers.sig=c[a].sig):
k=!1;var g=d.success;d.success=function(d,b,g){var p=g.getResponseHeader("sig");if(k&&c[a].sig===p)p=n.value({buffer:d,type:c[a].type}),l(p,b,g);else{var u=n._consumeType(d,0);d=n.value({buffer:d,offset:u.length,type:u.value});c[a]={sig:p,type:u.value};e();l(d,b,g)}};$.ajax(d)}})()},{"../lib/assert":"/lib/assert.js","../read":"/read.js","./common":"/client-side/common.js","base64-js":2}],2:[function(a,g,b){function e(a){var c=a.length;if(0<c%4)throw Error("Invalid string. Length must be a multiple of 4");
return"="===a[c-2]?2:"="===a[c-1]?1:0}function k(a,c,e){for(var b=[],l=c;l<e;l+=3)c=(a[l]<<16)+(a[l+1]<<8)+a[l+2],b.push(d[c>>18&63]+d[c>>12&63]+d[c>>6&63]+d[c&63]);return b.join("")}b.byteLength=function(a){return 3*a.length/4-e(a)};b.toByteArray=function(a){var d,b,k,g,q;d=a.length;g=e(a);q=new c(3*d/4-g);b=0<g?d-4:d;var v=0;for(d=0;d<b;d+=4)k=n[a.charCodeAt(d)]<<18|n[a.charCodeAt(d+1)]<<12|n[a.charCodeAt(d+2)]<<6|n[a.charCodeAt(d+3)],q[v++]=k>>16&255,q[v++]=k>>8&255,q[v++]=k&255;2===g?(k=n[a.charCodeAt(d)]<<
2|n[a.charCodeAt(d+1)]>>4,q[v++]=k&255):1===g&&(k=n[a.charCodeAt(d)]<<10|n[a.charCodeAt(d+1)]<<4|n[a.charCodeAt(d+2)]>>2,q[v++]=k>>8&255,q[v++]=k&255);return q};b.fromByteArray=function(a){for(var c=a.length,e=c%3,b="",g=[],n=0,v=c-e;n<v;n+=16383)g.push(k(a,n,n+16383>v?v:n+16383));1===e?(a=a[c-1],b+=d[a>>2],b+=d[a<<4&63],b+="=="):2===e&&(a=(a[c-2]<<8)+a[c-1],b+=d[a>>10],b+=d[a>>4&63],b+=d[a<<2&63],b+="=");g.push(b);return g.join("")};var d=[],n=[],c="undefined"!==typeof Uint8Array?Uint8Array:Array;
for(a=0;64>a;++a)d[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[a],n["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(a)]=a;n[45]=62;n[95]=63},{}],3:[function(a,g,b){!function(a){function e(a){return a.map(function(a){a=a.toString(16);a=2<a.length?a:Array(2-a.length+1).join("0")+a;return a}).join("")}var d={bytesToHex:function(a){return e(a)},hexToBytes:function(a){if(1===a.length%2)throw Error("hexToBytes can't have a string with an odd number of characters.");
0===a.indexOf("0x")&&(a=a.slice(2));return a.match(/../g).map(function(a){return parseInt(a,16)})}};"undefined"!==typeof g&&g.exports?g.exports=d:a.convertHex=d}(this)},{}],4:[function(a,g,b){!function(a){var e={bytesToString:function(a){return a.map(function(a){return String.fromCharCode(a)}).join("")},stringToBytes:function(a){return a.split("").map(function(a){return a.charCodeAt(0)})},UTF8:{bytesToString:function(a){return decodeURIComponent(escape(e.bytesToString(a)))},stringToBytes:function(a){return e.stringToBytes(unescape(encodeURIComponent(a)))}}};
"undefined"!==typeof g&&g.exports?g.exports=e:a.convertString=e}(this)},{}],5:[function(a,g,b){g.exports="function"===typeof Object.create?function(a,b){a.super_=b;a.prototype=Object.create(b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}})}:function(a,b){a.super_=b;var d=function(){};d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a}},{}],6:[function(a,g,b){function e(){throw Error("setTimeout has not been defined");}function k(){throw Error("clearTimeout has not been defined");
}function d(a){if(u===setTimeout)return setTimeout(a,0);if((u===e||!u)&&setTimeout)return u=setTimeout,setTimeout(a,0);try{return u(a,0)}catch(A){try{return u.call(null,a,0)}catch(z){return u.call(this,a,0)}}}function n(a){if(C===clearTimeout)return clearTimeout(a);if((C===k||!C)&&clearTimeout)return C=clearTimeout,clearTimeout(a);try{return C(a)}catch(A){try{return C.call(null,a)}catch(z){return C.call(this,a)}}}function c(){G&&r&&(G=!1,r.length?q=r.concat(q):p=-1,q.length&&v())}function v(){if(!G){var a=
d(c);G=!0;for(var e=q.length;e;){r=q;for(q=[];++p<e;)r&&r[p].run();p=-1;e=q.length}r=null;G=!1;n(a)}}function l(a,c){this.fun=a;this.array=c}function E(){}a=g.exports={};var u,C;try{u="function"===typeof setTimeout?setTimeout:e}catch(D){u=e}try{C="function"===typeof clearTimeout?clearTimeout:k}catch(D){C=k}var q=[],G=!1,r,p=-1;a.nextTick=function(a){var c=Array(arguments.length-1);if(1<arguments.length)for(var e=1;e<arguments.length;e++)c[e-1]=arguments[e];q.push(new l(a,c));1!==q.length||G||d(v)};
l.prototype.run=function(){this.fun.apply(null,this.array)};a.title="browser";a.browser=!0;a.env={};a.argv=[];a.version="";a.versions={};a.on=E;a.addListener=E;a.once=E;a.off=E;a.removeListener=E;a.removeAllListeners=E;a.emit=E;a.binding=function(a){throw Error("process.binding is not supported");};a.cwd=function(){return"/"};a.chdir=function(a){throw Error("process.chdir is not supported");};a.umask=function(){return 0}},{}],7:[function(a,g,b){!function(e){function b(a,e){a.constructor===String&&
(a=d.convertString.UTF8.stringToBytes(a));for(var b=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225],l=a,k=[],g=0,v=0;g<l.length;g++,v+=8)k[v>>>5]|=l[g]<<24-v%32;a=8*a.length;k[a>>5]|=128<<24-a%32;k[(a+64>>9<<4)+15]=a;for(a=0;a<k.length;a+=16){for(var l=b,g=k,v=a,r=l[0],p=l[1],D=l[2],A=l[3],z=l[4],B=l[5],x=l[6],w=l[7],t=0;64>t;t++){if(16>t)c[t]=g[v+t]|0;else{var f=c[t-15],y=c[t-2];c[t]=((f<<25|f>>>7)^(f<<14|f>>>18)^f>>>3)+c[t-7]+((y<<15|y>>>17)^(y<<13|y>>>19)^
y>>>10)+c[t-16]}f=w+((z<<26|z>>>6)^(z<<21|z>>>11)^(z<<7|z>>>25))+(z&B^~z&x)+n[t]+c[t];y=((r<<30|r>>>2)^(r<<19|r>>>13)^(r<<10|r>>>22))+(r&p^r&D^p&D);w=x;x=B;B=z;z=A+f|0;A=D;D=p;p=r;r=f+y|0}l[0]=l[0]+r|0;l[1]=l[1]+p|0;l[2]=l[2]+D|0;l[3]=l[3]+A|0;l[4]=l[4]+z|0;l[5]=l[5]+B|0;l[6]=l[6]+x|0;l[7]=l[7]+w|0}k=[];for(a=0;a<32*b.length;a+=8)k.push(b[a>>>5]>>>24-a%32&255);return e&&e.asBytes?k:e&&e.asString?d.convertString.bytesToString(k):d.bytesToHex(k)}var d={};"undefined"!==typeof g&&g.exports?(d.bytesToHex=
a("convert-hex").bytesToHex,d.convertString=a("convert-string"),g.exports=b):(d.bytesToHex=e.convertHex.bytesToHex,d.convertString=e.convertString,e.sha256=b);var n=[];!function(){function a(a){for(var c=Math.sqrt(a),e=2;e<=c;e++)if(!(a%e))return!1;return!0}function c(a){return 4294967296*(a-(a|0))|0}for(var e=2,d=0;64>d;)a(e)&&(n[d]=c(Math.pow(e,1/3)),d++),e++}();var c=[];b.x2=function(a,c){return b(b(a,{asBytes:!0}),c)}}(this)},{"convert-hex":3,"convert-string":4}],8:[function(a,g,b){g.exports=
function(a){return a&&"object"===typeof a&&"function"===typeof a.copy&&"function"===typeof a.fill&&"function"===typeof a.readUInt8}},{}],9:[function(a,g,b){(function(e,k){function d(a,e){var d={seen:[],stylize:c};3<=arguments.length&&(d.depth=arguments[2]);4<=arguments.length&&(d.colors=arguments[3]);p(e)?d.showHidden=e:e&&b._extend(d,e);z(d.showHidden)&&(d.showHidden=!1);z(d.depth)&&(d.depth=2);z(d.colors)&&(d.colors=!1);z(d.customInspect)&&(d.customInspect=!0);d.colors&&(d.stylize=g);return l(d,
a,d.depth)}function g(a,c){return(c=d.styles[c])?"\u001b["+d.colors[c][0]+"m"+a+"\u001b["+d.colors[c][1]+"m":a}function c(a,c){return a}function v(a){var c={};a.forEach(function(a,d){c[a]=!0});return c}function l(a,c,d){if(a.customInspect&&c&&f(c.inspect)&&c.inspect!==b.inspect&&(!c.constructor||c.constructor.prototype!==c)){var e=c.inspect(d,a);A(e)||(e=l(a,e,d));return e}if(e=E(a,c))return e;var h=Object.keys(c),k=v(h);a.showHidden&&(h=Object.getOwnPropertyNames(c));if(t(c)&&(0<=h.indexOf("message")||
0<=h.indexOf("description")))return u(c);if(0===h.length){if(f(c))return a.stylize("[Function"+(c.name?": "+c.name:"")+"]","special");if(B(c))return a.stylize(RegExp.prototype.toString.call(c),"regexp");if(w(c))return a.stylize(Date.prototype.toString.call(c),"date");if(t(c))return u(c)}var e="",g=!1,x=["{","}"];r(c)&&(g=!0,x=["[","]"]);f(c)&&(e=" [Function"+(c.name?": "+c.name:"")+"]");B(c)&&(e=" "+RegExp.prototype.toString.call(c));w(c)&&(e=" "+Date.prototype.toUTCString.call(c));t(c)&&(e=" "+u(c));
if(0===h.length&&(!g||0==c.length))return x[0]+e+x[1];if(0>d)return B(c)?a.stylize(RegExp.prototype.toString.call(c),"regexp"):a.stylize("[Object]","special");a.seen.push(c);h=g?C(a,c,d,k,h):h.map(function(e){return q(a,c,d,k,e,g)});a.seen.pop();return G(h,e,x)}function E(a,c){if(z(c))return a.stylize("undefined","undefined");if(A(c))return c="'"+JSON.stringify(c).replace(/^"|"$/g,"").replace(/'/g,"\\'").replace(/\\"/g,'"')+"'",a.stylize(c,"string");if(D(c))return a.stylize(""+c,"number");if(p(c))return a.stylize(""+
c,"boolean");if(null===c)return a.stylize("null","null")}function u(a){return"["+Error.prototype.toString.call(a)+"]"}function C(a,c,d,e,b){for(var f=[],l=0,h=c.length;l<h;++l)Object.prototype.hasOwnProperty.call(c,String(l))?f.push(q(a,c,d,e,String(l),!0)):f.push("");b.forEach(function(b){b.match(/^\d+$/)||f.push(q(a,c,d,e,b,!0))});return f}function q(a,c,d,e,b,f){var h,w;c=Object.getOwnPropertyDescriptor(c,b)||{value:c[b]};c.get?w=c.set?a.stylize("[Getter/Setter]","special"):a.stylize("[Getter]",
"special"):c.set&&(w=a.stylize("[Setter]","special"));Object.prototype.hasOwnProperty.call(e,b)||(h="["+b+"]");w||(0>a.seen.indexOf(c.value)?(w=null===d?l(a,c.value,null):l(a,c.value,d-1),-1<w.indexOf("\n")&&(w=f?w.split("\n").map(function(a){return"  "+a}).join("\n").substr(2):"\n"+w.split("\n").map(function(a){return"   "+a}).join("\n"))):w=a.stylize("[Circular]","special"));if(z(h)){if(f&&b.match(/^\d+$/))return w;h=JSON.stringify(""+b);h.match(/^"([a-zA-Z_][a-zA-Z_0-9]*)"$/)?(h=h.substr(1,h.length-
2),h=a.stylize(h,"name")):(h=h.replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'"),h=a.stylize(h,"string"))}return h+": "+w}function G(a,c,d){var e=0;return 60<a.reduce(function(a,c){e++;0<=c.indexOf("\n")&&e++;return a+c.replace(/\u001b\[\d\d?m/g,"").length+1},0)?d[0]+(""===c?"":c+"\n ")+" "+a.join(",\n  ")+" "+d[1]:d[0]+c+" "+a.join(", ")+" "+d[1]}function r(a){return Array.isArray(a)}function p(a){return"boolean"===typeof a}function D(a){return"number"===typeof a}function A(a){return"string"===
typeof a}function z(a){return void 0===a}function B(a){return x(a)&&"[object RegExp]"===Object.prototype.toString.call(a)}function x(a){return"object"===typeof a&&null!==a}function w(a){return x(a)&&"[object Date]"===Object.prototype.toString.call(a)}function t(a){return x(a)&&("[object Error]"===Object.prototype.toString.call(a)||a instanceof Error)}function f(a){return"function"===typeof a}function y(a){return 10>a?"0"+a.toString(10):a.toString(10)}function h(){var a=new Date,c=[y(a.getHours()),
y(a.getMinutes()),y(a.getSeconds())].join(":");return[a.getDate(),F[a.getMonth()],c].join(" ")}var m=/%[sdj%]/g;b.format=function(a){if(!A(a)){for(var c=[],e=0;e<arguments.length;e++)c.push(d(arguments[e]));return c.join(" ")}for(var e=1,b=arguments,f=b.length,c=String(a).replace(m,function(a){if("%%"===a)return"%";if(e>=f)return a;switch(a){case "%s":return String(b[e++]);case "%d":return Number(b[e++]);case "%j":try{return JSON.stringify(b[e++])}catch(R){return"[Circular]"}default:return a}}),h=
b[e];e<f;h=b[++e])c=null!==h&&x(h)?c+(" "+d(h)):c+(" "+h);return c};b.deprecate=function(a,c){if(z(k.process))return function(){return b.deprecate(a,c).apply(this,arguments)};if(!0===e.noDeprecation)return a;var d=!1;return function(){if(!d){if(e.throwDeprecation)throw Error(c);e.traceDeprecation?console.trace(c):console.error(c);d=!0}return a.apply(this,arguments)}};var L={},H;b.debuglog=function(a){z(H)&&(H=e.env.NODE_DEBUG||"");a=a.toUpperCase();if(!L[a])if((new RegExp("\\b"+a+"\\b","i")).test(H)){var c=
e.pid;L[a]=function(){var e=b.format.apply(b,arguments);console.error("%s %d: %s",a,c,e)}}else L[a]=function(){};return L[a]};b.inspect=d;d.colors={bold:[1,22],italic:[3,23],underline:[4,24],inverse:[7,27],white:[37,39],grey:[90,39],black:[30,39],blue:[34,39],cyan:[36,39],green:[32,39],magenta:[35,39],red:[31,39],yellow:[33,39]};d.styles={special:"cyan",number:"yellow","boolean":"yellow",undefined:"grey","null":"bold",string:"green",date:"magenta",regexp:"red"};b.isArray=r;b.isBoolean=p;b.isNull=
function(a){return null===a};b.isNullOrUndefined=function(a){return null==a};b.isNumber=D;b.isString=A;b.isSymbol=function(a){return"symbol"===typeof a};b.isUndefined=z;b.isRegExp=B;b.isObject=x;b.isDate=w;b.isError=t;b.isFunction=f;b.isPrimitive=function(a){return null===a||"boolean"===typeof a||"number"===typeof a||"string"===typeof a||"symbol"===typeof a||"undefined"===typeof a};b.isBuffer=a("./support/isBuffer");var F="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");b.log=function(){console.log("%s - %s",
h(),b.format.apply(b,arguments))};b.inherits=a("inherits");b._extend=function(a,c){if(!c||!x(c))return a;for(var e=Object.keys(c),d=e.length;d--;)a[e[d]]=c[e[d]];return a}}).call(this,a("_process"),"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"./support/isBuffer":8,_process:6,inherits:5}],"/read.js":[function(a,g,b){function e(a,c){l.assert(a.byteLength>c,"Buffer is not long enough");var e=q.getByteCount((new Uint8Array(a))[c]);l.assert(a.byteLength>=
c+e,"Buffer is not long enough");return{value:q.readValueBuffer(a.slice(c,c+e)),length:e}}function k(a,c){return a.length<c?"0".repeat(c-a.length)+a:a}function d(a,c){switch(a.constructor){case p.ArrayType:return Array(c);case p.TupleType:return Array(a.length);case p.MapType:return new Map;case p.SetType:return new Set;case p.StructType:return{};default:l.fail("Invalid type for base value: "+D.inspect(a))}}function n(a){var c=a.buffer,e=a.offset,d=a.count;a=a.baseValue||Array(d);var d=E.modEight(a.length),
b=E.dividedByEight(a.length),d=d?b+1:b;l.assert(c.byteLength>=e+d,"Buffer is not long enough");c=new Uint8Array(c);for(b=0;b<d;b++)for(var h=c[e+b],k=0;8>k;k++){var g=8*b+k;if(g===a.length)break;a[g]=!!(h&1<<E.modEight(~E.modEight(k)))}return{value:a,length:d}}function c(a){var b=a.buffer,k=a.pointerStart,f=a.offset,g=a.type;a=a.baseValue;var h,m;switch(g.constructor){case p.ByteType:m=1;l.assert(b.byteLength>=f+m,"Buffer is not long enough");h=(new Int8Array(b))[f];break;case p.ShortType:m=2;l.assert(b.byteLength>=
f+m,"Buffer is not long enough");h=(new DataView(b)).getInt16(f);break;case p.IntType:m=4;h=(new DataView(b)).getInt32(f);break;case p.LongType:case p.DateType:m=8;l.assert(b.byteLength>=f+m,"Buffer is not long enough");h=new DataView(b);b=h.getInt32(f);f=h.getUint32(f+4);h=r.add(r.mul(String(b),r.LONG_UPPER_SHIFT),String(f));g.constructor===p.DateType&&(h=new Date(Number(h)));break;case p.BigIntType:m=e(b,f);k=m.value;m=m.length;l.assert(b.byteLength>=f+m+k,"Buffer is not long enough");b=new DataView(b);
h=k?String(b.getInt8(f+m)):"0";for(g=1;g<k;g++)g&&(h=r.mul(h,r.BYTE_SHIFT)),h=r.add(h,String(b.getUint8(f+m+g)));m+=k;break;case p.UnsignedByteType:m=1;l.assert(b.byteLength>f,"Buffer is not long enough");h=(new Uint8Array(b))[f];break;case p.UnsignedShortType:m=2;l.assert(b.byteLength>=f+m,"Buffer is not long enough");h=(new DataView(b)).getUint16(f);break;case p.UnsignedIntType:m=4;l.assert(b.byteLength>=f+m,"Buffer is not long enough");h=(new DataView(b)).getUint32(f);break;case p.UnsignedLongType:m=
8;l.assert(b.byteLength>=f+m,"Buffer is not long enough");h=new DataView(b);b=h.getUint32(f);f=h.getUint32(f+4);h=r.add(r.mul(String(b),r.LONG_UPPER_SHIFT),String(f));break;case p.BigUnsignedIntType:m=e(b,f);k=m.value;m=m.length;l.assert(b.byteLength>=f+m+k,"Buffer is not long enough");b=new DataView(b);h="0";for(g=0;g<k;g++)g&&(h=r.mul(h,r.BYTE_SHIFT)),h=r.add(h,String(b.getUint8(f+m+g)));m+=k;break;case p.FlexUnsignedIntType:m=e(b,f);h=m.value;m=m.length;break;case p.DayType:m=3;l.assert(b.byteLength>=
f+m,"Buffer is not long enough");b=new DataView(b);f=(b.getInt16(f)<<8|b.getUint8(f+2))*p.MILLIS_PER_DAY;h=new Date(f+(new Date(f)).getTimezoneOffset()*p.MILLIS_PER_MINUTE);break;case p.TimeType:m=4;l.assert(b.byteLength>=f+m,"Buffer is not long enough");h=new Date((new DataView(b)).getUint32(f));break;case p.FloatType:m=4;l.assert(b.byteLength>=f+m,"Buffer is not long enough");h=(new DataView(b)).getFloat32(f);break;case p.DoubleType:m=8;l.assert(b.byteLength>=f+m,"Buffer is not long enough");h=
(new DataView(b)).getFloat64(f);break;case p.BooleanType:m=1;l.assert(b.byteLength>f,"Buffer is not long enough");f=(new Uint8Array(b))[f];l.assert(0===f||255===f,"0x"+f.toString(16)+" is an invalid Boolean value");h=!!f;break;case p.BooleanArrayType:h=e(b,f);m=h.length;f=n({buffer:b,offset:f+m,count:h.value,baseValue:a});m+=f.length;h=f.value;break;case p.BooleanTupleType:m=n({buffer:b,offset:f,count:g.length,baseValue:a});h=m.value;m=m.length;break;case p.CharType:l.assert(b.byteLength>f,"Buffer is not long enough");
h=u.toString((new Uint8Array(b)).subarray(f,f+4))[0];m=u.fromString(h).byteLength;break;case p.StringType:h=new Uint8Array(b);for(m=0;l.assert(b.byteLength>f+m,"Buffer is not long enough"),h[f+m];m++);h=u.toString((new Uint8Array(b)).subarray(f,f+m));m++;break;case p.OctetsType:h=e(b,f);m=h.length;k=m+h.value;l.assert(b.byteLength>=f+k,"Buffer is not long enough");h=b.slice(f+m,f+k);m=k;break;case p.TupleType:m=0;h=a||d(g);for(a=0;a<g.length;a++){var x=c({buffer:b,pointerStart:k,offset:f+m,type:g.type});
m+=x.length;h[a]=x.value}break;case p.StructType:m=0;h=a||d(g);g=$jscomp.makeIterator(g.fields);for(a=g.next();!a.done;a=g.next())a=a.value,x=c({buffer:b,pointerStart:k,offset:f+m,type:a.type}),h[a.name]=x.value,m+=x.length;break;case p.ArrayType:m=e(b,f);x=m.value;m=m.length;h=a||d(g,x);for(a=0;a<x;a++){var q=c({buffer:b,pointerStart:k,offset:f+m,type:g.type});m+=q.length;h[a]=q.value}break;case p.SetType:x=e(b,f);m=x.length;h=a||d(g);for(a=0;a<x.value;a++)q=c({buffer:b,pointerStart:k,offset:f+m,
type:g.type}),m+=q.length,h.add(q.value);break;case p.MapType:x=e(b,f);m=x.length;h=a||d(g);for(a=0;a<x.value;a++){q=c({buffer:b,pointerStart:k,offset:f+m,type:g.keyType});m+=q.length;var v=c({buffer:b,pointerStart:k,offset:f+m,type:g.valueType});m+=v.length;h.set(q.value,v.value)}break;case p.EnumType:m=1;l.assert(b.byteLength>f,"Buffer is not long enough");f=(new Uint8Array(b))[f];h=g.values[f];void 0===h&&l.fail("Index "+String(f)+" is invalid");break;case p.ChoiceType:m=1;l.assert(b.byteLength>
f,"Buffer is not long enough");h=(new Uint8Array(b))[f];f=c({buffer:b,pointerStart:k,offset:f+m,type:g.types[h]});m+=f.length;h=f.value;break;case p.NamedChoiceType:m=1;l.assert(b.byteLength>f,"Buffer is not long enough");h=(new Uint8Array(b))[f];a=g.indexConstructors.get(h).name;a=C.get(a);f=c({buffer:b,pointerStart:k,offset:f+m,type:g.constructorTypes[h].type,baseValue:new a});m+=f.length;h=f.value;break;case p.RecursiveType:m=1;l.assert(b.byteLength>f,"Buffer is not long enough");h=(new Uint8Array(b))[f];
l.assert(0===h||255===h,"0x"+h.toString(16)+" is an invalid Recursive byte");h?(g=g.type,h=d(g),z.has(b)||z.set(b,new Map),z.get(b).set(f+m,h),m+=c({buffer:b,pointerStart:k,offset:f+m,type:g,baseValue:h}).length):(k=e(b,f+m),f=f+m-k.value,h=z.get(b).get(f),l.assert(void 0!==h,"Cannot find target at "+String(f)),m+=k.length);break;case p.OptionalType:m=1;l.assert(b.byteLength>f,"Buffer is not long enough");h=(new Uint8Array(b))[f];l.assert(0===h||255===h,"0x"+h.toString(16)+" is an invalid Optional byte");
h?(f=c({buffer:b,pointerStart:k,offset:f+m,type:g.type}),m+=f.length,h=f.value):h=null;break;case p.PointerType:m=4;l.assert(b.byteLength>=f+m,"Buffer is not long enough");f=(new DataView(b)).getUint32(f);h=c({buffer:b,pointerStart:k,offset:k+f,type:g.type}).value;break;default:l.fail("Not a structure type: "+D.inspect(g))}return{value:h,length:m}}function v(a,b){l.assert(0<=b,"Offset is negative: "+String(b));var d=new Uint8Array(a);l.assert(a.byteLength>b,"Buffer is not long enough");var f=d[b],
g,h=1,m=A.get(f);if(void 0!==m)return{value:new m,length:h};switch(f){case p.BooleanTupleType._value:l.assert(a.byteLength>b+h,"Buffer is not long enough");a=d[b+h];h++;g=new p.BooleanTupleType(a);break;case p.TupleType._value:var n=v(a,b+h),h=h+n.length;l.assert(a.byteLength>b+h,"Buffer is not long enough");a=d[b+h];h++;g=new p.TupleType({type:n.value,length:a});break;case p.StructType._value:l.assert(a.byteLength>b+h,"Buffer is not long enough");n=d[b+h];h++;g={};for(f=0;f<n;f++){l.assert(a.byteLength>
b+h,"Buffer is not long enough");m=d[b+h];h++;var q=b+h,r=q+m;l.assert(a.byteLength>=r,"Buffer is not long enough");q=u.toString(d.subarray(q,r));h+=m;m=v(a,r);g[q]=m.value;h+=m.length}g=new p.StructType(g);break;case p.ArrayType._value:a=v(a,b+h);h+=a.length;g=new p.ArrayType(a.value);break;case p.SetType._value:a=v(a,b+h);h+=a.length;g=new p.SetType(a.value);break;case p.MapType._value:d=v(a,b+h);h+=d.length;a=v(a,b+h);h+=a.length;g=new p.MapType(d.value,a.value);break;case p.EnumType._value:d=
v(a,b+h);h+=d.length;l.assert(a.byteLength>b+h,"Buffer is not long enough");n=(new Uint8Array(a))[b+h];h++;g=Array(n);for(f=0;f<n;f++)m=b+h,m=c({buffer:a,pointerStart:m,offset:m,type:d.value}),h+=m.length,g[f]=m.value;g=new p.EnumType({type:d.value,values:g});break;case p.ChoiceType._value:l.assert(a.byteLength>b+h,"Buffer is not long enough");d=(new Uint8Array(a))[b+h];h++;n=Array(d);for(g=0;g<d;g++)f=v(a,b+h),n[g]=f.value,h+=f.length;g=new p.ChoiceType(n);break;case p.NamedChoiceType._value:l.assert(a.byteLength>
b+h,"Buffer is not long enough");n=d[b+h];h++;g=new Map;for(f=0;f<n;f++)l.assert(a.byteLength>b+h,"Buffer is not long enough"),m=d[b+h],h++,q=b+h,r=q+m,l.assert(a.byteLength>=r,"Buffer is not long enough"),q=u.toString(d.subarray(q,r)),h+=m,m=v(a,r),g.set(C.get(q),m.value),h+=m.length;g=new p.NamedChoiceType(g);break;case p.RecursiveType._value:g=e(a,b+h);d=g.value;h+=g.length;(g=B.get(a))?n=g.get(d):(g=new Map,B.set(a,g));if(!n){do for(n="read-type",f=0;16>f;f++)n+=Math.floor(16*Math.random()).toString(16);
while(G.isRegistered(n));g.set(d,n);a=v(a,b+h);h+=a.length;G.registerType({type:a.value,name:n})}g=new p.RecursiveType(n);break;case p.OptionalType._value:a=v(a,b+h);h+=a.length;g=new p.OptionalType(a.value);break;case p.PointerType._value:a=v(a,b+h);h+=a.length;g=new p.PointerType(a.value);break;case p.REPEATED_TYPE:d=e(a,b+h);g=v(a,b+h-d.value).value;h+=d.length;break;default:l.fail("No such type: 0x"+k((new Uint8Array(a))[b].toString(16),2))}return{value:g,length:h}}var l=a("./lib/assert"),E=a("./lib/bit-math"),
u=a("./lib/buffer-string"),C=a("./constructor-registry"),q=a("./lib/flex-int"),G=a("./recursive-registry"),r=a("./lib/strint"),p=a("./structure-types"),D=a("util");a=new Set([p.ByteType,p.ShortType,p.IntType,p.LongType,p.BigIntType,p.UnsignedByteType,p.UnsignedShortType,p.UnsignedIntType,p.UnsignedLongType,p.BigUnsignedIntType,p.FlexUnsignedIntType,p.DateType,p.DayType,p.TimeType,p.FloatType,p.DoubleType,p.BooleanType,p.BooleanArrayType,p.CharType,p.StringType,p.OctetsType]);var A=new Map;a=$jscomp.makeIterator(a);
for(b=a.next();!b.done;b=a.next())b=b.value,A.set(b._value,b);var z=new WeakMap,B=new WeakMap;g.exports={_consumeType:v,type:function(a,c){c=void 0===c?!0:c;l.instanceOf(a,ArrayBuffer);var b=v(a,0),d=b.value,b=b.length;c&&l.assert(b===a.byteLength,"Did not consume all of the buffer");return d},value:function(a){var b=a.buffer,d=a.type;a=void 0===a.offset?0:a.offset;l.instanceOf(b,ArrayBuffer);l.instanceOf(d,p.Type);l.instanceOf(a,Number);return c({buffer:b,offset:a,type:d,pointerStart:a}).value}}},
{"./constructor-registry":"/constructor-registry.js","./lib/assert":"/lib/assert.js","./lib/bit-math":"/lib/bit-math.js","./lib/buffer-string":"/lib/buffer-string.js","./lib/flex-int":"/lib/flex-int.js","./lib/strint":"/lib/strint.js","./recursive-registry":"/recursive-registry.js","./structure-types":"/structure-types.js",util:9}],"/recursive-registry.js":[function(a,g,b){var e=a("./lib/assert"),k=a("./structure-types"),d=new Map;g.exports={registerType:function(a){var c=a.type;a=a.name;e.instanceOf(c,
[k.ArrayType,k.MapType,k.SetType,k.StructType,k.TupleType]);e.instanceOf(a,String);e.assert(!d.has(a),'"'+a+'" is already a registered type');d.set(a,c)},getType:function(a){e.instanceOf(a,String);var c=d.get(a);e.assert(void 0!==c,'"'+a+'" is not a registered type');return c},isRegistered:function(a){return d.has(a)}}},{"./lib/assert":"/lib/assert.js","./structure-types":"/structure-types.js"}],"/structure-types.js":[function(a,g,b){function e(a,c){if(c&&(c=w.get(a))){c=$jscomp.makeIterator(c);for(var b=
c.next();!b.done;b=c.next()){var d=$jscomp.makeIterator(b.value),b=d.next().value,d=d.next().value,e=a.length;a.addAll(l.fromBinaryString(b));b=new ArrayBuffer(4);(new DataView(b)).setUint32(0,e);d=$jscomp.makeIterator(d);for(e=d.next();!e.done;e=d.next())a.setAll(e.value,b)}}}function k(a){if(a&&a.constructor===String&&(a=Number(a),!isNaN(a)))return a}function d(a,b){c.instanceOf(a,q);c.instanceOf(b,String);c.assert(!(r.gt(b,"9223372036854775807")||r.lt(b,"-9223372036854775808")),"Value out of range");
var d=r.div(b,r.LONG_UPPER_SHIFT,!0);b=r.sub(b,r.mul(d,r.LONG_UPPER_SHIFT));var e=new ArrayBuffer(8),I=new DataView(e);I.setInt32(0,Number(d));I.setUint32(4,Number(b));a.addAll(e)}function n(a,b){c.instanceOf(b,Array);for(var d=A(b.length),e=D(b.length),d=new ArrayBuffer(d?e+1:e),e=new Uint8Array(d),I=0;I<b.length;I++){var pa=b[I];c.instanceOf(pa,Boolean);var f=A(~A(I));pa?e[D(I)]|=1<<f:e[D(I)]&=~(1<<f)}a.addAll(d)}var c=a("./lib/assert"),v=a("base64-js"),l=a("./lib/buffer-string"),E=a("./config"),
u=a("./lib/flex-int"),C=a("sha256"),q=a("./lib/growable-buffer"),G,r=a("./lib/strint"),p=a("util");b=a("./lib/bit-math");var D=b.dividedByEight,A=b.modEight,z=new WeakMap,B=new WeakMap,x=new WeakMap,w=new WeakMap,t=function(){};t.prototype.addToBuffer=function(a){c.instanceOf(a,q);if(this.cachedTypeLocations){if(!B.get(a)){var b=this.cachedTypeLocations.get(a);if(void 0!==b)return a.add(255),a.addAll(u.makeValueBuffer(a.length-b)),!1}}else this.cachedTypeLocations=new Map;this.cachedTypeLocations.set(a,
a.length);a.add(this.constructor._value);return!0};t.prototype.toBuffer=function(){this.cachedBuffer||(this.cachedBuffer=this._toBuffer());return this.cachedBuffer};t.prototype._toBuffer=function(){var a=new q;this.addToBuffer(a);return a.toBuffer()};t.prototype.getHash=function(){this.cachedHash||(this.cachedHash=this._getHash());return this.cachedHash};t.prototype._getHash=function(){return v.fromByteArray(C(this.toBuffer(),{asBytes:!0}))};t.prototype.getSignature=function(){this.cachedSignature||
(this.cachedSignature=this._getSignature());return this.cachedSignature};t.prototype._getSignature=function(){return E.VERSION_STRING+this.getHash()};t.prototype.writeValue=function(a,b){c.fail("Generic Type has no value representation")};t.prototype.valueBuffer=function(a){var c=new q;this.writeValue(c,a);return c.toBuffer()};t.prototype.equals=function(a){try{c.instanceOf(a,this.constructor)}catch(qa){return!1}try{c.equal(a.constructor,this.constructor)}catch(qa){return!1}for(var b in this)if({}.hasOwnProperty.call(this,
b)&&!b.startsWith("cached"))try{c.equal(a[b],this[b])}catch(qa){return!1}return!0};$jscomp.global.Object.defineProperties(t,{_value:{configurable:!0,enumerable:!0,get:function(){c.fail("Generic Type has no value byte")}}});var f=function(a){return t.apply(this,arguments)||this};$jscomp.inherits(f,t);var y=function(a){return f.apply(this,arguments)||this};$jscomp.inherits(y,f);b=function(a){return y.apply(this,arguments)||this};$jscomp.inherits(b,y);b.prototype.writeValue=function(a,b){c.instanceOf(a,
q);var d=k(b);void 0!==d&&(b=d);c.integer(b);c.between(-128,b,128,"Value out of range");d=new ArrayBuffer(1);(new DataView(d)).setInt8(0,b);a.addAll(d)};$jscomp.global.Object.defineProperties(b,{_value:{configurable:!0,enumerable:!0,get:function(){return 1}}});var h=function(a){return y.apply(this,arguments)||this};$jscomp.inherits(h,y);h.prototype.writeValue=function(a,b){c.instanceOf(a,q);var d=k(b);void 0!==d&&(b=d);c.integer(b);c.between(-32768,b,32768,"Value out of range");d=new ArrayBuffer(2);
(new DataView(d)).setInt16(0,b);a.addAll(d)};$jscomp.global.Object.defineProperties(h,{_value:{configurable:!0,enumerable:!0,get:function(){return 2}}});var m=function(a){return y.apply(this,arguments)||this};$jscomp.inherits(m,y);m.prototype.writeValue=function(a,b){c.instanceOf(a,q);var d=k(b);void 0!==d&&(b=d);c.integer(b);c.between(-2147483648,b,2147483648,"Value out of range");d=new ArrayBuffer(4);(new DataView(d)).setInt32(0,b);a.addAll(d)};$jscomp.global.Object.defineProperties(m,{_value:{configurable:!0,
enumerable:!0,get:function(){return 3}}});var L=function(a){return y.apply(this,arguments)||this};$jscomp.inherits(L,y);L.prototype.writeValue=function(a,c){d(a,c)};$jscomp.global.Object.defineProperties(L,{_value:{configurable:!0,enumerable:!0,get:function(){return 4}}});var H=function(a){return y.apply(this,arguments)||this};$jscomp.inherits(H,y);H.prototype.writeValue=function(a,b){c.instanceOf(a,q);c.instanceOf(b,String);b=r.normalize(b);var d=[];if(!r.eq(b,"0")){for(;r.gt(b,"127")||r.lt(b,"-128");){var e=
r.div(b,r.BYTE_SHIFT,!0);b=r.sub(b,r.mul(e,r.BYTE_SHIFT));d.push(Number(b));b=e}d.push(Number(b))}a.addAll(u.makeValueBuffer(d.length));e=new ArrayBuffer(d.length);b=new DataView(e);for(var I=1,f=d.length-2;0<=f;f--,I++)b.setUint8(I,d[f]);d.length&&b.setInt8(0,d[d.length-1]);a.addAll(e)};$jscomp.global.Object.defineProperties(H,{_value:{configurable:!0,enumerable:!0,get:function(){return 5}}});var F=function(a){return f.apply(this,arguments)||this};$jscomp.inherits(F,f);var K=function(a){return F.apply(this,
arguments)||this};$jscomp.inherits(K,F);K.prototype.writeValue=function(a,b){c.instanceOf(a,q);var d=k(b);void 0!==d&&(b=d);c.integer(b);c.between(0,b,256,"Value out of range");d=new ArrayBuffer(1);(new Uint8Array(d))[0]=b;a.addAll(d)};$jscomp.global.Object.defineProperties(K,{_value:{configurable:!0,enumerable:!0,get:function(){return 17}}});var J=function(a){return F.apply(this,arguments)||this};$jscomp.inherits(J,F);J.prototype.writeValue=function(a,b){c.instanceOf(a,q);var d=k(b);void 0!==d&&
(b=d);c.integer(b);c.between(0,b,65536,"Value out of range");d=new ArrayBuffer(2);(new DataView(d)).setUint16(0,b);a.addAll(d)};$jscomp.global.Object.defineProperties(J,{_value:{configurable:!0,enumerable:!0,get:function(){return 18}}});var M=function(a){return F.apply(this,arguments)||this};$jscomp.inherits(M,F);M.prototype.writeValue=function(a,b){c.instanceOf(a,q);var d=k(b);void 0!==d&&(b=d);c.integer(b);c.between(0,b,4294967296,"Value out of range");d=new ArrayBuffer(4);(new DataView(d)).setUint32(0,
b);a.addAll(d)};$jscomp.global.Object.defineProperties(M,{_value:{configurable:!0,enumerable:!0,get:function(){return 19}}});var ca=function(a){return F.apply(this,arguments)||this};$jscomp.inherits(ca,F);ca.prototype.writeValue=function(a,b){c.instanceOf(a,q);c.instanceOf(b,String);c.assert(!(r.gt(b,"18446744073709551615")||r.lt(b,"0")),"Value out of range");var d=r.div(b,r.LONG_UPPER_SHIFT);b=r.sub(b,r.mul(d,r.LONG_UPPER_SHIFT));var e=new ArrayBuffer(8),f=new DataView(e);f.setUint32(0,Number(d));
f.setUint32(4,Number(b));a.addAll(e)};$jscomp.global.Object.defineProperties(ca,{_value:{configurable:!0,enumerable:!0,get:function(){return 20}}});var da=function(a){return F.apply(this,arguments)||this};$jscomp.inherits(da,F);da.prototype.writeValue=function(a,b){c.instanceOf(a,q);c.instanceOf(b,String);c.assert(!r.isNegative(b),"Value out of range");var d=[];if(!r.eq(b,"0")){for(;r.ge(b,r.BYTE_SHIFT);){var e=$jscomp.makeIterator(r.quotientRemainderPositive(b,r.BYTE_SHIFT));b=e.next().value;e=e.next().value;
d.push(Number(e))}d.push(Number(b))}a.addAll(u.makeValueBuffer(d.length));b=new ArrayBuffer(d.length);for(var e=new DataView(b),f=0,g=d.length-1;0<=g;g--,f++)e.setUint8(f,d[g]);a.addAll(b)};$jscomp.global.Object.defineProperties(da,{_value:{configurable:!0,enumerable:!0,get:function(){return 21}}});var ea=function(a){return F.apply(this,arguments)||this};$jscomp.inherits(ea,F);ea.prototype.writeValue=function(a,b){c.instanceOf(a,q);var d=k(b);void 0!==d&&(b=d);c.integer(b);a.addAll(u.makeValueBuffer(b))};
$jscomp.global.Object.defineProperties(ea,{_value:{configurable:!0,enumerable:!0,get:function(){return 23}}});var O=function(a){return f.apply(this,arguments)||this};$jscomp.inherits(O,f);var R=function(a){return O.apply(this,arguments)||this};$jscomp.inherits(R,O);R.prototype.writeValue=function(a,b){c.instanceOf(b,Date);d(a,String(b.getTime()))};$jscomp.global.Object.defineProperties(R,{_value:{configurable:!0,enumerable:!0,get:function(){return 26}}});var fa=function(a){return O.apply(this,arguments)||
this};$jscomp.inherits(fa,O);fa.prototype.writeValue=function(a,b){c.instanceOf(b,Date);b=new Date(b.getFullYear(),b.getMonth(),b.getDate());b=(b.getTime()-6E4*b.getTimezoneOffset())/864E5;var d=new ArrayBuffer(3),e=new DataView(d);e.setInt16(0,b>>8);e.setUint8(2,b&255);a.addAll(d)};$jscomp.global.Object.defineProperties(fa,{_value:{configurable:!0,enumerable:!0,get:function(){return 27}}});var ga=function(a){return O.apply(this,arguments)||this};$jscomp.inherits(ga,O);ga.prototype.writeValue=function(a,
b){c.instanceOf(b,Date);var d=new ArrayBuffer(4);(new DataView(d)).setUint32(0,b.getTime()%864E5);a.addAll(d)};$jscomp.global.Object.defineProperties(ga,{_value:{configurable:!0,enumerable:!0,get:function(){return 28}}});var S=function(a){return f.apply(this,arguments)||this};$jscomp.inherits(S,f);var ha=function(a){return S.apply(this,arguments)||this};$jscomp.inherits(ha,S);ha.prototype.writeValue=function(a,b){c.instanceOf(a,q);var d=k(b);void 0!==d&&(b=d);c.instanceOf(b,Number);d=new ArrayBuffer(4);
(new DataView(d)).setFloat32(0,b);a.addAll(d)};$jscomp.global.Object.defineProperties(ha,{_value:{configurable:!0,enumerable:!0,get:function(){return 32}}});var ia=function(a){return S.apply(this,arguments)||this};$jscomp.inherits(ia,S);ia.prototype.writeValue=function(a,b){c.instanceOf(a,q);var d=k(b);void 0!==d&&(b=d);c.instanceOf(b,Number);d=new ArrayBuffer(8);(new DataView(d)).setFloat64(0,b);a.addAll(d)};$jscomp.global.Object.defineProperties(ia,{_value:{configurable:!0,enumerable:!0,get:function(){return 33}}});
var ja=function(a){return f.apply(this,arguments)||this};$jscomp.inherits(ja,f);ja.prototype.writeValue=function(a,b){c.instanceOf(a,q);c.instanceOf(b,Boolean);b?a.add(255):a.add(0)};$jscomp.global.Object.defineProperties(ja,{_value:{configurable:!0,enumerable:!0,get:function(){return 48}}});var T=function(a){var b;b=f.call(this)||this;c.byteUnsignedInteger(a);b.length=a;return b};$jscomp.inherits(T,f);T.prototype.addToBuffer=function(a){f.prototype.addToBuffer.call(this,a)&&a.add(this.length)};T.prototype.writeValue=
function(a,b){c.instanceOf(a,q);c.instanceOf(b,Array);c.assert(b.length===this.length,"Length does not match: expected "+String(this.length)+" but got "+b.length);n(a,b)};$jscomp.global.Object.defineProperties(T,{_value:{configurable:!0,enumerable:!0,get:function(){return 49}}});var ka=function(a){return f.apply(this,arguments)||this};$jscomp.inherits(ka,f);ka.prototype.writeValue=function(a,b){c.instanceOf(b,Array);a.addAll(u.makeValueBuffer(b.length));n(a,b)};$jscomp.global.Object.defineProperties(ka,
{_value:{configurable:!0,enumerable:!0,get:function(){return 50}}});var la=function(a){return f.apply(this,arguments)||this};$jscomp.inherits(la,f);la.prototype.writeValue=function(a,b){c.instanceOf(a,q);c.instanceOf(b,String);c.assert(1===b.length,"String must contain only 1 character");a.addAll(l.fromString(b))};$jscomp.global.Object.defineProperties(la,{_value:{configurable:!0,enumerable:!0,get:function(){return 64}}});var ma=function(a){return f.apply(this,arguments)||this};$jscomp.inherits(ma,
f);ma.prototype.writeValue=function(a,b){c.instanceOf(a,q);c.instanceOf(b,String);b=l.fromString(b);a.addAll(b);a.add(0)};$jscomp.global.Object.defineProperties(ma,{_value:{configurable:!0,enumerable:!0,get:function(){return 65}}});var na=function(a){return f.apply(this,arguments)||this};$jscomp.inherits(na,f);na.prototype.writeValue=function(a,b){c.instanceOf(a,q);c.instanceOf(b,ArrayBuffer);a.addAll(u.makeValueBuffer(b.byteLength));a.addAll(b)};$jscomp.global.Object.defineProperties(na,{_value:{configurable:!0,
enumerable:!0,get:function(){return 66}}});var U=function(a){var b=a.type,d=a.length;a=f.call(this)||this;c.instanceOf(b,t);c.byteUnsignedInteger(d);a.type=b;a.length=d;return a};$jscomp.inherits(U,f);U.prototype.addToBuffer=function(a){f.prototype.addToBuffer.call(this,a)&&(this.type.addToBuffer(a),a.add(this.length))};U.prototype.writeValue=function(a,b,d){d=void 0===d?!0:d;c.instanceOf(a,q);c.instanceOf(b,Array);c.assert(b.length===this.length,"Length does not match: expected "+String(this.length)+
" but got "+b.length);b=$jscomp.makeIterator(b);for(var f=b.next();!f.done;f=b.next())this.type.writeValue(a,f.value,!1);e(a,d)};$jscomp.global.Object.defineProperties(U,{_value:{configurable:!0,enumerable:!0,get:function(){return 80}}});var P=function(a){var b;b=f.call(this)||this;c.instanceOf(a,Object);var d=0,e;for(e in a)({}).hasOwnProperty.call(a,e)&&d++;try{c.byteUnsignedInteger(d)}catch(V){c.fail(String(d)+" fields is too many")}b.fields=Array(d);var d=0,g;for(g in a)if({}.hasOwnProperty.call(a,
g)){e=l.fromString(g);try{c.byteUnsignedInteger(e.byteLength)}catch(V){c.fail("Field name "+g+" is too long")}var h=a[g];try{c.instanceOf(h,t)}catch(V){c.fail(String(h)+" is not a valid field type")}var k={};b.fields[d]=(k.name=g,k.type=h,k.buffer=e,k);d++}b.fields.sort(function(a,b){if(a.name<b.name)return-1;if(a.name>b.name)return 1});return b};$jscomp.inherits(P,f);P.prototype.addToBuffer=function(a){if(f.prototype.addToBuffer.call(this,a)){a.add(this.fields.length);for(var b=$jscomp.makeIterator(this.fields),
c=b.next();!c.done;c=b.next()){var c=c.value,d=c.buffer;a.add(d.byteLength);a.addAll(d);c.type.addToBuffer(a)}}};P.prototype.writeValue=function(a,b,d){d=void 0===d?!0:d;c.instanceOf(a,q);c.instanceOf(b,Object);for(var f=$jscomp.makeIterator(this.fields),g=f.next();!g.done;g=f.next()){var g=g.value,h=b[g.name];try{g.type.writeValue(a,h,!1)}catch(ra){throw c.assert(void 0!==h,'Value for field "'+g.name+'" missing'),ra;}}e(a,d)};$jscomp.global.Object.defineProperties(P,{_value:{configurable:!0,enumerable:!0,
get:function(){return 81}}});var N=function(a){var b;b=f.call(this)||this;c.instanceOf(a,t);b.type=a;return b};$jscomp.inherits(N,f);N.prototype.addToBuffer=function(a){f.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};N.prototype._writeValue=function(a){var b=a;a=b.buffer;var d=b.value,f=b.length,b=b.root;c.instanceOf(a,q);a.addAll(u.makeValueBuffer(f));d=$jscomp.makeIterator(d);for(f=d.next();!f.done;f=d.next())this.type.writeValue(a,f.value,!1);e(a,b)};N.prototype.writeValue=function(a,
b,d){d=void 0===d?!0:d;c.instanceOf(b,Array);this._writeValue({buffer:a,value:b,length:b.length,root:d})};$jscomp.global.Object.defineProperties(N,{_value:{configurable:!0,enumerable:!0,get:function(){return 82}}});var oa=function(a){return N.apply(this,arguments)||this};$jscomp.inherits(oa,N);oa.prototype.writeValue=function(a,b,d){d=void 0===d?!0:d;c.instanceOf(b,Set);this._writeValue({buffer:a,value:b,length:b.size,root:d})};$jscomp.global.Object.defineProperties(oa,{_value:{configurable:!0,enumerable:!0,
get:function(){return 83}}});var W=function(a,b){var d;d=f.call(this)||this;c.instanceOf(a,t);c.instanceOf(b,t);d.keyType=a;d.valueType=b;return d};$jscomp.inherits(W,f);W.prototype.addToBuffer=function(a){f.prototype.addToBuffer.call(this,a)&&(this.keyType.addToBuffer(a),this.valueType.addToBuffer(a))};W.prototype.writeValue=function(a,b,d){d=void 0===d?!0:d;c.instanceOf(a,q);c.instanceOf(b,Map);a.addAll(u.makeValueBuffer(b.size));b=$jscomp.makeIterator(b);for(var f=b.next();!f.done;f=b.next()){var g=
$jscomp.makeIterator(f.value),f=g.next().value,g=g.next().value;this.keyType.writeValue(a,f,!1);this.valueType.writeValue(a,g,!1)}e(a,d)};$jscomp.global.Object.defineProperties(W,{_value:{configurable:!0,enumerable:!0,get:function(){return 84}}});var X=function(a){var b=a.type;a=a.values;c.instanceOf(b,f);c.instanceOf(a,Array);try{c.byteUnsignedInteger(a.length)}catch(ra){c.fail(String(a.length)+" values is too many")}for(var d=new Map,e=0;e<a.length;e++){var g=a[e],h=l.toBinaryString(b.valueBuffer(g));
c.assert(!d.has(h),"Value is repeated: "+p.inspect(g));d.set(h,e)}this.type=b;this.values=a;this.valueIndices=d;return this};$jscomp.inherits(X,t);X.prototype.addToBuffer=function(a){if(t.prototype.addToBuffer.call(this,a)){this.type.addToBuffer(a);a.add(this.valueIndices.size);for(var b=$jscomp.makeIterator(this.valueIndices),c=b.next();!c.done;c=b.next()){var c=$jscomp.makeIterator(c.value),d=c.next().value;c.next();a.addAll(l.fromBinaryString(d))}}};X.prototype.writeValue=function(a,b,d){d=void 0===
d?!0:d;c.instanceOf(a,q);var f=new q;this.type.writeValue(f,b,!1);f=this.valueIndices.get(l.toBinaryString(f.toBuffer()));c.assert(void 0!==f,"Not a valid enum value: "+p.inspect(b));a.add(f);e(a,d)};$jscomp.global.Object.defineProperties(X,{_value:{configurable:!0,enumerable:!0,get:function(){return 85}}});var Y=function(a){var b;b=f.call(this)||this;c.instanceOf(a,Array);try{c.byteUnsignedInteger(a.length)}catch(sa){c.fail(String(a.length)+" types is too many")}for(var d=$jscomp.makeIterator(a),
e=d.next();!e.done;e=d.next())c.instanceOf(e.value,t);b.types=a;return b};$jscomp.inherits(Y,f);Y.prototype.addToBuffer=function(a){if(f.prototype.addToBuffer.call(this,a)){a.add(this.types.length);for(var b=$jscomp.makeIterator(this.types),c=b.next();!c.done;c=b.next())c.value.addToBuffer(a)}};Y.prototype.writeValue=function(a,b,d){d=void 0===d?!0:d;c.instanceOf(a,q);for(var f=!1,g=0;g<this.types.length;g++){var h=this.types[g],k=new q;try{h.writeValue(k,b,!1)}catch(V){continue}a.add(g);a.addAll(k.toBuffer());
f=!0;break}c.assert(f,"No types matched: "+p.inspect(b));e(a,d)};$jscomp.global.Object.defineProperties(Y,{_value:{configurable:!0,enumerable:!0,get:function(){return 86}}});var Z=function(a){var b;b=f.call(this)||this;c.instanceOf(a,Map);try{c.byteUnsignedInteger(a.size)}catch(V){c.fail(String(a.size)+" types is too many")}b.indexConstructors=new Map;b.constructorTypes=Array(a.size);var d=new Set;a=$jscomp.makeIterator(a);for(var e=a.next();!e.done;e=a.next()){var g=$jscomp.makeIterator(e.value),
e=g.next().value,g=g.next().value;c.instanceOf(e,Function);var h=e.name;c.assert(h,'Function "'+String(h)+'" does not have a name');c.assert(!d.has(h),'Function name "'+h+'" is repeated');d.add(h);var k=l.fromString(h);try{c.byteUnsignedInteger(k.byteLength)}catch(V){c.fail('Function name "'+h+'" is too long')}c.instanceOf(g,P);h=b.indexConstructors.size;b.indexConstructors.set(h,e);b.constructorTypes[h]={nameBuffer:k,type:g}}return b};$jscomp.inherits(Z,f);Z.prototype.addToBuffer=function(a){if(f.prototype.addToBuffer.call(this,
a)){a.add(this.constructorTypes.length);for(var b=$jscomp.makeIterator(this.constructorTypes),c=b.next();!c.done;c=b.next()){var d=c.value,c=d.nameBuffer,d=d.type;a.add(c.byteLength);a.addAll(c);d.addToBuffer(a)}}};Z.prototype.writeValue=function(a,b,d){d=void 0===d?!0:d;c.instanceOf(a,q);c.instanceOf(b,Object);for(var f,g=$jscomp.makeIterator(this.indexConstructors),h=g.next();!h.done;h=g.next()){var k=$jscomp.makeIterator(h.value),h=k.next().value,k=k.next().value;if(b instanceof k){f=h;break}}c.assert(void 0!==
f,"No types matched: "+p.inspect(b));a.add(f);this.constructorTypes[f].type.writeValue(a,b,!1);e(a,d)};$jscomp.global.Object.defineProperties(Z,{_value:{configurable:!0,enumerable:!0,get:function(){return 88}}});var Q=function(a){var b;b=f.call(this)||this;c.instanceOf(a,String);b.name=a;return b};$jscomp.inherits(Q,f);Q.prototype.addToBuffer=function(a){if(f.prototype.addToBuffer.call(this,a)){var b=z.get(a);b||(b=new Map,z.set(a,b));var c=b.get(this.name),d=void 0===c;d&&(c=b.size,b.set(this.name,
c));a.addAll(u.makeValueBuffer(c));d&&(b=B.get(a)||0,B.set(a,b+1),this.type.addToBuffer(a),B.set(a,b))}};Q.prototype.writeValue=function(a,b,d){d=void 0===d?!0:d;c.instanceOf(a,q);var f=!0,g=x.get(a);if(g){var h=g.get(b);void 0!==h&&(f=!1,a.add(0),a.addAll(u.makeValueBuffer(a.length-h)))}else g=new Map,x.set(a,g);f&&(a.add(255),g.set(b,a.length),this.type.writeValue(a,b,!1));e(a,d)};$jscomp.global.Object.defineProperties(Q.prototype,{type:{configurable:!0,enumerable:!0,get:function(){G||(G=a("./recursive-registry"));
return G.getType(this.name)}}});$jscomp.global.Object.defineProperties(Q,{_value:{configurable:!0,enumerable:!0,get:function(){return 87}}});var aa=function(a){var b;b=f.call(this)||this;c.instanceOf(a,t);b.type=a;return b};$jscomp.inherits(aa,f);aa.prototype.addToBuffer=function(a){f.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};aa.prototype.writeValue=function(a,b,d){d=void 0===d?!0:d;c.instanceOf(a,q);null===b||void 0===b?a.add(0):(a.add(255),this.type.writeValue(a,b,!1));e(a,d)};
$jscomp.global.Object.defineProperties(aa,{_value:{configurable:!0,enumerable:!0,get:function(){return 96}}});var ba=function(a){c.instanceOf(a,f);this.type=a;return this};$jscomp.inherits(ba,t);ba.prototype.addToBuffer=function(a){t.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};ba.prototype.writeValue=function(a,b,d){d=void 0===d?!0:d;c.instanceOf(a,q);var f=w.get(a);f||(f=new Map,w.set(a,f));var g=new q;this.type.writeValue(g,b,!1);b=l.toBinaryString(g.toBuffer());var g=a.length,
h=f.get(b);h?h.add(g):f.set(b,new Set([g]));a.addAll(new ArrayBuffer(4));e(a,d)};$jscomp.global.Object.defineProperties(ba,{_value:{configurable:!0,enumerable:!0,get:function(){return 112}}});g.exports={Type:t,ByteType:b,ShortType:h,IntType:m,LongType:L,BigIntType:H,UnsignedByteType:K,UnsignedShortType:J,UnsignedIntType:M,UnsignedLongType:ca,BigUnsignedIntType:da,FlexUnsignedIntType:ea,DateType:R,DayType:fa,TimeType:ga,FloatType:ha,DoubleType:ia,BooleanType:ja,BooleanTupleType:T,BooleanArrayType:ka,
CharType:la,StringType:ma,OctetsType:na,TupleType:U,StructType:P,ArrayType:N,SetType:oa,MapType:W,EnumType:X,ChoiceType:Y,NamedChoiceType:Z,RecursiveType:Q,OptionalType:aa,PointerType:ba,REPEATED_TYPE:255,MILLIS_PER_DAY:864E5,MILLIS_PER_MINUTE:6E4}},{"./config":"/config.js","./lib/assert":"/lib/assert.js","./lib/bit-math":"/lib/bit-math.js","./lib/buffer-string":"/lib/buffer-string.js","./lib/flex-int":"/lib/flex-int.js","./lib/growable-buffer":"/lib/growable-buffer.js","./lib/strint":"/lib/strint.js",
"./recursive-registry":"/recursive-registry.js","base64-js":2,sha256:7,util:9}]},{},[1]);}()
