!function(){var g={scope:{}};g.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,h,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[h]=c.value)};g.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};g.global=g.getGlobal(this);g.SYMBOL_PREFIX="jscomp_symbol_";
g.initSymbol=function(){g.initSymbol=function(){};g.global.Symbol||(g.global.Symbol=g.Symbol)};g.symbolCounter_=0;g.Symbol=function(b){return g.SYMBOL_PREFIX+(b||"")+g.symbolCounter_++};g.initSymbolIterator=function(){g.initSymbol();var b=g.global.Symbol.iterator;b||(b=g.global.Symbol.iterator=g.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&g.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return g.arrayIterator(this)}});g.initSymbolIterator=function(){}};
g.arrayIterator=function(b){var h=0;return g.iteratorPrototype(function(){return h<b.length?{done:!1,value:b[h++]}:{done:!0}})};g.iteratorPrototype=function(b){g.initSymbolIterator();b={next:b};b[g.global.Symbol.iterator]=function(){return this};return b};g.makeIterator=function(b){g.initSymbolIterator();g.initSymbol();g.initSymbolIterator();var h=b[Symbol.iterator];return h?h.call(b):g.arrayIterator(b)};g.arrayFromIterator=function(b){for(var h,c=[];!(h=b.next()).done;)c.push(h.value);return c};
g.arrayFromIterable=function(b){return b instanceof Array?b:g.arrayFromIterator(g.makeIterator(b))};g.inherits=function(b,h){function c(){}c.prototype=h.prototype;b.prototype=new c;b.prototype.constructor=b;for(var e in h)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(h,e);d&&Object.defineProperty(b,e,d)}else b[e]=h[e]};g.owns=function(b,h){return Object.prototype.hasOwnProperty.call(b,h)};
g.polyfill=function(b,h){if(h){var c=g.global;b=b.split(".");for(var e=0;e<b.length-1;e++){var d=b[e];d in c||(c[d]={});c=c[d]}b=b[b.length-1];e=c[b];h=h(e);h!=e&&null!=h&&g.defineProperty(c,b,{configurable:!0,writable:!0,value:h})}};
g.polyfill("WeakMap",function(b){function h(d){this.id_=(a+=Math.random()+1).toString();if(d){g.initSymbol();g.initSymbolIterator();d=g.makeIterator(d);for(var f;!(f=d.next()).done;)f=f.value,this.set(f[0],f[1])}}function c(a){g.owns(a,d)||g.defineProperty(a,d,{value:{}})}function e(a){var f=Object[a];f&&(Object[a]=function(a){c(a);return f(a)})}if(function(){if(!b||!Object.seal)return!1;try{var a=Object.seal({}),f=Object.seal({}),d=new b([[a,2],[f,3]]);if(2!=d.get(a)||3!=d.get(f))return!1;d.delete(a);
d.set(f,4);return!d.has(a)&&4==d.get(f)}catch(q){return!1}}())return b;var d="$jscomp_hidden_"+Math.random().toString().substring(2);e("freeze");e("preventExtensions");e("seal");var a=0;h.prototype.set=function(a,f){c(a);if(!g.owns(a,d))throw Error("WeakMap key fail: "+a);a[d][this.id_]=f;return this};h.prototype.get=function(a){return g.owns(a,d)?a[d][this.id_]:void 0};h.prototype.has=function(a){return g.owns(a,d)&&g.owns(a[d],this.id_)};h.prototype.delete=function(a){return g.owns(a,d)&&g.owns(a[d],
this.id_)?delete a[d][this.id_]:!1};return h},"es6-impl","es3");g.ASSUME_NO_NATIVE_MAP=!1;
g.polyfill("Map",function(b){function h(){var a={};return a.previous=a.next=a.head=a}function c(a,d){var f=a.head_;return g.iteratorPrototype(function(){if(f){for(;f.head!=a.head_;)f=f.previous;for(;f.next!=f.head;)return f=f.next,{done:!1,value:d(f)};f=null}return{done:!0,value:void 0}})}function e(f,d){var c;c=d&&typeof d;"object"==c||"function"==c?a.has(d)?c=a.get(d):(c=""+ ++l,a.set(d,c)):c="p_"+d;var e=f.data_[c];if(e&&g.owns(f.data_,c))for(f=0;f<e.length;f++){var b=e[f];if(d!==d&&b.key!==b.key||
d===b.key)return{id:c,list:e,index:f,entry:b}}return{id:c,list:e,index:-1,entry:void 0}}function d(a){this.data_={};this.head_=h();this.size=0;if(a){a=g.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}}if(!g.ASSUME_NO_NATIVE_MAP&&function(){if(!b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),d=new b(g.makeIterator([[a,"s"]]));if("s"!=d.get(a)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var c=d.entries(),
e=c.next();if(e.done||e.value[0]!=a||"s"!=e.value[1])return!1;e=c.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!c.next().done?!1:!0}catch(m){return!1}}())return b;g.initSymbol();g.initSymbolIterator();var a=new WeakMap;d.prototype.set=function(a,d){var f=e(this,a);f.list||(f.list=this.data_[f.id]=[]);f.entry?f.entry.value=d:(f.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:d},f.list.push(f.entry),this.head_.previous.next=f.entry,this.head_.previous=f.entry,
this.size++);return this};d.prototype.delete=function(a){a=e(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=h();this.size=0};d.prototype.has=function(a){return!!e(this,a).entry};d.prototype.get=function(a){return(a=e(this,a).entry)&&a.value};d.prototype.entries=function(){return c(this,
function(a){return[a.key,a.value]})};d.prototype.keys=function(){return c(this,function(a){return a.key})};d.prototype.values=function(){return c(this,function(a){return a.value})};d.prototype.forEach=function(a,d){for(var c=this.entries(),f;!(f=c.next()).done;)f=f.value,a.call(d,f[1],f[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var l=0;return d},"es6-impl","es3");g.ASSUME_NO_NATIVE_SET=!1;
g.polyfill("Set",function(b){function h(c){this.map_=new Map;if(c){c=g.makeIterator(c);for(var e;!(e=c.next()).done;)this.add(e.value)}this.size=this.map_.size}if(!g.ASSUME_NO_NATIVE_SET&&function(){if(!b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),e=new b(g.makeIterator([c]));if(!e.has(c)||1!=e.size||e.add(c)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var d=e.entries(),a=d.next();if(a.done||a.value[0]!=c||a.value[1]!=c)return!1;a=d.next();return a.done||
a.value[0]==c||4!=a.value[0].x||a.value[1]!=a.value[0]?!1:d.next().done}catch(l){return!1}}())return b;g.initSymbol();g.initSymbolIterator();h.prototype.add=function(c){this.map_.set(c,c);this.size=this.map_.size;return this};h.prototype.delete=function(c){c=this.map_.delete(c);this.size=this.map_.size;return c};h.prototype.clear=function(){this.map_.clear();this.size=0};h.prototype.has=function(c){return this.map_.has(c)};h.prototype.entries=function(){return this.map_.entries()};h.prototype.values=
function(){return this.map_.values()};h.prototype[Symbol.iterator]=h.prototype.values;h.prototype.forEach=function(c,e){var d=this;this.map_.forEach(function(a){return c.call(e,a,a,d)})};return h},"es6-impl","es3");g.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");g.polyfill("Number.isFinite",function(b){return b?b:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}},"es6-impl","es3");
g.polyfill("Number.isInteger",function(b){return b?b:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}},"es6-impl","es3");g.polyfill("Number.isSafeInteger",function(b){return b?b:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}},"es6-impl","es3");g.array=g.array||{};
g.iteratorFromArray=function(b,h){g.initSymbolIterator();b instanceof String&&(b+="");var c=0,e={next:function(){if(c<b.length){var d=c++;return{value:h(d,b[d]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};g.polyfill("Array.prototype.entries",function(b){return b?b:function(){return g.iteratorFromArray(this,function(b,c){return[b,c]})}},"es6-impl","es3");
g.polyfill("Array.prototype.values",function(b){return b?b:function(){return g.iteratorFromArray(this,function(b,c){return c})}},"es6","es3");g.checkStringArgs=function(b,h,c){if(null==b)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(h instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return b+""};
g.polyfill("String.prototype.startsWith",function(b){return b?b:function(b,c){var e=g.checkStringArgs(this,b,"startsWith");b+="";var d=e.length,a=b.length;c=Math.max(0,Math.min(c|0,e.length));for(var l=0;l<a&&c<d;)if(e[c++]!=b[l++])return!1;return l>=a}},"es6-impl","es3");
require=function ia(h,c,e){function d(f,l){if(!c[f]){if(!h[f]){var p="function"==typeof require&&require;if(!l&&p)return p(f,!0);if(a)return a(f,!0);l=Error("Cannot find module '"+f+"'");throw l.code="MODULE_NOT_FOUND",l;}l=c[f]={exports:{}};h[f][0].call(l.exports,function(a){var c=h[f][1][a];return d(c?c:a)},l,l.exports,ia,h,c,e)}return c[f].exports}for(var a="function"==typeof require&&require,l=0;l<e.length;l++)d(e[l]);return d}({"/client-side/binary-ajax.js":[function(){(function(b){b.ajaxTransport("+*",
function(b){if(window.FormData&&("blob"===b.dataType||"arraybuffer"===b.dataType||b.data&&(window.Blob&&b.data instanceof Blob||window.ArrayBuffer&&b.data instanceof ArrayBuffer))){var c;return{send:function(e,d){var a=b.url||location.href,l=b.type||"GET",f=b.dataType||"text",p=b.data||null,h=b.async||!0;c=new XMLHttpRequest;c.addEventListener("load",function(){var a={};200<=c.status&&300>c.status||304===c.status?a[f]=c.response:a.text=c.statusText;d(c.status,c.statusText,a,c.getAllResponseHeaders())});
c.open(l,a,h);c.responseType=f;for(var A in e)({}).hasOwnProperty.call(e,A)&&c.setRequestHeader(A,e[A]);c.send(p)},abort:function(){c&&c.abort()}}}})})(jQuery)},{}],"/client-side/common.js":[function(b){var h=b("/lib/assert.js");h.instanceOf(window.Map,Function);h.instanceOf(window.Set,Function);h.instanceOf(window.ArrayBuffer,Function);h.instanceOf(window.Uint8Array,Function);h.instanceOf(window.Symbol,Function);b("/client-side/binary-ajax.js");if(!window.sb)window.sb=b("/structure-types.js");else if(!(window.sb instanceof
Object))throw Error("window.sb is already defined");},{"/client-side/binary-ajax.js":"/client-side/binary-ajax.js","/lib/assert.js":"/lib/assert.js","/structure-types.js":"/structure-types.js"}],"/config.js":[function(b,h){var c="/";"/"===c&&(c="");c=b(c+"/lib/assert.js");b=b("base64-js");c.between(0,9,65536);c=new ArrayBuffer(2);(new DataView(c)).setUint16(0,9);b=b.fromByteArray(new Uint8Array(c));h.exports={VERSION_STRING:b}},{"base64-js":2}],"/lib/assert.js":[function(b,h){var c=b("/lib/util-inspect.js"),
e=h.exports={instanceOf:function(d,a){a instanceof Array||(a=[a]);for(var b=!1,f=g.makeIterator(a),e=f.next();!e.done;e=f.next())if(e=e.value,d instanceof e||void 0!==d&&null!==d&&d.constructor===e){b=!0;break}if(!b)throw new TypeError(c.inspect(d)+" is not an instance of "+a.map(function(a){return a.name}).join(" or "));},integer:function(d){e.instanceOf(d,Number);if(!Number.isSafeInteger(d))throw new RangeError(c.inspect(d)+" is not an integer");},between:function(d,a,b,f){if(a<d||a>=b){d=c.inspect(a)+
" is not in ["+c.inspect(d)+","+c.inspect(b)+")";if(void 0===f)throw new RangeError(d);throw new RangeError(f+" ("+d+")");}},byteUnsignedInteger:function(d){e.integer(d);e.between(0,d,256)},twoByteUnsignedInteger:function(d){e.integer(d);e.between(0,d,65536)},fourByteUnsignedInteger:function(d){e.integer(d);e.between(0,d,4294967296)},fail:function(d){throw Error(d);},assert:function(d,a){d||e.fail(a)},throws:function(d,a){var c=!0;try{d(),c=!1}catch(f){void 0!==a&&e.message(f,a)}e.assert(c,"Should throw an error")},
equal:function(d,a){var b=new RangeError("Expected "+c.inspect(a)+" but got "+c.inspect(d));if(a&&a.constructor===Object)for(var f in a){if({}.hasOwnProperty.call(a,f))try{e.equal(d[f],a[f])}catch(q){throw b;}}else if(a&&a.constructor===Array){if(!d||d.constructor!==Array)throw b;try{e.equal(d.length,a.length)}catch(q){throw b;}for(f=0;f<a.length;f++)try{e.equal(d[f],a[f])}catch(q){throw b;}}else if(a&&a.constructor===Map){if(!d||d.constructor!==Map)throw b;try{e.equal(d.size,a.size)}catch(q){throw b;
}a=a.entries();for(d=d.entries();!(f=a.next()).done;)try{e.equal(f.value,d.next().value)}catch(q){throw b;}}else if(a&&a.constructor===Set){if(!d||d.constructor!==Set)throw b;try{e.equal(d.size,a.size)}catch(q){throw b;}a=a.values();for(d=d.values();!(f=a.next()).done;)try{e.equal(f.value,d.next().value)}catch(q){throw b;}}else if(a&&a.constructor===ArrayBuffer){if(!d||d.constructor!==ArrayBuffer)throw b;try{e.equal(d.byteLength,a.byteLength)}catch(q){throw b;}d=new Uint8Array(d);a=new Uint8Array(a);
try{for(f=0;f<a.length;f++)e.equal(d[f],a[f])}catch(q){throw b;}}else if(void 0!==a&&null!==a&&a.equals instanceof Function){var h;try{h=a.equals(d)}catch(q){throw Error("equals() is not implemented for "+c.inspect(a));}if(!h)throw b;}else if(a!==d)throw b;},message:function(d,a){e.instanceOf(a,String);e.assert(d&&d.message.startsWith(a),'Message "'+(d?d.message:"No error thrown")+'" does not start with "'+a+'"')}}},{"/lib/util-inspect.js":"/lib/util-inspect.js"}],"/lib/bit-math.js":[function(b,h){h.exports=
{dividedByEight:function(b){return b>>>3},modEight:function(b){return b&7}}},{}],"/lib/buffer-string.js":[function(b,h){(function(c){var e=b(c+"/assert.js"),d=b(c+"/growable-buffer.js");h.exports={toString:function(a){a&&a.constructor===ArrayBuffer&&(a=new Uint8Array(a));e.instanceOf(a,Uint8Array);for(var d=[],b=0;b<a.length;){var c=a[b],h=void 0,A=239<c?4:223<c?3:191<c?2:1;if(b+A<=a.length){var m,t,v;switch(A){case 1:128>c&&(h=c);break;case 2:m=a[b+1];128===(m&192)&&(c=(c&31)<<6|m&63,127<c&&(h=c));
break;case 3:m=a[b+1];t=a[b+2];128===(m&192)&&128===(t&192)&&(c=(c&15)<<12|(m&63)<<6|t&63,2047<c&&(55296>c||57343<c)&&(h=c));break;case 4:m=a[b+1],t=a[b+2],v=a[b+3],128===(m&192)&&128===(t&192)&&128===(v&192)&&(c=(c&15)<<18|(m&63)<<12|(t&63)<<6|v&63,65535<c&&1114112>c&&(h=c))}}void 0===h?(h=65533,A=1):65535<h&&(h-=65536,d.push(h>>>10&1023|55296),h=56320|h&1023);d.push(h);b+=A}a="";for(b=0;b<d.length;b+=4096)a+=String.fromCharCode.apply(String,[].concat(g.arrayFromIterable(d.slice(b,b+4096))));return a},
fromString:function(a){e.instanceOf(a,String);var b=new d;a=g.makeIterator(a);for(var c=a.next();!c.done;c=a.next())c=c.value.charCodeAt(0),128>c?b.add(c):(2048>c?b.add(192|c>>6):(55296>c||57344<=c?b.add(224|c>>12):(c=65536+((c&1023)<<10|c&1023),b.add(240|c>>18),b.add(128|c>>12&63)),b.add(128|c>>6&63)),b.add(128|c&63));return b.toBuffer()},toBinaryString:function(a){e.instanceOf(a,ArrayBuffer);var b="";a=new Uint8Array(a);a=g.makeIterator(a);for(var c=a.next();!c.done;c=a.next())b+=String.fromCharCode(c.value);
return b},fromBinaryString:function(a){e.instanceOf(a,String);for(var b=new ArrayBuffer(a.length),c=new Uint8Array(b),d=0;d<a.length;d++)c[d]=a[d].charCodeAt(0);return b}}}).call(this,"/lib")},{}],"/lib/growable-buffer.js":[function(b,h){(function(c){function e(a){a=void 0===a?10:a;try{d.integer(a),d.between(0,a,Number.MAX_SAFE_INTEGER+1)}catch(l){throw new RangeError(String(a)+" is not a valid buffer length");}this.buffer=new ArrayBuffer(a);this.size=0}var d=b(c+"/assert.js");e.prototype.grow=function(a){d.integer(a);
a>this.buffer.byteLength&&(a=new ArrayBuffer(a<<1),(new Uint8Array(a)).set((new Uint8Array(this.buffer)).subarray(0,this.size)),this.buffer=a);return this};e.prototype.set=function(a,b){d.integer(a);d.integer(b);d.between(0,a,this.size,"Index out of bounds: "+String(a));d.between(0,b,256,"Not a byte: "+String(b));(new Uint8Array(this.buffer))[a]=b;return this};e.prototype.setAll=function(a,b){d.instanceOf(b,ArrayBuffer);d.integer(a);d.between(0,a,this.size-b.byteLength+1,"Index out of bounds: "+String(a));
(new Uint8Array(this.buffer)).set(new Uint8Array(b),a);return this};e.prototype.get=function(a){d.integer(a);d.between(0,a,this.size,"Index out of bounds: "+String(a));return(new Uint8Array(this.buffer))[a]};e.prototype.add=function(a){var b=this.size,c=b+1;this.grow(c);this.size=c;(new Uint8Array(this.buffer))[b]=a;return this};e.prototype.addAll=function(a){d.instanceOf(a,ArrayBuffer);var b=this.size,c=this.size+a.byteLength;this.grow(c);this.size=c;(new Uint8Array(this.buffer)).set(new Uint8Array(a),
b);return this};e.prototype.toBuffer=function(){return this.buffer.slice(0,this.size)};g.global.Object.defineProperties(e.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.size}},rawBuffer:{configurable:!0,enumerable:!0,get:function(){return this.buffer}}});h.exports=e}).call(this,"/lib")},{}],"/lib/strint.js":[function(b,h){var c={};(function(){function b(a){return D(a)?a.length-1:a.length}function d(a,c){m(a);R(c,"number");return c>=b(a)?"0":a.charAt(a.length-c-1)}function a(a,
b){t(a);v(b);for(var c=0;c<b;c++)a="0"+a;return a}function h(b,c){t(b);v(c);return a(b,c-b.length)}function f(a,b){if(D(a)||D(b))throw Error("Both operands must be positive: "+a+" "+b);var c=Math.max(a.length,b.length);a=h(a,c);b=h(b,c);return a<b}function p(b,c){t(b);t(c);if(x(b,"0")&&x(c,"0"))return"0";for(var e=Math.max(b.length,c.length),f="",h=0,B=0,F=0;F<e;F++){for(var m=Number(d(b,F)),q=Number(d(c,F)),m=m+q+h,h=0;10<=m;)m-=10,h++;0===m?B++:(f=String(m)+a(f,B),B=0)}0<h&&(f=String(h)+a(f,B));
return f}function q(a,b){return I(a)===I(b)}function A(a,b){for(;0<b;)a+="0",b--;return a}function m(a){R(a,"string")}function t(a){m(a);if(!I.call(null,a))throw Error("Condition isPositive failed for value "+a);}function v(a){R(a,"number");if(0>a)throw Error("Expected a positive number: "+a);}function R(a,b){if(typeof a!==b)throw Error("Not a "+b+": "+a);}var K=c.subPositive=function(b,c){t(b);t(c);if(!y(b,c))throw Error("x must be greater or equal to y");for(var e=Math.max(b.length,c.length),f=
"",h=0,B=0,m=0;m<e;m++){for(var F=Number(d(b,m))-h,h=0,q=Number(d(c,m));F<q;)F+=10,h++;F=String(F-q);"0"!==F?(f=F+a(f,B),B=0):B++}return 0===f.length?"0":f},H=c.add=function(a,b){m(a);m(b);if(I(a)&&I(b))return p(a,b);if(D(a)&&D(b))return N(p(E(a),E(b)));if(G(E(a),E(b))){var c=a;a=b;b=c}b=K(E(a),E(b));return I(a)?b:N(b)},O=c.sub=function(a,b){m(a);m(b);return H(a,N(b))},C=c.timesDigit=function(c,e){t(c);R(e,"number");for(var f="",h=b(c),m=0,B=0,q=0;q<h;q++){for(var l=Number(d(c,q))*e+m,m=0;10<=l;)l-=
10,m++;0===l?B++:(f=String(l)+a(f,B),B=0)}0<m&&(f=String(m)+a(f,B));return 0===f.length?"0":f},P=c.mulPositive=function(a,c){t(a);t(c);for(var e="0",f=b(c),h=0;h<f;h++)var m=C(a,Number(d(c,h))),m=A(m,h),e=p(e,m);return e},L=c.mul=function(a,b){m(a);m(b);if(x(a,"0")||x(b,"0"))return"0";var c=P(E(a),E(b));return q(a,b)?c:N(c)},Q=c.quotientRemainderPositive=function(a,b){t(a);t(b);if(x(a,b))return["1","0"];if(X(b,a))return["0",S(a)];for(var c="0",d=a.length-b.length;;){for(var e=a.slice(0,a.length-d);y(e,
b);)e=O(e,b),c=H(c,"1");a=e+a.slice(a.length-d);if(X(b,a))return c=A(c,d),[c,S(a)];d--;c=A(c,1);if(0>d)throw Error("Illegal state");}};c.div=function(a,b,c){c=void 0===c?!1:c;m(a);m(b);var d=Q(E(a),E(b))[0];q(a,b)||(d=N(d));!c||x(L(d,b),a)||q(a,b)||(d=O(d,"1"));return d};var x=c.eq=function(a,b){return S(a)===S(b)},G=c.lt=function(a,b){return D(a)&&I(b)?!0:I(a)&&D(b)?!1:D(a)&&D(b)?!x(a,b)&&!f(E(a),E(b)):f(a,b)},y=c.ge=function(a,b){return!G(a,b)},X=c.gt=function(a,b){return x(a,b)?!1:y(a,b)},D=c.isNegative=
function(a){m(a);return 0===a.indexOf("-")},I=c.isPositive=function(a){return!D(a)},E=c.abs=function(a){return D(a)?N(a):a},N=c.negate=function(a){return"0"===a?"0":D(a)?a.slice(1):"-"+a},J=/^(-?)0*([1-9][0-9]*)$/,Z=/^0+$/,S=c.normalize=function(a){if(Z.test(a))return"0";var b=J.exec(a);if(!b)throw Error("Illegal strint format: "+a);return b[1]+b[2]}})();c.LONG_UPPER_SHIFT="4294967296";c.BYTE_SHIFT="256";h.exports=c},{}],"/lib/util-inspect.js":[function(b,h,c){c.inspect=function(b){if(void 0===b)return"undefined";
if(null===b||b.constructor===Object||b.constructor===Array||b.constructor===String||b.constructor===Number||b.constructor===Boolean||b.constructor===Date)return JSON.stringify(b);if(b.constructor===Set){var d="Set {";b=b.values();for(var a=b.next();!a.done;)d+=c.inspect(a.value),a=b.next(),a.done||(d+=", ");return d+"}"}if(b.constructor===Map){d="Map {";b=b.entries();for(a=b.next();!a.done;)d+=c.inspect(a.value[0]),d+=" \x3d\x3e ",d+=c.inspect(a.value[1]),a=b.next(),a.done||(d+=", ");return d+"}"}return b.constructor.name?
b.constructor.name+" "+JSON.stringify(b):JSON.stringify(b)}},{}],"/structure-types.js":[function(b,h){(function(c){function e(a){k.instanceOf(a,n);this.type=a}function d(a){n.call(this);k.instanceOf(a,w);this.type=a}function a(a){k.instanceOf(a,Array);try{k.byteUnsignedInteger(a.length)}catch(ja){k.fail(String(a.length)+" types is too many")}for(var b=g.makeIterator(a),c=b.next();!c.done;c=b.next())k.instanceOf(c.value,w);this.types=a}function l(a){var b=a.type;a=a.values;k.instanceOf(b,n);k.instanceOf(a,
Array);try{k.byteUnsignedInteger(a.length)}catch(ba){k.fail(String(a.length)+" values is too many")}for(var c=new Map,d=0;d<a.length;d++){var T=a[d],e=W.toBinaryString(b.valueBuffer(T));k.assert(!c.has(e),"Value is repeated: "+ca.inspect(T));c.set(e,d)}this.type=b;this.values=a;this.valueIndices=c}function f(a,b){n.call(this);k.instanceOf(a,w);k.instanceOf(b,w);this.keyType=a;this.valueType=b}function p(a){q.apply(this,arguments)}function q(a){n.call(this);k.instanceOf(a,w);this.type=a}function A(a){n.call(this);
k.instanceOf(a,Object);var b=0,c;for(c in a)({}).hasOwnProperty.call(a,c)&&b++;try{k.byteUnsignedInteger(b)}catch(ba){k.fail(String(b)+" fields is too many")}this.fields=Array(b);var b=0,d;for(d in a)if({}.hasOwnProperty.call(a,d)){c=W.fromString(d);try{k.byteUnsignedInteger(c.byteLength)}catch(ba){k.fail("Field name "+d+" is too long")}var T=a[d];try{k.instanceOf(T,w)}catch(ba){k.fail(String(T)+" is not a valid field type")}var e={};this.fields[b]=(e.name=d,e.type=T,e.buffer=c,e);b++}this.fields.sort(function(a,
b){if(a.name<b.name)return-1;if(a.name>b.name)return 1})}function m(a){var b=a.type;a=a.length;n.call(this);k.instanceOf(b,w);k.fourByteUnsignedInteger(a);this.type=b;this.length=a}function t(a){n.apply(this,arguments)}function v(a){n.apply(this,arguments)}function R(a){n.apply(this,arguments)}function K(a){n.apply(this,arguments)}function H(a){n.call(this);k.fourByteUnsignedInteger(a);this.length=a}function O(a){n.apply(this,arguments)}function C(a){L.apply(this,arguments)}function P(a){L.apply(this,
arguments)}function L(a){n.apply(this,arguments)}function Q(a){y.apply(this,arguments)}function x(a){y.apply(this,arguments)}function G(a){y.apply(this,arguments)}function y(a){n.apply(this,arguments)}function X(a){J.apply(this,arguments)}function D(a){J.apply(this,arguments)}function I(a){J.apply(this,arguments)}function E(a){J.apply(this,arguments)}function N(a){J.apply(this,arguments)}function J(a){n.apply(this,arguments)}function Z(a){M.apply(this,arguments)}function S(a){M.apply(this,arguments)}
function B(a){M.apply(this,arguments)}function F(a){M.apply(this,arguments)}function aa(a){M.apply(this,arguments)}function M(a){n.apply(this,arguments)}function n(a){w.apply(this,arguments)}function w(){}function Y(a){var b=new ArrayBuffer(4);(new DataView(b)).setUint32(0,a);return b}function U(a,b){if(b&&a.pointers){b=g.makeIterator(a.pointers);for(var c=b.next();!c.done;c=b.next()){var d=g.makeIterator(c.value),c=d.next().value,d=d.next().value,z=a.length;a.addAll(W.fromBinaryString(c));c=new ArrayBuffer(4);
(new DataView(c)).setUint32(0,z);d=g.makeIterator(d);for(z=d.next();!z.done;z=d.next())a.setAll(z.value,c)}}}function V(a){if(a&&a.constructor===String&&(a=Number(a),!isNaN(a)))return a}function ga(a,b){k.instanceOf(a,r);k.instanceOf(b,String);(u.gt(b,"9223372036854775807")||u.lt(b,"-9223372036854775808"))&&k.fail("Value out of range");var c=u.div(b,u.LONG_UPPER_SHIFT,!0);b=u.sub(b,u.mul(c,u.LONG_UPPER_SHIFT));var d=new ArrayBuffer(8),z=new DataView(d);z.setInt32(0,Number(c));z.setUint32(4,Number(b));
a.addAll(d)}function ha(a,b){k.instanceOf(b,Array);for(var c=da(b.length),d=ea(b.length),c=new ArrayBuffer(c?d+1:d),d=new Uint8Array(c),z=0;z<b.length;z++){var T=b[z];k.instanceOf(T,Boolean);var e=da(~da(z));T?d[ea(z)]|=1<<e:d[ea(z)]&=~(1<<e)}a.addAll(c)}"/"===c&&(c="");var k=b(c+"/lib/assert.js"),ka=b("base64-js"),W=b(c+"/lib/buffer-string.js"),la=b(c+"/config.js"),ma=b("sha256"),r=b(c+"/lib/growable-buffer.js"),u=b(c+"/lib/strint.js"),ca=b("/lib/util-inspect.js");c=b(c+"/lib/bit-math.js");var ea=
c.dividedByEight,da=c.modEight;w.prototype.addToBuffer=function(a){k.instanceOf(a,r);if(this.cachedTypeLocations){var b=this.cachedTypeLocations.get(a);if(void 0!==b){a.add(255);var c=new ArrayBuffer(2);try{return(new DataView(c)).setUint16(0,a.length-b),a.addAll(c),!1}catch(ja){}}}else this.cachedTypeLocations=new Map;this.cachedTypeLocations.set(a,a.length);a.add(this.constructor._value);return!0};w.prototype.toBuffer=function(){this.cachedBuffer||(this.cachedBuffer=this._toBuffer());return this.cachedBuffer};
w.prototype._toBuffer=function(){var a=new r;this.addToBuffer(a);return a.toBuffer()};w.prototype.getHash=function(){this.cachedHash||(this.cachedHash=this._getHash());return this.cachedHash};w.prototype._getHash=function(){return ka.fromByteArray(ma(this.toBuffer(),{asBytes:!0}))};w.prototype.getSignature=function(){this.cachedSignature||(this.cachedSignature=this._getSignature());return this.cachedSignature};w.prototype._getSignature=function(){return la.VERSION_STRING+this.getHash()};w.prototype.writeValue=
function(){k.fail("Generic Type has no value representation")};w.prototype.valueBuffer=function(a){var b=new r;this.writeValue(b,a);return b.toBuffer()};w.prototype.equals=function(a){try{k.instanceOf(a,this.constructor)}catch(fa){return!1}try{k.equal(a.constructor,this.constructor)}catch(fa){return!1}for(var b in this)if({}.hasOwnProperty.call(this,b)&&!b.startsWith("cached"))try{k.equal(a[b],this[b])}catch(fa){return!1}return!0};g.global.Object.defineProperties(w,{_value:{configurable:!0,enumerable:!0,
get:function(){k.fail("Generic Type has no value byte")}}});g.inherits(n,w);g.inherits(M,n);g.inherits(aa,M);aa.prototype.writeValue=function(a,b){k.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);k.integer(b);k.between(-128,b,128,"Value out of range");c=new ArrayBuffer(1);(new DataView(c)).setInt8(0,b);a.addAll(c)};g.global.Object.defineProperties(aa,{_value:{configurable:!0,enumerable:!0,get:function(){return 1}}});g.inherits(F,M);F.prototype.writeValue=function(a,b){k.instanceOf(a,r);var c=V(b);void 0!==
c&&(b=c);k.integer(b);k.between(-32768,b,32768,"Value out of range");c=new ArrayBuffer(2);(new DataView(c)).setInt16(0,b);a.addAll(c)};g.global.Object.defineProperties(F,{_value:{configurable:!0,enumerable:!0,get:function(){return 2}}});g.inherits(B,M);B.prototype.writeValue=function(a,b){k.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);k.integer(b);k.between(-2147483648,b,2147483648,"Value out of range");c=new ArrayBuffer(4);(new DataView(c)).setInt32(0,b);a.addAll(c)};g.global.Object.defineProperties(B,
{_value:{configurable:!0,enumerable:!0,get:function(){return 3}}});g.inherits(S,M);S.prototype.writeValue=function(a,b){ga(a,b)};g.global.Object.defineProperties(S,{_value:{configurable:!0,enumerable:!0,get:function(){return 4}}});g.inherits(Z,M);Z.prototype.writeValue=function(a,b){k.instanceOf(a,r);k.instanceOf(b,String);b=u.normalize(b);var c=[];if(!u.eq(b,"0")){for(;u.gt(b,"127")||u.lt(b,"-128");){var d=u.div(b,u.BYTE_SHIFT,!0);b=u.sub(b,u.mul(d,u.BYTE_SHIFT));c.push(Number(b));b=d}c.push(Number(b));
k.twoByteUnsignedInteger(c.length)}d=new ArrayBuffer(2+c.length);b=new DataView(d);b.setUint16(0,c.length);for(var e=3,z=c.length-2;-1<z;z--,e++)b.setUint8(e,c[z]);c.length&&b.setInt8(2,c[c.length-1]);a.addAll(d)};g.global.Object.defineProperties(Z,{_value:{configurable:!0,enumerable:!0,get:function(){return 5}}});g.inherits(J,n);g.inherits(N,J);N.prototype.writeValue=function(a,b){k.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);k.integer(b);k.between(0,b,256,"Value out of range");c=new ArrayBuffer(1);
(new Uint8Array(c))[0]=b;a.addAll(c)};g.global.Object.defineProperties(N,{_value:{configurable:!0,enumerable:!0,get:function(){return 17}}});g.inherits(E,J);E.prototype.writeValue=function(a,b){k.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);k.integer(b);k.between(0,b,65536,"Value out of range");c=new ArrayBuffer(2);(new DataView(c)).setUint16(0,b);a.addAll(c)};g.global.Object.defineProperties(E,{_value:{configurable:!0,enumerable:!0,get:function(){return 18}}});g.inherits(I,J);I.prototype.writeValue=
function(a,b){k.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);k.integer(b);k.between(0,b,4294967296,"Value out of range");c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,b);a.addAll(c)};g.global.Object.defineProperties(I,{_value:{configurable:!0,enumerable:!0,get:function(){return 19}}});g.inherits(D,J);D.prototype.writeValue=function(a,b){k.instanceOf(a,r);k.instanceOf(b,String);(u.gt(b,"18446744073709551615")||u.lt(b,"0"))&&k.fail("Value out of range");var c=u.div(b,u.LONG_UPPER_SHIFT);b=u.sub(b,
u.mul(c,u.LONG_UPPER_SHIFT));var d=new ArrayBuffer(8),e=new DataView(d);e.setUint32(0,Number(c));e.setUint32(4,Number(b));a.addAll(d)};g.global.Object.defineProperties(D,{_value:{configurable:!0,enumerable:!0,get:function(){return 20}}});g.inherits(X,J);X.prototype.writeValue=function(a,b){k.instanceOf(a,r);k.instanceOf(b,String);u.isNegative(b)&&k.fail("Value out of range");var c=[];if(!u.eq(b,"0")){for(;u.ge(b,u.BYTE_SHIFT);){var d=g.makeIterator(u.quotientRemainderPositive(b,u.BYTE_SHIFT));b=d.next().value;
d=d.next().value;c.push(Number(d))}c.push(Number(b));k.twoByteUnsignedInteger(c.length)}b=new ArrayBuffer(2+c.length);d=new DataView(b);d.setUint16(0,c.length);for(var e=2,f=c.length-1;-1<f;f--,e++)d.setUint8(e,c[f]);a.addAll(b)};g.global.Object.defineProperties(X,{_value:{configurable:!0,enumerable:!0,get:function(){return 21}}});g.inherits(y,n);g.inherits(G,y);G.prototype.writeValue=function(a,b){k.instanceOf(b,Date);ga(a,String(b.getTime()))};g.global.Object.defineProperties(G,{_value:{configurable:!0,
enumerable:!0,get:function(){return 26}}});g.inherits(x,y);x.prototype.writeValue=function(a,b){k.instanceOf(b,Date);b=new Date(b.getFullYear(),b.getMonth(),b.getDate());b=(b.getTime()-6E4*b.getTimezoneOffset())/864E5;var c=new ArrayBuffer(3),d=new DataView(c);d.setInt16(0,b>>8);d.setUint8(2,b&255);a.addAll(c)};g.global.Object.defineProperties(x,{_value:{configurable:!0,enumerable:!0,get:function(){return 27}}});g.inherits(Q,y);Q.prototype.writeValue=function(a,b){k.instanceOf(b,Date);var c=new ArrayBuffer(4);
(new DataView(c)).setUint32(0,b.getTime()%864E5);a.addAll(c)};g.global.Object.defineProperties(Q,{_value:{configurable:!0,enumerable:!0,get:function(){return 28}}});g.inherits(L,n);g.inherits(P,L);P.prototype.writeValue=function(a,b){k.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);k.instanceOf(b,Number);c=new ArrayBuffer(4);(new DataView(c)).setFloat32(0,b);a.addAll(c)};g.global.Object.defineProperties(P,{_value:{configurable:!0,enumerable:!0,get:function(){return 32}}});g.inherits(C,L);C.prototype.writeValue=
function(a,b){k.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);k.instanceOf(b,Number);c=new ArrayBuffer(8);(new DataView(c)).setFloat64(0,b);a.addAll(c)};g.global.Object.defineProperties(C,{_value:{configurable:!0,enumerable:!0,get:function(){return 33}}});g.inherits(O,n);O.prototype.writeValue=function(a,b){k.instanceOf(a,r);k.instanceOf(b,Boolean);b?a.add(255):a.add(0)};g.global.Object.defineProperties(O,{_value:{configurable:!0,enumerable:!0,get:function(){return 48}}});g.inherits(H,n);H.prototype.addToBuffer=
function(a){n.prototype.addToBuffer.call(this,a)&&a.addAll(Y(this.length))};H.prototype.writeValue=function(a,b){k.instanceOf(a,r);k.instanceOf(b,Array);b.length!==this.length&&k.fail("Length does not match");ha(a,b)};g.global.Object.defineProperties(H,{_value:{configurable:!0,enumerable:!0,get:function(){return 49}}});g.inherits(K,n);K.prototype.writeValue=function(a,b){k.instanceOf(b,Array);k.fourByteUnsignedInteger(b.length);a.addAll(Y(b.length));ha(a,b)};g.global.Object.defineProperties(K,{_value:{configurable:!0,
enumerable:!0,get:function(){return 50}}});g.inherits(R,n);R.prototype.writeValue=function(a,b){k.instanceOf(a,r);k.instanceOf(b,String);k.assert(1===b.length,"String must contain only 1 character");a.addAll(W.fromString(b))};g.global.Object.defineProperties(R,{_value:{configurable:!0,enumerable:!0,get:function(){return 64}}});g.inherits(v,n);v.prototype.writeValue=function(a,b){k.instanceOf(a,r);k.instanceOf(b,String);b=W.fromString(b);a.addAll(b);a.add(0)};g.global.Object.defineProperties(v,{_value:{configurable:!0,
enumerable:!0,get:function(){return 65}}});g.inherits(t,n);t.prototype.writeValue=function(a,b){k.instanceOf(a,r);k.instanceOf(b,ArrayBuffer);k.fourByteUnsignedInteger(b.byteLength);a.addAll(Y(b.byteLength));a.addAll(b)};g.global.Object.defineProperties(t,{_value:{configurable:!0,enumerable:!0,get:function(){return 66}}});g.inherits(m,n);m.prototype.addToBuffer=function(a){n.prototype.addToBuffer.call(this,a)&&(this.type.addToBuffer(a),a.addAll(Y(this.length)))};m.prototype.writeValue=function(a,
b,c){c=void 0===c?!0:c;k.instanceOf(a,r);k.instanceOf(b,Array);b.length!==this.length&&k.fail("Length does not match: expected "+String(this.length)+" but got "+b.length);b=g.makeIterator(b);for(var d=b.next();!d.done;d=b.next())this.type.writeValue(a,d.value,!1);U(a,c)};g.global.Object.defineProperties(m,{_value:{configurable:!0,enumerable:!0,get:function(){return 80}}});g.inherits(A,n);A.prototype.addToBuffer=function(a){if(n.prototype.addToBuffer.call(this,a)){a.add(this.fields.length);for(var b=
g.makeIterator(this.fields),c=b.next();!c.done;c=b.next()){var c=c.value,d=c.buffer;a.add(d.byteLength);a.addAll(d);c.type.addToBuffer(a)}}};A.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;k.instanceOf(a,r);k.instanceOf(b,Object);for(var d=g.makeIterator(this.fields),e=d.next();!e.done;e=d.next()){var e=e.value,f=b[e.name];void 0===f&&k.fail("Value for field "+e.name+" missing");e.type.writeValue(a,f,!1)}U(a,c)};g.global.Object.defineProperties(A,{_value:{configurable:!0,enumerable:!0,get:function(){return 81}}});
g.inherits(q,n);q.prototype.addToBuffer=function(a){n.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};q.prototype._writeValue=function(a,b,c){k.instanceOf(a,r);k.fourByteUnsignedInteger(b.length);a.addAll(Y(b.length));b=g.makeIterator(b);for(var d=b.next();!d.done;d=b.next())this.type.writeValue(a,d.value,!1);U(a,c)};q.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;k.instanceOf(b,Array);this._writeValue(a,b,c)};g.global.Object.defineProperties(q,{_value:{configurable:!0,enumerable:!0,
get:function(){return 82}}});g.inherits(p,q);p.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;k.instanceOf(b,Set);b.length=b.size;this._writeValue(a,b,c)};g.global.Object.defineProperties(p,{_value:{configurable:!0,enumerable:!0,get:function(){return 83}}});g.inherits(f,n);f.prototype.addToBuffer=function(a){n.prototype.addToBuffer.call(this,a)&&(this.keyType.addToBuffer(a),this.valueType.addToBuffer(a))};f.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;k.instanceOf(a,r);k.instanceOf(b,
Map);k.fourByteUnsignedInteger(b.size);a.addAll(Y(b.size));b=g.makeIterator(b);for(var d=b.next();!d.done;d=b.next()){var e=g.makeIterator(d.value),d=e.next().value,e=e.next().value;this.keyType.writeValue(a,d,!1);this.valueType.writeValue(a,e,!1)}U(a,c)};g.global.Object.defineProperties(f,{_value:{configurable:!0,enumerable:!0,get:function(){return 84}}});g.inherits(l,w);l.prototype.addToBuffer=function(a){if(w.prototype.addToBuffer.call(this,a)){this.type.addToBuffer(a);a.add(this.valueIndices.size);
for(var b=g.makeIterator(this.valueIndices),c=b.next();!c.done;c=b.next()){var c=g.makeIterator(c.value),d=c.next().value;c.next();a.addAll(W.fromBinaryString(d))}}};l.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;k.instanceOf(a,r);var d=new r;this.type.writeValue(d,b,!1);d=this.valueIndices.get(W.toBinaryString(d.toBuffer()));k.assert(void 0!==d,"Not a valid enum value: "+ca.inspect(b));a.add(d);U(a,c)};g.global.Object.defineProperties(l,{_value:{configurable:!0,enumerable:!0,get:function(){return 85}}});
g.inherits(a,w);a.prototype.addToBuffer=function(a){if(w.prototype.addToBuffer.call(this,a)){a.add(this.types.length);for(var b=g.makeIterator(this.types),c=b.next();!c.done;c=b.next())c.value.addToBuffer(a)}};a.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;k.instanceOf(a,r);for(var d=!1,e=0;e<this.types.length;e++){var f=this.types[e],h=new r;try{f.writeValue(h,b,!1)}catch(na){continue}a.add(e);a.addAll(h.toBuffer());d=!0;break}d||k.fail("No types matched: "+ca.inspect(b));U(a,c)};g.global.Object.defineProperties(a,
{_value:{configurable:!0,enumerable:!0,get:function(){return 86}}});g.inherits(d,n);d.prototype.addToBuffer=function(a){n.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};d.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;k.instanceOf(a,r);null===b?a.add(0):(a.add(255),this.type.writeValue(a,b,!1));U(a,c)};g.global.Object.defineProperties(d,{_value:{configurable:!0,enumerable:!0,get:function(){return 96}}});g.inherits(e,w);e.prototype.addToBuffer=function(a){w.prototype.addToBuffer.call(this,
a)&&this.type.addToBuffer(a)};e.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;a.pointers||(a.pointers=new Map);var d=new r;this.type.writeValue(d,b,!1);b=W.toBinaryString(d.toBuffer());var d=a.length,e=a.pointers.get(b);e?e.add(d):a.pointers.set(b,new Set([d]));a.addAll(new ArrayBuffer(4));U(a,c)};g.global.Object.defineProperties(e,{_value:{configurable:!0,enumerable:!0,get:function(){return 112}}});h.exports={Type:w,ByteType:aa,ShortType:F,IntType:B,LongType:S,BigIntType:Z,UnsignedByteType:N,
UnsignedShortType:E,UnsignedIntType:I,UnsignedLongType:D,BigUnsignedIntType:X,DateType:G,DayType:x,TimeType:Q,FloatType:P,DoubleType:C,BooleanType:O,BooleanTupleType:H,BooleanArrayType:K,CharType:R,StringType:v,OctetsType:t,TupleType:m,StructType:A,ArrayType:q,SetType:p,MapType:f,EnumType:l,ChoiceType:a,OptionalType:d,PointerType:e,REPEATED_TYPE:255,MILLIS_PER_DAY:864E5,MILLIS_PER_MINUTE:6E4}}).call(this,"/")},{"/lib/util-inspect.js":"/lib/util-inspect.js","base64-js":2,sha256:5}],1:[function(b){(function(){b("/client-side/common.js");
var h=b("/lib/assert.js");sb.upload=function(b,e){var c=b.type;b=b.value;h.instanceOf(c,sb.Type);h.instanceOf(e,Object);"POST"!==e.type&&"POST"!==e.method&&h.fail("Must use POST when uploading");e.processData=!1;e.data=c.valueBuffer(b);$.ajax(e)}})()},{"/client-side/common.js":"/client-side/common.js","/lib/assert.js":"/lib/assert.js"}],2:[function(b,h,c){function e(a){var b=a.length;if(0<b%4)throw Error("Invalid string. Length must be a multiple of 4");return"\x3d"===a[b-2]?2:"\x3d"===a[b-1]?1:0}
function d(b,c,d){for(var e=[],f=c;f<d;f+=3)c=(b[f]<<16)+(b[f+1]<<8)+b[f+2],e.push(a[c>>18&63]+a[c>>12&63]+a[c>>6&63]+a[c&63]);return e.join("")}c.byteLength=function(a){return 3*a.length/4-e(a)};c.toByteArray=function(a){var b,c,d,h,v;b=a.length;h=e(a);v=new f(3*b/4-h);c=0<h?b-4:b;var p=0;for(b=0;b<c;b+=4)d=l[a.charCodeAt(b)]<<18|l[a.charCodeAt(b+1)]<<12|l[a.charCodeAt(b+2)]<<6|l[a.charCodeAt(b+3)],v[p++]=d>>16&255,v[p++]=d>>8&255,v[p++]=d&255;2===h?(d=l[a.charCodeAt(b)]<<2|l[a.charCodeAt(b+1)]>>
4,v[p++]=d&255):1===h&&(d=l[a.charCodeAt(b)]<<10|l[a.charCodeAt(b+1)]<<4|l[a.charCodeAt(b+2)]>>2,v[p++]=d>>8&255,v[p++]=d&255);return v};c.fromByteArray=function(b){for(var c=b.length,e=c%3,f="",h=[],l=0,p=c-e;l<p;l+=16383)h.push(d(b,l,l+16383>p?p:l+16383));1===e?(b=b[c-1],f+=a[b>>2],f+=a[b<<4&63],f+="\x3d\x3d"):2===e&&(b=(b[c-2]<<8)+b[c-1],f+=a[b>>10],f+=a[b>>4&63],f+=a[b<<2&63],f+="\x3d");h.push(f);return h.join("")};var a=[],l=[],f="undefined"!==typeof Uint8Array?Uint8Array:Array;for(b=0;64>b;++b)a[b]=
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[b],l["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(b)]=b;l[45]=62;l[95]=63},{}],3:[function(b,h){!function(b){function c(a){return a.map(function(a){a=a.toString(16);a=2<a.length?a:Array(2-a.length+1).join("0")+a;return a}).join("")}var d={bytesToHex:function(a){return c(a)},hexToBytes:function(a){if(1===a.length%2)throw Error("hexToBytes can't have a string with an odd number of characters.");0===a.indexOf("0x")&&
(a=a.slice(2));return a.match(/../g).map(function(a){return parseInt(a,16)})}};"undefined"!==typeof h&&h.exports?h.exports=d:b.convertHex=d}(this)},{}],4:[function(b,h){!function(b){var c={bytesToString:function(b){return b.map(function(a){return String.fromCharCode(a)}).join("")},stringToBytes:function(b){return b.split("").map(function(a){return a.charCodeAt(0)})},UTF8:{bytesToString:function(b){return decodeURIComponent(escape(c.bytesToString(b)))},stringToBytes:function(b){return c.stringToBytes(unescape(encodeURIComponent(b)))}}};
"undefined"!==typeof h&&h.exports?h.exports=c:b.convertString=c}(this)},{}],5:[function(b,h){!function(c){function e(b,c){b.constructor===String&&(b=d.convertString.UTF8.stringToBytes(b));for(var e=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225],f=b,h=[],t=0,v=0;t<f.length;t++,v+=8)h[v>>>5]|=f[t]<<24-v%32;b=8*b.length;h[b>>5]|=128<<24-b%32;h[(b+64>>9<<4)+15]=b;for(b=0;b<h.length;b+=16){for(var f=e,t=h,v=b,p=f[0],K=f[1],H=f[2],O=f[3],C=f[4],P=f[5],L=f[6],Q=
f[7],x=0;64>x;x++){if(16>x)l[x]=t[v+x]|0;else{var G=l[x-15],y=l[x-2];l[x]=((G<<25|G>>>7)^(G<<14|G>>>18)^G>>>3)+l[x-7]+((y<<15|y>>>17)^(y<<13|y>>>19)^y>>>10)+l[x-16]}G=Q+((C<<26|C>>>6)^(C<<21|C>>>11)^(C<<7|C>>>25))+(C&P^~C&L)+a[x]+l[x];y=((p<<30|p>>>2)^(p<<19|p>>>13)^(p<<10|p>>>22))+(p&K^p&H^K&H);Q=L;L=P;P=C;C=O+G|0;O=H;H=K;K=p;p=G+y|0}f[0]=f[0]+p|0;f[1]=f[1]+K|0;f[2]=f[2]+H|0;f[3]=f[3]+O|0;f[4]=f[4]+C|0;f[5]=f[5]+P|0;f[6]=f[6]+L|0;f[7]=f[7]+Q|0}h=[];for(b=0;b<32*e.length;b+=8)h.push(e[b>>>5]>>>24-
b%32&255);return c&&c.asBytes?h:c&&c.asString?d.convertString.bytesToString(h):d.bytesToHex(h)}var d={};"undefined"!==typeof h&&h.exports?(d.bytesToHex=b("convert-hex").bytesToHex,d.convertString=b("convert-string"),h.exports=e):(d.bytesToHex=c.convertHex.bytesToHex,d.convertString=c.convertString,c.sha256=e);var a=[];!function(){function b(a){for(var b=Math.sqrt(a),c=2;c<=b;c++)if(!(a%c))return!1;return!0}function c(a){return 4294967296*(a-(a|0))|0}for(var d=2,e=0;64>e;)b(d)&&(a[e]=c(Math.pow(d,
1/3)),e++),d++}();var l=[];e.x2=function(a,b){return e(e(a,{asBytes:!0}),b)}}(this)},{"convert-hex":3,"convert-string":4}]},{},[1]);}()