!function(){var f={scope:{}};f.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,g,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[g]=a.value)};f.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};f.global=f.getGlobal(this);f.SYMBOL_PREFIX="jscomp_symbol_";
f.initSymbol=function(){f.initSymbol=function(){};f.global.Symbol||(f.global.Symbol=f.Symbol)};f.symbolCounter_=0;f.Symbol=function(c){return f.SYMBOL_PREFIX+(c||"")+f.symbolCounter_++};f.initSymbolIterator=function(){f.initSymbol();var c=f.global.Symbol.iterator;c||(c=f.global.Symbol.iterator=f.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&f.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return f.arrayIterator(this)}});f.initSymbolIterator=function(){}};
f.arrayIterator=function(c){var g=0;return f.iteratorPrototype(function(){return g<c.length?{done:!1,value:c[g++]}:{done:!0}})};f.iteratorPrototype=function(c){f.initSymbolIterator();c={next:c};c[f.global.Symbol.iterator]=function(){return this};return c};f.makeIterator=function(c){f.initSymbolIterator();f.initSymbol();f.initSymbolIterator();var g=c[Symbol.iterator];return g?g.call(c):f.arrayIterator(c)};f.arrayFromIterator=function(c){for(var g,a=[];!(g=c.next()).done;)a.push(g.value);return a};
f.arrayFromIterable=function(c){return c instanceof Array?c:f.arrayFromIterator(f.makeIterator(c))};f.inherits=function(c,g){function a(){}a.prototype=g.prototype;c.prototype=new a;c.prototype.constructor=c;for(var e in g)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(g,e);d&&Object.defineProperty(c,e,d)}else c[e]=g[e]};f.owns=function(c,g){return Object.prototype.hasOwnProperty.call(c,g)};
f.polyfill=function(c,g){if(g){var a=f.global;c=c.split(".");for(var e=0;e<c.length-1;e++){var d=c[e];d in a||(a[d]={});a=a[d]}c=c[c.length-1];e=a[c];g=g(e);g!=e&&null!=g&&f.defineProperty(a,c,{configurable:!0,writable:!0,value:g})}};
f.polyfill("WeakMap",function(c){function g(a){this.id_=(b+=Math.random()+1).toString();if(a){f.initSymbol();f.initSymbolIterator();a=f.makeIterator(a);for(var k;!(k=a.next()).done;)k=k.value,this.set(k[0],k[1])}}function a(b){f.owns(b,d)||f.defineProperty(b,d,{value:{}})}function e(b){var k=Object[b];k&&(Object[b]=function(b){a(b);return k(b)})}if(function(){if(!c||!Object.seal)return!1;try{var b=Object.seal({}),a=Object.seal({}),d=new c([[b,2],[a,3]]);if(2!=d.get(b)||3!=d.get(a))return!1;d.delete(b);
d.set(a,4);return!d.has(b)&&4==d.get(a)}catch(R){return!1}}())return c;var d="$jscomp_hidden_"+Math.random().toString().substring(2);e("freeze");e("preventExtensions");e("seal");var b=0;g.prototype.set=function(b,k){a(b);if(!f.owns(b,d))throw Error("WeakMap key fail: "+b);b[d][this.id_]=k;return this};g.prototype.get=function(b){return f.owns(b,d)?b[d][this.id_]:void 0};g.prototype.has=function(b){return f.owns(b,d)&&f.owns(b[d],this.id_)};g.prototype.delete=function(b){return f.owns(b,d)&&f.owns(b[d],
this.id_)?delete b[d][this.id_]:!1};return g},"es6-impl","es3");f.ASSUME_NO_NATIVE_MAP=!1;
f.polyfill("Map",function(c){function g(){var b={};return b.previous=b.next=b.head=b}function a(b,a){var d=b.head_;return f.iteratorPrototype(function(){if(d){for(;d.head!=b.head_;)d=d.previous;for(;d.next!=d.head;)return d=d.next,{done:!1,value:a(d)};d=null}return{done:!0,value:void 0}})}function e(a,d){var k;k=d&&typeof d;"object"==k||"function"==k?b.has(d)?k=b.get(d):(k=""+ ++m,b.set(d,k)):k="p_"+d;var c=a.data_[k];if(c&&f.owns(a.data_,k))for(a=0;a<c.length;a++){var e=c[a];if(d!==d&&e.key!==e.key||
d===e.key)return{id:k,list:c,index:a,entry:e}}return{id:k,list:c,index:-1,entry:void 0}}function d(b){this.data_={};this.head_=g();this.size=0;if(b){b=f.makeIterator(b);for(var a;!(a=b.next()).done;)a=a.value,this.set(a[0],a[1])}}if(!f.ASSUME_NO_NATIVE_MAP&&function(){if(!c||!c.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),a=new c(f.makeIterator([[b,"s"]]));if("s"!=a.get(b)||1!=a.size||a.get({x:4})||a.set({x:4},"t")!=a||2!=a.size)return!1;var d=a.entries(),
e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(n){return!1}}())return c;f.initSymbol();f.initSymbolIterator();var b=new WeakMap;d.prototype.set=function(b,a){var d=e(this,b);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=a:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:b,value:a},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,
this.size++);return this};d.prototype.delete=function(b){b=e(this,b);return b.entry&&b.list?(b.list.splice(b.index,1),b.list.length||delete this.data_[b.id],b.entry.previous.next=b.entry.next,b.entry.next.previous=b.entry.previous,b.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};d.prototype.has=function(b){return!!e(this,b).entry};d.prototype.get=function(b){return(b=e(this,b).entry)&&b.value};d.prototype.entries=function(){return a(this,
function(b){return[b.key,b.value]})};d.prototype.keys=function(){return a(this,function(b){return b.key})};d.prototype.values=function(){return a(this,function(b){return b.value})};d.prototype.forEach=function(b,a){for(var d=this.entries(),c;!(c=d.next()).done;)c=c.value,b.call(a,c[1],c[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var m=0;return d},"es6-impl","es3");f.ASSUME_NO_NATIVE_SET=!1;
f.polyfill("Set",function(c){function g(a){this.map_=new Map;if(a){a=f.makeIterator(a);for(var c;!(c=a.next()).done;)this.add(c.value)}this.size=this.map_.size}if(!f.ASSUME_NO_NATIVE_SET&&function(){if(!c||!c.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),e=new c(f.makeIterator([a]));if(!e.has(a)||1!=e.size||e.add(a)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var d=e.entries(),b=d.next();if(b.done||b.value[0]!=a||b.value[1]!=a)return!1;b=d.next();return b.done||
b.value[0]==a||4!=b.value[0].x||b.value[1]!=b.value[0]?!1:d.next().done}catch(m){return!1}}())return c;f.initSymbol();f.initSymbolIterator();g.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};g.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};g.prototype.clear=function(){this.map_.clear();this.size=0};g.prototype.has=function(a){return this.map_.has(a)};g.prototype.entries=function(){return this.map_.entries()};g.prototype.values=
function(){return this.map_.values()};g.prototype[Symbol.iterator]=g.prototype.values;g.prototype.forEach=function(a,c){var d=this;this.map_.forEach(function(b){return a.call(c,b,b,d)})};return g},"es6-impl","es3");f.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");f.polyfill("Number.isFinite",function(c){return c?c:function(c){return"number"!==typeof c?!1:!isNaN(c)&&Infinity!==c&&-Infinity!==c}},"es6-impl","es3");
f.polyfill("Number.isInteger",function(c){return c?c:function(c){return Number.isFinite(c)?c===Math.floor(c):!1}},"es6-impl","es3");f.polyfill("Number.isSafeInteger",function(c){return c?c:function(c){return Number.isInteger(c)&&Math.abs(c)<=Number.MAX_SAFE_INTEGER}},"es6-impl","es3");f.array=f.array||{};
f.iteratorFromArray=function(c,g){f.initSymbolIterator();c instanceof String&&(c+="");var a=0,e={next:function(){if(a<c.length){var d=a++;return{value:g(d,c[d]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};f.polyfill("Array.prototype.entries",function(c){return c?c:function(){return f.iteratorFromArray(this,function(c,a){return[c,a]})}},"es6-impl","es3");
f.polyfill("Array.prototype.values",function(c){return c?c:function(){return f.iteratorFromArray(this,function(c,a){return a})}},"es6","es3");f.checkStringArgs=function(c,g,a){if(null==c)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(g instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return c+""};
f.polyfill("String.prototype.startsWith",function(c){return c?c:function(c,a){var e=f.checkStringArgs(this,c,"startsWith");c+="";var d=e.length,b=c.length;a=Math.max(0,Math.min(a|0,e.length));for(var m=0;m<b&&a<d;)if(e[a++]!=c[m++])return!1;return m>=b}},"es6-impl","es3");
require=function qa(g,a,e){function d(k,m){if(!a[k]){if(!g[k]){var l="function"==typeof require&&require;if(!m&&l)return l(k,!0);if(b)return b(k,!0);m=Error("Cannot find module '"+k+"'");throw m.code="MODULE_NOT_FOUND",m;}m=a[k]={exports:{}};g[k][0].call(m.exports,function(b){var a=g[k][1][b];return d(a?a:b)},m,m.exports,qa,g,a,e)}return a[k].exports}for(var b="function"==typeof require&&require,m=0;m<e.length;m++)d(e[m]);return d}({"/client-side/binary-ajax.js":[function(){(function(c){c.ajaxTransport("+*",
function(c){if(window.FormData&&("blob"===c.dataType||"arraybuffer"===c.dataType||c.data&&(window.Blob&&c.data instanceof Blob||window.ArrayBuffer&&c.data instanceof ArrayBuffer))){var a;return{send:function(e,d){var b=c.url||location.href,m=c.type||"GET",k=c.dataType||"text",l=c.data||null,g=c.async||!0;a=new XMLHttpRequest;a.addEventListener("load",function(){var b={};200<=a.status&&300>a.status||304===a.status?b[k]=a.response:b.text=a.statusText;d(a.status,a.statusText,b,a.getAllResponseHeaders())});
a.open(m,b,g);a.responseType=k;for(var x in e)({}).hasOwnProperty.call(e,x)&&a.setRequestHeader(x,e[x]);a.send(l)},abort:function(){a&&a.abort()}}}})})(jQuery)},{}],"/client-side/common.js":[function(c){var g=c("/lib/assert.js");g.instanceOf(window.Map,Function);g.instanceOf(window.Set,Function);g.instanceOf(window.ArrayBuffer,Function);g.instanceOf(window.Uint8Array,Function);g.instanceOf(window.Symbol,Function);c("/client-side/binary-ajax.js");if(!window.sb){window.sb=c("/structure-types.js");c=
c("/recursive-registry.js");for(var a in c)({}).hasOwnProperty.call(c,a)&&(window.sb[a]=c[a])}else if(!(window.sb instanceof Object))throw Error("window.sb is already defined");},{"/client-side/binary-ajax.js":"/client-side/binary-ajax.js","/lib/assert.js":"/lib/assert.js","/recursive-registry.js":"/recursive-registry.js","/structure-types.js":"/structure-types.js"}],"/config.js":[function(c,g){var a="/";"/"===a&&(a="");a=c(a+"/lib/assert.js");c=c("base64-js");a.between(0,9,65536);a=new ArrayBuffer(2);
(new DataView(a)).setUint16(0,9);c=c.fromByteArray(new Uint8Array(a));g.exports={VERSION_STRING:c}},{"base64-js":2}],"/lib/assert.js":[function(c,g){function a(){}var e=c("/lib/util-inspect.js");a.instanceOf=function(a,b){b instanceof Array||(b=[b]);for(var d=!1,c=f.makeIterator(b),l=c.next();!l.done;l=c.next())if(l=l.value,a instanceof l||void 0!==a&&null!==a&&a.constructor===l){d=!0;break}if(!d)throw new TypeError(e.inspect(a)+" is not an instance of "+b.map(function(b){return b.name}).join(" or "));
};a.integer=function(d){a.instanceOf(d,Number);if(!Number.isSafeInteger(d))throw new RangeError(e.inspect(d)+" is not an integer");};a.between=function(a,b,c,k){if(b<a||b>=c){a=e.inspect(b)+" is not in ["+e.inspect(a)+","+e.inspect(c)+")";if(void 0===k)throw new RangeError(a);throw new RangeError(k+" ("+a+")");}};a.byteUnsignedInteger=function(d){a.integer(d);a.between(0,d,256)};a.twoByteUnsignedInteger=function(d){a.integer(d);a.between(0,d,65536)};a.fourByteUnsignedInteger=function(d){a.integer(d);
a.between(0,d,4294967296)};a.fail=function(a){throw Error(a);};a.assert=function(d,b){d||a.fail(b)};a.throws=function(d,b){var c=!0;try{d(),c=!1}catch(k){void 0!==b&&a.message(k,b)}a.assert(c,"Should throw an error")};a.equal=function(d,b){var c=new RangeError("Expected "+e.inspect(b)+" but got "+e.inspect(d));if(b){var k=!0;switch(b.constructor){case Object:if(!d||d.constructor!==Object)throw c;for(var l in b)if({}.hasOwnProperty.call(b,l))try{a.equal(d[l],b[l])}catch(q){throw c;}break;case Array:if(!d||
d.constructor!==Array)throw c;try{a.equal(d.length,b.length)}catch(q){throw c;}for(l=0;l<b.length;l++)try{a.equal(d[l],b[l])}catch(q){throw c;}break;case Map:if(!d||d.constructor!==Map)throw c;try{a.equal(d.size,b.size)}catch(q){throw c;}l=b.entries();for(var g=d.entries(),x;!(x=l.next()).done;)try{a.equal(x.value,g.next().value)}catch(q){throw c;}break;case Set:if(!d||d.constructor!==Set)throw c;try{a.equal(d.size,b.size)}catch(q){throw c;}l=b.values();for(g=d.values();!(x=l.next()).done;)try{a.equal(x.value,
g.next().value)}catch(q){throw c;}break;case ArrayBuffer:if(!d||d.constructor!==ArrayBuffer)throw c;try{a.equal(d.byteLength,b.byteLength)}catch(q){throw c;}d=new Uint8Array(d);b=new Uint8Array(b);try{for(l=0;l<b.length;l++)a.equal(d[l],b[l])}catch(q){throw c;}break;case Function:if(!d||d.constructor!==Function)throw c;try{a.equal(d.name,b.name)}catch(q){throw c;}break;default:k=!1}if(k)return}if(void 0!==b&&null!==b&&b.equals instanceof Function){var n;try{n=b.equals(d)}catch(q){throw Error("equals() is not implemented for "+
e.inspect(b));}if(!n)throw c;}else if(b!==d)throw c;};a.message=function(c,b){a.instanceOf(b,String);a.assert(c&&c.message.startsWith(b),'Message "'+(c?c.message:"No error thrown")+'" does not start with "'+b+'"')};g.exports=a},{"/lib/util-inspect.js":"/lib/util-inspect.js"}],"/lib/bit-math.js":[function(c,g){g.exports={dividedByEight:function(a){return a>>>3},modEight:function(a){return a&7}}},{}],"/lib/buffer-string.js":[function(c,g){(function(a){var e=c(a+"/assert.js"),d=c(a+"/growable-buffer.js");
g.exports={toString:function(b){b&&b.constructor===ArrayBuffer&&(b=new Uint8Array(b));e.instanceOf(b,Uint8Array);for(var a=[],c=0;c<b.length;){var d=b[c],g=void 0,x=239<d?4:223<d?3:191<d?2:1;if(c+x<=b.length){var n,q,A;switch(x){case 1:128>d&&(g=d);break;case 2:n=b[c+1];128===(n&192)&&(d=(d&31)<<6|n&63,127<d&&(g=d));break;case 3:n=b[c+1];q=b[c+2];128===(n&192)&&128===(q&192)&&(d=(d&15)<<12|(n&63)<<6|q&63,2047<d&&(55296>d||57343<d)&&(g=d));break;case 4:n=b[c+1],q=b[c+2],A=b[c+3],128===(n&192)&&128===
(q&192)&&128===(A&192)&&(d=(d&15)<<18|(n&63)<<12|(q&63)<<6|A&63,65535<d&&1114112>d&&(g=d))}}void 0===g?(g=65533,x=1):65535<g&&(g-=65536,a.push(g>>>10&1023|55296),g=56320|g&1023);a.push(g);c+=x}b="";for(c=0;c<a.length;c+=4096)b+=String.fromCharCode.apply(String,[].concat(f.arrayFromIterable(a.slice(c,c+4096))));return b},fromString:function(b){e.instanceOf(b,String);var a=new d;b=f.makeIterator(b);for(var c=b.next();!c.done;c=b.next())c=c.value.charCodeAt(0),128>c?a.add(c):(2048>c?a.add(192|c>>6):
(55296>c||57344<=c?a.add(224|c>>12):(c=65536+((c&1023)<<10|c&1023),a.add(240|c>>18),a.add(128|c>>12&63)),a.add(128|c>>6&63)),a.add(128|c&63));return a.toBuffer()},toBinaryString:function(b){e.instanceOf(b,ArrayBuffer);var a="";b=new Uint8Array(b);b=f.makeIterator(b);for(var c=b.next();!c.done;c=b.next())a+=String.fromCharCode(c.value);return a},fromBinaryString:function(b){e.instanceOf(b,String);for(var a=new ArrayBuffer(b.length),c=new Uint8Array(a),d=0;d<b.length;d++)c[d]=b[d].charCodeAt(0);return a}}}).call(this,
"/lib")},{}],"/lib/growable-buffer.js":[function(c,g){(function(a){function e(b){b=void 0===b?10:b;try{d.integer(b),d.between(0,b,Number.MAX_SAFE_INTEGER+1)}catch(m){throw new RangeError(String(b)+" is not a valid buffer length");}this.buffer=new ArrayBuffer(b);this.size=0}var d=c(a+"/assert.js");e.prototype.grow=function(b){d.integer(b);b>this.buffer.byteLength&&(b=new ArrayBuffer(b<<1),(new Uint8Array(b)).set((new Uint8Array(this.buffer)).subarray(0,this.size)),this.buffer=b);return this};e.prototype.set=
function(b,a){d.integer(b);d.between(0,b,this.size,"Index out of bounds: "+String(b));d.integer(a);d.between(0,a,256,"Not a byte: "+String(a));(new Uint8Array(this.buffer))[b]=a;return this};e.prototype.setAll=function(b,a){d.instanceOf(a,ArrayBuffer);d.integer(b);d.between(0,b,this.size-a.byteLength+1,"Index out of bounds: "+String(b));(new Uint8Array(this.buffer)).set(new Uint8Array(a),b);return this};e.prototype.get=function(b){d.integer(b);d.between(0,b,this.size,"Index out of bounds: "+String(b));
return(new Uint8Array(this.buffer))[b]};e.prototype.add=function(b){d.integer(b);d.between(0,b,256,"Not a byte: "+String(b));var a=this.size,c=a+1;this.grow(c);this.size=c;(new Uint8Array(this.buffer))[a]=b;return this};e.prototype.addAll=function(b){d.instanceOf(b,ArrayBuffer);var a=this.size,c=this.size+b.byteLength;this.grow(c);this.size=c;(new Uint8Array(this.buffer)).set(new Uint8Array(b),a);return this};e.prototype.toBuffer=function(){return this.buffer.slice(0,this.size)};f.global.Object.defineProperties(e.prototype,
{length:{configurable:!0,enumerable:!0,get:function(){return this.size}},rawBuffer:{configurable:!0,enumerable:!0,get:function(){return this.buffer}}});g.exports=e}).call(this,"/lib")},{}],"/lib/strint.js":[function(c,g){var a={};(function(){function c(b){return z(b)?b.length-1:b.length}function d(b,a){n(b);u(a,"number");return a>=c(b)?"0":b.charAt(b.length-a-1)}function b(b,a){q(b);A(a);for(var c=0;c<a;c++)b="0"+b;return b}function g(a,c){q(a);A(c);return b(a,c-a.length)}function k(b,a){if(z(b)||
z(a))throw Error("Both operands must be positive: "+b+" "+a);var c=Math.max(b.length,a.length);b=g(b,c);a=g(a,c);return b<a}function l(a,c){q(a);q(c);if(v(a,"0")&&v(c,"0"))return"0";for(var e=Math.max(a.length,c.length),g="",y=0,k=0,l=0;l<e;l++){for(var L=Number(d(a,l)),n=Number(d(c,l)),L=L+n+y,y=0;10<=L;)L-=10,y++;0===L?k++:(g=String(L)+b(g,k),k=0)}0<y&&(g=String(y)+b(g,k));return g}function R(b,a){return I(b)===I(a)}function x(b,a){for(;0<a;)b+="0",a--;return b}function n(b){u(b,"string")}function q(b){n(b);
if(!I.call(null,b))throw Error("Condition isPositive failed for value "+b);}function A(b){u(b,"number");if(0>b)throw Error("Expected a positive number: "+b);}function u(b,a){if(typeof b!==a)throw Error("Not a "+a+": "+b);}var K=a.subPositive=function(a,c){q(a);q(c);if(!F(a,c))throw Error("x must be greater or equal to y");for(var e=Math.max(a.length,c.length),g="",k=0,l=0,y=0;y<e;y++){for(var n=Number(d(a,y))-k,k=0,m=Number(d(c,y));n<m;)n+=10,k++;n=String(n-m);"0"!==n?(g=n+b(g,l),l=0):l++}return 0===
g.length?"0":g},J=a.add=function(b,a){n(b);n(a);if(I(b)&&I(a))return l(b,a);if(z(b)&&z(a))return N(l(E(b),E(a)));if(G(E(b),E(a))){var c=b;b=a;a=c}a=K(E(b),E(a));return I(b)?a:N(a)},O=a.sub=function(b,a){n(b);n(a);return J(b,N(a))},B=a.timesDigit=function(a,e){q(a);u(e,"number");for(var g="",k=c(a),l=0,n=0,m=0;m<k;m++){for(var y=Number(d(a,m))*e+l,l=0;10<=y;)y-=10,l++;0===y?n++:(g=String(y)+b(g,n),n=0)}0<l&&(g=String(l)+b(g,n));return 0===g.length?"0":g},P=a.mulPositive=function(b,a){q(b);q(a);for(var e=
"0",g=c(a),k=0;k<g;k++)var n=B(b,Number(d(a,k))),n=x(n,k),e=l(e,n);return e},Q=a.mul=function(a,b){n(a);n(b);if(v(a,"0")||v(b,"0"))return"0";var c=P(E(a),E(b));return R(a,b)?c:N(c)},S=a.quotientRemainderPositive=function(a,b){q(a);q(b);if(v(a,b))return["1","0"];if(W(b,a))return["0",H(a)];for(var c="0",d=a.length-b.length;;){for(var e=a.slice(0,a.length-d);F(e,b);)e=O(e,b),c=J(c,"1");a=e+a.slice(a.length-d);if(W(b,a))return c=x(c,d),[c,H(a)];d--;c=x(c,1);if(0>d)throw Error("Illegal state");}};a.div=
function(a,b,c){c=void 0===c?!1:c;n(a);n(b);var d=S(E(a),E(b))[0];R(a,b)||(d=N(d));!c||v(Q(d,b),a)||R(a,b)||(d=O(d,"1"));return d};var v=a.eq=function(a,b){return H(a)===H(b)},G=a.lt=function(a,b){return z(a)&&I(b)?!0:I(a)&&z(b)?!1:z(a)&&z(b)?!v(a,b)&&!k(E(a),E(b)):k(a,b)},F=a.ge=function(a,b){return!G(a,b)},W=a.gt=function(a,b){return v(a,b)?!1:F(a,b)},z=a.isNegative=function(a){n(a);return 0===a.indexOf("-")},I=a.isPositive=function(a){return!z(a)},E=a.abs=function(a){return z(a)?N(a):a},N=a.negate=
function(a){return"0"===a?"0":z(a)?a.slice(1):"-"+a},Z=/^(-?)0*([1-9][0-9]*)$/,aa=/^0+$/,H=a.normalize=function(a){if(aa.test(a))return"0";var b=Z.exec(a);if(!b)throw Error("Illegal strint format: "+a);return b[1]+b[2]}})();a.LONG_UPPER_SHIFT="4294967296";a.BYTE_SHIFT="256";g.exports=a},{}],"/lib/util-inspect.js":[function(c,g,a){a.inspect=function(c){if(void 0===c)return"undefined";if(null===c||c.constructor===Object||c.constructor===Array||c.constructor===String||c.constructor===Number||c.constructor===
Boolean||c.constructor===Date)return JSON.stringify(c);if(c.constructor===Set){var d="Set {";c=c.values();for(var b=c.next();!b.done;)d+=a.inspect(b.value),b=c.next(),b.done||(d+=", ");return d+"}"}if(c.constructor===Map){d="Map {";c=c.entries();for(b=c.next();!b.done;)d+=a.inspect(b.value[0]),d+=" \x3d\x3e ",d+=a.inspect(b.value[1]),b=c.next(),b.done||(d+=", ");return d+"}"}return c.constructor.name?c.constructor.name+" "+JSON.stringify(c):JSON.stringify(c)}},{}],1:[function(c){(function(){c("/client-side/common.js");
var g=c("/lib/assert.js");sb.upload=function(a,c){var d=a.type;a=a.value;g.instanceOf(d,sb.Type);g.instanceOf(c,Object);"POST"!==c.type&&"POST"!==c.method&&g.fail("Must use POST when uploading");c.processData=!1;c.data=d.valueBuffer(a);$.ajax(c)}})()},{"/client-side/common.js":"/client-side/common.js","/lib/assert.js":"/lib/assert.js"}],2:[function(c,g,a){function e(a){var b=a.length;if(0<b%4)throw Error("Invalid string. Length must be a multiple of 4");return"\x3d"===a[b-2]?2:"\x3d"===a[b-1]?1:0}
function d(a,c,d){for(var g=[],e=c;e<d;e+=3)c=(a[e]<<16)+(a[e+1]<<8)+a[e+2],g.push(b[c>>18&63]+b[c>>12&63]+b[c>>6&63]+b[c&63]);return g.join("")}a.byteLength=function(a){return 3*a.length/4-e(a)};a.toByteArray=function(a){var b,c,d,g,l;b=a.length;g=e(a);l=new k(3*b/4-g);c=0<g?b-4:b;var u=0;for(b=0;b<c;b+=4)d=m[a.charCodeAt(b)]<<18|m[a.charCodeAt(b+1)]<<12|m[a.charCodeAt(b+2)]<<6|m[a.charCodeAt(b+3)],l[u++]=d>>16&255,l[u++]=d>>8&255,l[u++]=d&255;2===g?(d=m[a.charCodeAt(b)]<<2|m[a.charCodeAt(b+1)]>>
4,l[u++]=d&255):1===g&&(d=m[a.charCodeAt(b)]<<10|m[a.charCodeAt(b+1)]<<4|m[a.charCodeAt(b+2)]>>2,l[u++]=d>>8&255,l[u++]=d&255);return l};a.fromByteArray=function(a){for(var c=a.length,g=c%3,e="",k=[],m=0,l=c-g;m<l;m+=16383)k.push(d(a,m,m+16383>l?l:m+16383));1===g?(a=a[c-1],e+=b[a>>2],e+=b[a<<4&63],e+="\x3d\x3d"):2===g&&(a=(a[c-2]<<8)+a[c-1],e+=b[a>>10],e+=b[a>>4&63],e+=b[a<<2&63],e+="\x3d");k.push(e);return k.join("")};var b=[],m=[],k="undefined"!==typeof Uint8Array?Uint8Array:Array;for(c=0;64>c;++c)b[c]=
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[c],m["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(c)]=c;m[45]=62;m[95]=63},{}],3:[function(c,g){!function(a){function c(a){return a.map(function(a){a=a.toString(16);a=2<a.length?a:Array(2-a.length+1).join("0")+a;return a}).join("")}var d={bytesToHex:function(a){return c(a)},hexToBytes:function(a){if(1===a.length%2)throw Error("hexToBytes can't have a string with an odd number of characters.");0===a.indexOf("0x")&&
(a=a.slice(2));return a.match(/../g).map(function(a){return parseInt(a,16)})}};"undefined"!==typeof g&&g.exports?g.exports=d:a.convertHex=d}(this)},{}],4:[function(c,g){!function(a){var c={bytesToString:function(a){return a.map(function(a){return String.fromCharCode(a)}).join("")},stringToBytes:function(a){return a.split("").map(function(a){return a.charCodeAt(0)})},UTF8:{bytesToString:function(a){return decodeURIComponent(escape(c.bytesToString(a)))},stringToBytes:function(a){return c.stringToBytes(unescape(encodeURIComponent(a)))}}};
"undefined"!==typeof g&&g.exports?g.exports=c:a.convertString=c}(this)},{}],5:[function(c,g){!function(a){function e(a,c){a.constructor===String&&(a=d.convertString.UTF8.stringToBytes(a));for(var g=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225],e=a,k=[],l=0,A=0;l<e.length;l++,A+=8)k[A>>>5]|=e[l]<<24-A%32;a=8*a.length;k[a>>5]|=128<<24-a%32;k[(a+64>>9<<4)+15]=a;for(a=0;a<k.length;a+=16){for(var e=g,l=k,A=a,u=e[0],K=e[1],J=e[2],O=e[3],B=e[4],P=e[5],Q=e[6],S=
e[7],v=0;64>v;v++){if(16>v)m[v]=l[A+v]|0;else{var G=m[v-15],F=m[v-2];m[v]=((G<<25|G>>>7)^(G<<14|G>>>18)^G>>>3)+m[v-7]+((F<<15|F>>>17)^(F<<13|F>>>19)^F>>>10)+m[v-16]}G=S+((B<<26|B>>>6)^(B<<21|B>>>11)^(B<<7|B>>>25))+(B&P^~B&Q)+b[v]+m[v];F=((u<<30|u>>>2)^(u<<19|u>>>13)^(u<<10|u>>>22))+(u&K^u&J^K&J);S=Q;Q=P;P=B;B=O+G|0;O=J;J=K;K=u;u=G+F|0}e[0]=e[0]+u|0;e[1]=e[1]+K|0;e[2]=e[2]+J|0;e[3]=e[3]+O|0;e[4]=e[4]+B|0;e[5]=e[5]+P|0;e[6]=e[6]+Q|0;e[7]=e[7]+S|0}k=[];for(a=0;a<32*g.length;a+=8)k.push(g[a>>>5]>>>24-
a%32&255);return c&&c.asBytes?k:c&&c.asString?d.convertString.bytesToString(k):d.bytesToHex(k)}var d={};"undefined"!==typeof g&&g.exports?(d.bytesToHex=c("convert-hex").bytesToHex,d.convertString=c("convert-string"),g.exports=e):(d.bytesToHex=a.convertHex.bytesToHex,d.convertString=a.convertString,a.sha256=e);var b=[];!function(){function a(a){for(var b=Math.sqrt(a),c=2;c<=b;c++)if(!(a%c))return!1;return!0}function c(a){return 4294967296*(a-(a|0))|0}for(var d=2,e=0;64>e;)a(d)&&(b[e]=c(Math.pow(d,
1/3)),e++),d++}();var m=[];e.x2=function(a,b){return e(e(a,{asBytes:!0}),b)}}(this)},{"convert-hex":3,"convert-string":4}],"/recursive-registry.js":[function(c,g){(function(a){"/"===a&&(a="");var e=c(a+"/lib/assert.js"),d=c(a+"/structure-types.js"),b=new Map;g.exports={registerType:function(a){var c=a.type;a=a.name;e.instanceOf(c,[d.ArrayType,d.MapType,d.SetType,d.StructType,d.TupleType]);e.instanceOf(a,String);e.assert(!b.has(a),'"'+a+'" is already a registered type');b.set(a,c)},getType:function(a){e.instanceOf(a,
String);var c=b.get(a);e.assert(void 0!==c,'"'+a+'" is not a registered type');return c},isRegistered:function(a){return b.has(a)}}}).call(this,"/")},{}],"/structure-types.js":[function(c,g){(function(a){function e(a){h.instanceOf(a,p);this.type=a}function d(a){p.call(this);h.instanceOf(a,w);this.type=a}function b(a){p.call(this);h.instanceOf(a,String);this.name=a}function m(a){p.call(this);h.instanceOf(a,Map);try{h.byteUnsignedInteger(a.size)}catch(X){h.fail(String(a.size)+" types is too many")}this.indexConstructors=
new Map;this.constructorTypes=Array(a.size);var b=new Set;a=f.makeIterator(a);for(var c=a.next();!c.done;c=a.next()){var C=f.makeIterator(c.value),c=C.next().value,C=C.next().value;h.instanceOf(c,Function);var d=c.name;h.assert(d,'Function "'+String(d)+'" does not have a name');h.assert(!b.has(d),'Function name "'+d+'" is repeated');b.add(d);var e=U.fromString(d);try{h.byteUnsignedInteger(e.byteLength)}catch(X){h.fail('Function name "'+d+'" is too long')}h.instanceOf(C,q);d=this.indexConstructors.size;
this.indexConstructors.set(d,c);this.constructorTypes[d]={nameBuffer:e,type:C}}}function k(a){p.call(this);h.instanceOf(a,Array);try{h.byteUnsignedInteger(a.length)}catch(ra){h.fail(String(a.length)+" types is too many")}for(var b=f.makeIterator(a),c=b.next();!c.done;c=b.next())h.instanceOf(c.value,w);this.types=a}function l(a){var b=a.type;a=a.values;h.instanceOf(b,p);h.instanceOf(a,Array);try{h.byteUnsignedInteger(a.length)}catch(X){h.fail(String(a.length)+" values is too many")}for(var c=new Map,
d=0;d<a.length;d++){var C=a[d],e=U.toBinaryString(b.valueBuffer(C));h.assert(!c.has(e),"Value is repeated: "+ea.inspect(C));c.set(e,d)}this.type=b;this.values=a;this.valueIndices=c}function R(a,b){p.call(this);h.instanceOf(a,w);h.instanceOf(b,w);this.keyType=a;this.valueType=b}function x(a){n.apply(this,arguments)}function n(a){p.call(this);h.instanceOf(a,w);this.type=a}function q(a){p.call(this);h.instanceOf(a,Object);var b=0,c;for(c in a)({}).hasOwnProperty.call(a,c)&&b++;try{h.byteUnsignedInteger(b)}catch(X){h.fail(String(b)+
" fields is too many")}this.fields=Array(b);var b=0,d;for(d in a)if({}.hasOwnProperty.call(a,d)){c=U.fromString(d);try{h.byteUnsignedInteger(c.byteLength)}catch(X){h.fail("Field name "+d+" is too long")}var C=a[d];try{h.instanceOf(C,w)}catch(X){h.fail(String(C)+" is not a valid field type")}var e={};this.fields[b]=(e.name=d,e.type=C,e.buffer=c,e);b++}this.fields.sort(function(a,b){if(a.name<b.name)return-1;if(a.name>b.name)return 1})}function A(a){var b=a.type;a=a.length;p.call(this);h.instanceOf(b,
w);h.fourByteUnsignedInteger(a);this.type=b;this.length=a}function u(a){p.apply(this,arguments)}function K(a){p.apply(this,arguments)}function J(a){p.apply(this,arguments)}function O(a){p.apply(this,arguments)}function B(a){p.call(this);h.fourByteUnsignedInteger(a);this.length=a}function P(a){p.apply(this,arguments)}function Q(a){v.apply(this,arguments)}function S(a){v.apply(this,arguments)}function v(a){p.apply(this,arguments)}function G(a){z.apply(this,arguments)}function F(a){z.apply(this,arguments)}
function W(a){z.apply(this,arguments)}function z(a){p.apply(this,arguments)}function I(a){H.apply(this,arguments)}function E(a){H.apply(this,arguments)}function N(a){H.apply(this,arguments)}function Z(a){H.apply(this,arguments)}function aa(a){H.apply(this,arguments)}function H(a){p.apply(this,arguments)}function y(a){M.apply(this,arguments)}function L(a){M.apply(this,arguments)}function ba(a){M.apply(this,arguments)}function ca(a){M.apply(this,arguments)}function da(a){M.apply(this,arguments)}function M(a){p.apply(this,
arguments)}function p(a){w.apply(this,arguments)}function w(){}function Y(a){var b=new ArrayBuffer(4);(new DataView(b)).setUint32(0,a);return b}function T(a,b){if(b&&(b=ga.get(a))){b=f.makeIterator(b);for(var c=b.next();!c.done;c=b.next()){var d=f.makeIterator(c.value),c=d.next().value,d=d.next().value,D=a.length;a.addAll(U.fromBinaryString(c));c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,D);d=f.makeIterator(d);for(D=d.next();!D.done;D=d.next())a.setAll(D.value,c)}}}function V(a){if(a&&a.constructor===
String&&(a=Number(a),!isNaN(a)))return a}function la(a,b){h.instanceOf(a,r);h.instanceOf(b,String);(t.gt(b,"9223372036854775807")||t.lt(b,"-9223372036854775808"))&&h.fail("Value out of range");var c=t.div(b,t.LONG_UPPER_SHIFT,!0);b=t.sub(b,t.mul(c,t.LONG_UPPER_SHIFT));var d=new ArrayBuffer(8),D=new DataView(d);D.setInt32(0,Number(c));D.setUint32(4,Number(b));a.addAll(d)}function ma(a,b){h.instanceOf(b,Array);for(var c=ha(b.length),d=ia(b.length),c=new ArrayBuffer(c?d+1:d),d=new Uint8Array(c),D=0;D<
b.length;D++){var C=b[D];h.instanceOf(C,Boolean);var e=ha(~ha(D));C?d[ia(D)]|=1<<e:d[ia(D)]&=~(1<<e)}a.addAll(c)}"/"===a&&(a="");var h=c(a+"/lib/assert.js"),sa=c("base64-js"),U=c(a+"/lib/buffer-string.js"),ta=c(a+"/config.js"),ua=c("sha256"),r=c(a+"/lib/growable-buffer.js"),ja,t=c(a+"/lib/strint.js"),ea=c("/lib/util-inspect.js"),na=c(a+"/lib/bit-math.js"),ia=na.dividedByEight,ha=na.modEight,oa=new WeakMap,fa=new WeakMap,pa=new WeakMap,ga=new WeakMap;w.prototype.addToBuffer=function(a){h.instanceOf(a,
r);if(this.cachedTypeLocations){if(!fa.get(a)){var b=this.cachedTypeLocations.get(a);if(void 0!==b){a.add(255);var c=new ArrayBuffer(2);try{return(new DataView(c)).setUint16(0,a.length-b),a.addAll(c),!1}catch(ra){}}}}else this.cachedTypeLocations=new Map;this.cachedTypeLocations.set(a,a.length);a.add(this.constructor._value);return!0};w.prototype.toBuffer=function(){this.cachedBuffer||(this.cachedBuffer=this._toBuffer());return this.cachedBuffer};w.prototype._toBuffer=function(){var a=new r;this.addToBuffer(a);
return a.toBuffer()};w.prototype.getHash=function(){this.cachedHash||(this.cachedHash=this._getHash());return this.cachedHash};w.prototype._getHash=function(){return sa.fromByteArray(ua(this.toBuffer(),{asBytes:!0}))};w.prototype.getSignature=function(){this.cachedSignature||(this.cachedSignature=this._getSignature());return this.cachedSignature};w.prototype._getSignature=function(){return ta.VERSION_STRING+this.getHash()};w.prototype.writeValue=function(){h.fail("Generic Type has no value representation")};
w.prototype.valueBuffer=function(a){var b=new r;this.writeValue(b,a);return b.toBuffer()};w.prototype.equals=function(a){try{h.instanceOf(a,this.constructor)}catch(ka){return!1}try{h.equal(a.constructor,this.constructor)}catch(ka){return!1}for(var b in this)if({}.hasOwnProperty.call(this,b)&&!b.startsWith("cached"))try{h.equal(a[b],this[b])}catch(ka){return!1}return!0};f.global.Object.defineProperties(w,{_value:{configurable:!0,enumerable:!0,get:function(){h.fail("Generic Type has no value byte")}}});
f.inherits(p,w);f.inherits(M,p);f.inherits(da,M);da.prototype.writeValue=function(a,b){h.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);h.integer(b);h.between(-128,b,128,"Value out of range");c=new ArrayBuffer(1);(new DataView(c)).setInt8(0,b);a.addAll(c)};f.global.Object.defineProperties(da,{_value:{configurable:!0,enumerable:!0,get:function(){return 1}}});f.inherits(ca,M);ca.prototype.writeValue=function(a,b){h.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);h.integer(b);h.between(-32768,b,32768,"Value out of range");
c=new ArrayBuffer(2);(new DataView(c)).setInt16(0,b);a.addAll(c)};f.global.Object.defineProperties(ca,{_value:{configurable:!0,enumerable:!0,get:function(){return 2}}});f.inherits(ba,M);ba.prototype.writeValue=function(a,b){h.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);h.integer(b);h.between(-2147483648,b,2147483648,"Value out of range");c=new ArrayBuffer(4);(new DataView(c)).setInt32(0,b);a.addAll(c)};f.global.Object.defineProperties(ba,{_value:{configurable:!0,enumerable:!0,get:function(){return 3}}});
f.inherits(L,M);L.prototype.writeValue=function(a,b){la(a,b)};f.global.Object.defineProperties(L,{_value:{configurable:!0,enumerable:!0,get:function(){return 4}}});f.inherits(y,M);y.prototype.writeValue=function(a,b){h.instanceOf(a,r);h.instanceOf(b,String);b=t.normalize(b);var c=[];if(!t.eq(b,"0")){for(;t.gt(b,"127")||t.lt(b,"-128");){var d=t.div(b,t.BYTE_SHIFT,!0);b=t.sub(b,t.mul(d,t.BYTE_SHIFT));c.push(Number(b));b=d}c.push(Number(b));h.twoByteUnsignedInteger(c.length)}d=new ArrayBuffer(2+c.length);
b=new DataView(d);b.setUint16(0,c.length);for(var e=3,D=c.length-2;-1<D;D--,e++)b.setUint8(e,c[D]);c.length&&b.setInt8(2,c[c.length-1]);a.addAll(d)};f.global.Object.defineProperties(y,{_value:{configurable:!0,enumerable:!0,get:function(){return 5}}});f.inherits(H,p);f.inherits(aa,H);aa.prototype.writeValue=function(a,b){h.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);h.integer(b);h.between(0,b,256,"Value out of range");c=new ArrayBuffer(1);(new Uint8Array(c))[0]=b;a.addAll(c)};f.global.Object.defineProperties(aa,
{_value:{configurable:!0,enumerable:!0,get:function(){return 17}}});f.inherits(Z,H);Z.prototype.writeValue=function(a,b){h.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);h.integer(b);h.between(0,b,65536,"Value out of range");c=new ArrayBuffer(2);(new DataView(c)).setUint16(0,b);a.addAll(c)};f.global.Object.defineProperties(Z,{_value:{configurable:!0,enumerable:!0,get:function(){return 18}}});f.inherits(N,H);N.prototype.writeValue=function(a,b){h.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);h.integer(b);
h.between(0,b,4294967296,"Value out of range");c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,b);a.addAll(c)};f.global.Object.defineProperties(N,{_value:{configurable:!0,enumerable:!0,get:function(){return 19}}});f.inherits(E,H);E.prototype.writeValue=function(a,b){h.instanceOf(a,r);h.instanceOf(b,String);(t.gt(b,"18446744073709551615")||t.lt(b,"0"))&&h.fail("Value out of range");var c=t.div(b,t.LONG_UPPER_SHIFT);b=t.sub(b,t.mul(c,t.LONG_UPPER_SHIFT));var d=new ArrayBuffer(8),e=new DataView(d);
e.setUint32(0,Number(c));e.setUint32(4,Number(b));a.addAll(d)};f.global.Object.defineProperties(E,{_value:{configurable:!0,enumerable:!0,get:function(){return 20}}});f.inherits(I,H);I.prototype.writeValue=function(a,b){h.instanceOf(a,r);h.instanceOf(b,String);t.isNegative(b)&&h.fail("Value out of range");var c=[];if(!t.eq(b,"0")){for(;t.ge(b,t.BYTE_SHIFT);){var d=f.makeIterator(t.quotientRemainderPositive(b,t.BYTE_SHIFT));b=d.next().value;d=d.next().value;c.push(Number(d))}c.push(Number(b));h.twoByteUnsignedInteger(c.length)}b=
new ArrayBuffer(2+c.length);d=new DataView(b);d.setUint16(0,c.length);for(var e=2,C=c.length-1;-1<C;C--,e++)d.setUint8(e,c[C]);a.addAll(b)};f.global.Object.defineProperties(I,{_value:{configurable:!0,enumerable:!0,get:function(){return 21}}});f.inherits(z,p);f.inherits(W,z);W.prototype.writeValue=function(a,b){h.instanceOf(b,Date);la(a,String(b.getTime()))};f.global.Object.defineProperties(W,{_value:{configurable:!0,enumerable:!0,get:function(){return 26}}});f.inherits(F,z);F.prototype.writeValue=
function(a,b){h.instanceOf(b,Date);b=new Date(b.getFullYear(),b.getMonth(),b.getDate());b=(b.getTime()-6E4*b.getTimezoneOffset())/864E5;var c=new ArrayBuffer(3),d=new DataView(c);d.setInt16(0,b>>8);d.setUint8(2,b&255);a.addAll(c)};f.global.Object.defineProperties(F,{_value:{configurable:!0,enumerable:!0,get:function(){return 27}}});f.inherits(G,z);G.prototype.writeValue=function(a,b){h.instanceOf(b,Date);var c=new ArrayBuffer(4);(new DataView(c)).setUint32(0,b.getTime()%864E5);a.addAll(c)};f.global.Object.defineProperties(G,
{_value:{configurable:!0,enumerable:!0,get:function(){return 28}}});f.inherits(v,p);f.inherits(S,v);S.prototype.writeValue=function(a,b){h.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);h.instanceOf(b,Number);c=new ArrayBuffer(4);(new DataView(c)).setFloat32(0,b);a.addAll(c)};f.global.Object.defineProperties(S,{_value:{configurable:!0,enumerable:!0,get:function(){return 32}}});f.inherits(Q,v);Q.prototype.writeValue=function(a,b){h.instanceOf(a,r);var c=V(b);void 0!==c&&(b=c);h.instanceOf(b,Number);
c=new ArrayBuffer(8);(new DataView(c)).setFloat64(0,b);a.addAll(c)};f.global.Object.defineProperties(Q,{_value:{configurable:!0,enumerable:!0,get:function(){return 33}}});f.inherits(P,p);P.prototype.writeValue=function(a,b){h.instanceOf(a,r);h.instanceOf(b,Boolean);b?a.add(255):a.add(0)};f.global.Object.defineProperties(P,{_value:{configurable:!0,enumerable:!0,get:function(){return 48}}});f.inherits(B,p);B.prototype.addToBuffer=function(a){p.prototype.addToBuffer.call(this,a)&&a.addAll(Y(this.length))};
B.prototype.writeValue=function(a,b){h.instanceOf(a,r);h.instanceOf(b,Array);b.length!==this.length&&h.fail("Length does not match");ma(a,b)};f.global.Object.defineProperties(B,{_value:{configurable:!0,enumerable:!0,get:function(){return 49}}});f.inherits(O,p);O.prototype.writeValue=function(a,b){h.instanceOf(b,Array);h.fourByteUnsignedInteger(b.length);a.addAll(Y(b.length));ma(a,b)};f.global.Object.defineProperties(O,{_value:{configurable:!0,enumerable:!0,get:function(){return 50}}});f.inherits(J,
p);J.prototype.writeValue=function(a,b){h.instanceOf(a,r);h.instanceOf(b,String);h.assert(1===b.length,"String must contain only 1 character");a.addAll(U.fromString(b))};f.global.Object.defineProperties(J,{_value:{configurable:!0,enumerable:!0,get:function(){return 64}}});f.inherits(K,p);K.prototype.writeValue=function(a,b){h.instanceOf(a,r);h.instanceOf(b,String);b=U.fromString(b);a.addAll(b);a.add(0)};f.global.Object.defineProperties(K,{_value:{configurable:!0,enumerable:!0,get:function(){return 65}}});
f.inherits(u,p);u.prototype.writeValue=function(a,b){h.instanceOf(a,r);h.instanceOf(b,ArrayBuffer);h.fourByteUnsignedInteger(b.byteLength);a.addAll(Y(b.byteLength));a.addAll(b)};f.global.Object.defineProperties(u,{_value:{configurable:!0,enumerable:!0,get:function(){return 66}}});f.inherits(A,p);A.prototype.addToBuffer=function(a){p.prototype.addToBuffer.call(this,a)&&(this.type.addToBuffer(a),a.addAll(Y(this.length)))};A.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(a,r);h.instanceOf(b,
Array);b.length!==this.length&&h.fail("Length does not match: expected "+String(this.length)+" but got "+b.length);b=f.makeIterator(b);for(var d=b.next();!d.done;d=b.next())this.type.writeValue(a,d.value,!1);T(a,c)};f.global.Object.defineProperties(A,{_value:{configurable:!0,enumerable:!0,get:function(){return 80}}});f.inherits(q,p);q.prototype.addToBuffer=function(a){if(p.prototype.addToBuffer.call(this,a)){a.add(this.fields.length);for(var b=f.makeIterator(this.fields),c=b.next();!c.done;c=b.next()){var c=
c.value,d=c.buffer;a.add(d.byteLength);a.addAll(d);c.type.addToBuffer(a)}}};q.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(a,r);h.instanceOf(b,Object);for(var d=f.makeIterator(this.fields),e=d.next();!e.done;e=d.next()){var e=e.value,g=b[e.name];try{e.type.writeValue(a,g,!1)}catch(X){throw void 0===g&&h.fail('Value for field "'+e.name+'" missing'),X;}}T(a,c)};f.global.Object.defineProperties(q,{_value:{configurable:!0,enumerable:!0,get:function(){return 81}}});f.inherits(n,
p);n.prototype.addToBuffer=function(a){p.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};n.prototype._writeValue=function(a,b,c){h.instanceOf(a,r);var d=b.length;void 0===d&&(d=b.size);h.fourByteUnsignedInteger(d);a.addAll(Y(d));b=f.makeIterator(b);for(d=b.next();!d.done;d=b.next())this.type.writeValue(a,d.value,!1);T(a,c)};n.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(b,Array);this._writeValue(a,b,c)};f.global.Object.defineProperties(n,{_value:{configurable:!0,
enumerable:!0,get:function(){return 82}}});f.inherits(x,n);x.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(b,Set);this._writeValue(a,b,c)};f.global.Object.defineProperties(x,{_value:{configurable:!0,enumerable:!0,get:function(){return 83}}});f.inherits(R,p);R.prototype.addToBuffer=function(a){p.prototype.addToBuffer.call(this,a)&&(this.keyType.addToBuffer(a),this.valueType.addToBuffer(a))};R.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(a,r);h.instanceOf(b,
Map);h.fourByteUnsignedInteger(b.size);a.addAll(Y(b.size));b=f.makeIterator(b);for(var d=b.next();!d.done;d=b.next()){var e=f.makeIterator(d.value),d=e.next().value,e=e.next().value;this.keyType.writeValue(a,d,!1);this.valueType.writeValue(a,e,!1)}T(a,c)};f.global.Object.defineProperties(R,{_value:{configurable:!0,enumerable:!0,get:function(){return 84}}});f.inherits(l,w);l.prototype.addToBuffer=function(a){if(w.prototype.addToBuffer.call(this,a)){this.type.addToBuffer(a);a.add(this.valueIndices.size);
for(var b=f.makeIterator(this.valueIndices),c=b.next();!c.done;c=b.next()){var c=f.makeIterator(c.value),d=c.next().value;c.next();a.addAll(U.fromBinaryString(d))}}};l.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(a,r);var d=new r;this.type.writeValue(d,b,!1);d=this.valueIndices.get(U.toBinaryString(d.toBuffer()));h.assert(void 0!==d,"Not a valid enum value: "+ea.inspect(b));a.add(d);T(a,c)};f.global.Object.defineProperties(l,{_value:{configurable:!0,enumerable:!0,get:function(){return 85}}});
f.inherits(k,p);k.prototype.addToBuffer=function(a){if(p.prototype.addToBuffer.call(this,a)){a.add(this.types.length);for(var b=f.makeIterator(this.types),c=b.next();!c.done;c=b.next())c.value.addToBuffer(a)}};k.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(a,r);for(var d=!1,e=0;e<this.types.length;e++){var g=this.types[e],k=new r;try{g.writeValue(k,b,!1)}catch(va){continue}a.add(e);a.addAll(k.toBuffer());d=!0;break}d||h.fail("No types matched: "+ea.inspect(b));T(a,c)};f.global.Object.defineProperties(k,
{_value:{configurable:!0,enumerable:!0,get:function(){return 86}}});f.inherits(m,p);m.prototype.addToBuffer=function(a){if(p.prototype.addToBuffer.call(this,a)){a.add(this.constructorTypes.length);for(var b=f.makeIterator(this.constructorTypes),c=b.next();!c.done;c=b.next()){var d=c.value,c=d.nameBuffer,d=d.type;a.add(c.byteLength);a.addAll(c);d.addToBuffer(a)}}};m.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(a,r);h.instanceOf(b,Object);for(var d,e=f.makeIterator(this.indexConstructors),
g=e.next();!g.done;g=e.next()){var k=f.makeIterator(g.value),g=k.next().value,k=k.next().value;if(b instanceof k){d=g;break}}void 0===d&&h.fail("No types matched: "+ea.inspect(b));a.add(d);this.constructorTypes[d].type.writeValue(a,b,!1);T(a,c)};f.global.Object.defineProperties(m,{_value:{configurable:!0,enumerable:!0,get:function(){return 88}}});f.inherits(b,p);b.prototype.addToBuffer=function(a){if(p.prototype.addToBuffer.call(this,a)){var b=oa.get(a);b||(b=new Map,oa.set(a,b));var c=b.get(this.name),
d=void 0===c;d&&(c=b.size,h.twoByteUnsignedInteger(c),b.set(this.name,c));b=new ArrayBuffer(2);(new DataView(b)).setUint16(0,c);a.addAll(b);d&&(c=fa.get(a)||0,fa.set(a,c+1),this.type.addToBuffer(a),fa.set(a,c))}};b.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(a,r);var d=!0,e=pa.get(a);if(e){var g=e.get(b);if(void 0!==g){d=!1;a.add(0);g=a.length-g;h.fourByteUnsignedInteger(g);var k=new ArrayBuffer(4);(new DataView(k)).setUint32(0,g);a.addAll(k)}}else e=new Map,pa.set(a,e);d&&
(a.add(255),e.set(b,a.length),this.type.writeValue(a,b,!1));T(a,c)};f.global.Object.defineProperties(b.prototype,{type:{configurable:!0,enumerable:!0,get:function(){ja||(ja=c(a+"/recursive-registry.js"));return ja.getType(this.name)}}});f.global.Object.defineProperties(b,{_value:{configurable:!0,enumerable:!0,get:function(){return 87}}});f.inherits(d,p);d.prototype.addToBuffer=function(a){p.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};d.prototype.writeValue=function(a,b,c){c=void 0===
c?!0:c;h.instanceOf(a,r);null===b||void 0===b?a.add(0):(a.add(255),this.type.writeValue(a,b,!1));T(a,c)};f.global.Object.defineProperties(d,{_value:{configurable:!0,enumerable:!0,get:function(){return 96}}});f.inherits(e,w);e.prototype.addToBuffer=function(a){w.prototype.addToBuffer.call(this,a)&&this.type.addToBuffer(a)};e.prototype.writeValue=function(a,b,c){c=void 0===c?!0:c;h.instanceOf(a,r);var d=ga.get(a);d||(d=new Map,ga.set(a,d));var e=new r;this.type.writeValue(e,b,!1);b=U.toBinaryString(e.toBuffer());
var e=a.length,g=d.get(b);g?g.add(e):d.set(b,new Set([e]));a.addAll(new ArrayBuffer(4));T(a,c)};f.global.Object.defineProperties(e,{_value:{configurable:!0,enumerable:!0,get:function(){return 112}}});g.exports={Type:w,ByteType:da,ShortType:ca,IntType:ba,LongType:L,BigIntType:y,UnsignedByteType:aa,UnsignedShortType:Z,UnsignedIntType:N,UnsignedLongType:E,BigUnsignedIntType:I,DateType:W,DayType:F,TimeType:G,FloatType:S,DoubleType:Q,BooleanType:P,BooleanTupleType:B,BooleanArrayType:O,CharType:J,StringType:K,
OctetsType:u,TupleType:A,StructType:q,ArrayType:n,SetType:x,MapType:R,EnumType:l,ChoiceType:k,NamedChoiceType:m,RecursiveType:b,OptionalType:d,PointerType:e,REPEATED_TYPE:255,MILLIS_PER_DAY:864E5,MILLIS_PER_MINUTE:6E4}}).call(this,"/")},{"/lib/util-inspect.js":"/lib/util-inspect.js","base64-js":2,sha256:5}]},{},[1]);}()