language: node_js
node_js:
  - "node"
after_success:
  - ./node_modules/.bin/jscoverage . ../structure-bytes-cov
  - ./node_modules/.bin/mocha ./test/main.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js